histmgr::ProfileCollection_t Class Reference
One or two dimensional collection of profile histograms.
#include <ProfileCollection_t.hh>Inheritance diagram for histmgr::ProfileCollection_t::
Public Member Functions
ProfileCollection_t (const std::string &collection_name, const EVENT::StringVec &name_list, UInt_t n_hist, const HistPar &par) throw (std::bad_alloc, std::runtime_error)
Create a collection of profile histograms which will have the same binning of the x-axis.
ProfileCollection_t (const std::string &collection_name, const EVENT::StringVec &name_list, const lcio::IntVec &n_hist_list, const HistPar &par)
Create a collection of profile histograms which will have the same binning of the x-axis.
ProfileCollection_t (lcio::LCCollection *profile_histograms, lcio::IntVec *indices)
ProfileCollection_t (lcio::LCCollection *profile_histograms)
Create a profile histogram collection from lcio collection.
ProfileCollection_t (const ProfileCollection_t &a)
copy constructor.
ProfileCollection_t ()
Default constructor.
void deleteCollection ()
delete the histogram collection and the index array This method exists instead of a destrctor to prevent copying the arrays (FIXME)
void deleteSharedStorage ()
lcio::LCCollection * createProfiles (const std::string &collection_name, const EVENT::StringVec &name_list, UInt_t n_hist, const HistPar &par) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * createProfiles (const std::string &collection_name, const EVENT::StringVec &name_list, const lcio::IntVec &n_hist_list, const HistPar &par) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * collection ()
get the unique group id
const lcio::LCCollection * collection () const
get the collection of histograms (read only).
UInt_t n () const
get the number of histograms in the one dimensional collection.
bool is2D () const
Return true if the histogram collection is two instead of one diemensional.
UInt_t nMajor () const
get the number of histograms in the one dimensional collection.
UInt_t nMinor (UInt_t major_index) const
get the number of histograms in the one dimensional collection.
const Profile1D * histogram (UInt_t index) const
Get one histogram of the collection (read only).
Profile1D * histogram (UInt_t index)
Get one histogram of the collection.
Profile1D * histogram (UInt_t major_index, UInt_t minor_index)
Get one histogram of the collection which is organised as a two dimensional array.
const Profile1D * histogram (UInt_t major_index, UInt_t minor_index) const
Get one histogram of the collection which is organised as a two dimensional array (read only).
const std::string & getName (UInt_t major_index) const
Get the name of the specified element of the histogram collection.
Protected Member Functions
UInt_t get_index (UInt_t major_index, UInt_t minor_index) const throw (std::range_error)
Static Protected Attributes
static const std::string __histogramNameParameterName
Private Member Functions
void copyNames () const
Copy the names from the collection to an accessible vector.
Private Attributes
lcio::LCCollection * _histogramCol
the histogram collection
lcio::IntVec * _majorIndex
optional list of offset to form a two dimensional array out of the list.
lcio::StringVec _nameList
A vector which contains one name for all histograms of the collection or a name for each element.
Static Private Attributes
static const std::string __majorIndexParameterName
static const std::string __defaultProfileName
Friends
class HistMgr
Detailed Description
One or two dimensional collection of profile histograms.
Definition at line 19 of file ProfileCollection_t.hh.
Constructor & Destructor Documentation
histmgr::ProfileCollection_t::ProfileCollection_t (const std::string & collection_name, const EVENT::StringVec & name_list, UInt_t n_hist, const HistPar & par) throw (std::bad_alloc, std::runtime_error) [inline]
Create a collection of profile histograms which will have the same binning of the x-axis.
Parameters
collection_name the of the histogram collection
name_list a vector which contains a name for each profile histogram of the collection.
n_hist the number of histograms to be created
par the binning of the histograms
If the name_list is empty the name of the collection is used. The name will be extended by the index in the collection.
The profile histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Definition at line 36 of file ProfileCollection_t.hh.
References createProfiles().
histmgr::ProfileCollection_t::ProfileCollection_t (const std::string & collection_name, const EVENT::StringVec & name_list, const lcio::IntVec & n_hist_list, const HistPar & par) [inline]
Create a collection of profile histograms which will have the same binning of the x-axis.
Parameters
collection_name the of the histogram collection
name_list a vector containing the names of the profile histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all profile histograms.
n_hist_list the number of profile histograms to be created
par the binning of the histogram
Returns
pointer to the histogram collection
The profile histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Definition at line 60 of file ProfileCollection_t.hh.
References createProfiles().
histmgr::ProfileCollection_t::ProfileCollection_t (lcio::LCCollection * profile_histograms, lcio::IntVec * indices) [inline]
Parameters
profile_histograms the linearised one or two dimensional collection of profile histograms
indices optional list of indicies used to give two dimensional access to the profile histogram list. for each possible index of the first dimension is needed which contains the offset in the list. The second index is added to this offset.
Definition at line 76 of file ProfileCollection_t.hh.
References _majorIndex.
histmgr::ProfileCollection_t::ProfileCollection_t (lcio::LCCollection * profile_histograms) [inline]
Create a profile histogram collection from lcio collection.
Parameters
profile_histograms the linearised one or two dimensional collection of profile histograms (two dimensional collections have the collection parameter `major`). The method does not verify whether the lcio collection really is a histogram collection. However, if the collection has the parameter `major` it creates an index vector (costly operation) assuming that it is a 2d array instead of a 1d array(i.e. collection). The unique group id remains undedfined since it is not stored in the lcio collection.
Definition at line 98 of file ProfileCollection_t.hh.
References _majorIndex.
Member Function Documentation
const lcio::LCCollection* histmgr::ProfileCollection_t::collection () const [inline]
get the collection of histograms (read only). The index array needed for the two dimensional acces is added as a parameter named `major`.
Definition at line 195 of file ProfileCollection_t.hh.
References _histogramCol.
lcio::LCCollection* histmgr::ProfileCollection_t::collection () [inline]
get the unique group id get the collection of histograms. The index array needed for the two dimensional acces is added as a parameter named `major`.
Definition at line 190 of file ProfileCollection_t.hh.
References _histogramCol.
void histmgr::ProfileCollection_t::copyNames () const [inline, private]
Copy the names from the collection to an accessible vector. The vector of histogram names is attached as a parameter to the LCCollection.
Definition at line 275 of file ProfileCollection_t.hh.
References _histogramCol, and _nameList.
Referenced by getName().
lcio::LCCollection * histmgr::ProfileCollection_t::createProfiles (const std::string & collection_name, const EVENT::StringVec & name_list, const lcio::IntVec & n_hist_list, const HistPar & par) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension).
Parameters
collection_name the of the histogram collection
name_list a vector containing the names of the histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all histograms.
n_hist_list the number of histograms to be created
par the binning of the histogram
Returns
pointer to the histogram collection
The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Definition at line 66 of file ProfileCollection_t.cc.
lcio::LCCollection * histmgr::ProfileCollection_t::createProfiles (const std::string & collection_name, const EVENT::StringVec & name_list, UInt_t n_hist, const HistPar & par) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension).
Parameters
collection_name the of the histogram collection
name_list a vector containing the names of the profile histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all profile histograms.
n_hist the number of histograms to be created
par the binning of the histograms
Returns
pointer to the histogram collection.
The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Definition at line 16 of file ProfileCollection_t.cc.
Referenced by ProfileCollection_t().
const std::string& histmgr::ProfileCollection_t::getName (UInt_t major_index) const [inline]
Get the name of the specified element of the histogram collection.
Parameters
major_index the index of the histogram element or in case of an 2D histogram array the major index.
Returns
a reference to the name.
Definition at line 259 of file ProfileCollection_t.hh.
References _nameList, and copyNames().
Field Documentation
lcio::IntVec* histmgr::ProfileCollection_t::_majorIndex [private]
optional list of offset to form a two dimensional array out of the list.
Definition at line 285 of file ProfileCollection_t.hh.
Referenced by deleteCollection(), is2D(), nMajor(), nMinor(), and ProfileCollection_t().
lcio::StringVec histmgr::ProfileCollection_t::_nameList [mutable, private]
A vector which contains one name for all histograms of the collection or a name for each element.
Definition at line 287 of file ProfileCollection_t.hh.
Referenced by copyNames(), and getName().
The documentation for this class was generated from the following files:
ProfileCollection_t.hh
ProfileCollection_t.cc