CALICE::CellParameter Class Reference
Information about a pad: Pedestal, noise, etc.
#include <CellParameter.hh>
Public Member Functions
CellParameter (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
void resetSums ()
Reset the sums which are used to calculate the pedestals and the noise.
void resetSaturationCounter ()
void resetHitCounter ()
void resetAll ()
void setSum (Float_t a_sum)
Set the sum of the adc values (used to calculate the pedestal).
Float_t getSum () const
Get the sum of the adc values (used to calculate the pedestal).
void setSum2 (Float_t a_sum2)
Set the sum of the adc values squared (used to calculate the noise).
Float_t getSum2 () const
Get the sum of the adc values squared (used to calculate the noise).
void setNValues (UInt_t n_values)
Set the number of values added to the sums.
UInt_t getNValues () const
Get the number of values added to the sums.
void setPedestal (Float_t a_pedestal)
Set the pedestal.
Float_t getPedestal () const
Get the pedestal.
void setOldPedestal (Float_t an_old_pedestal)
Set the old pedestal.
Float_t getOldPedestal () const
Get the old pedestal The result is undefined before the pedestals and the noise have been adjusted or calculated.
void setNoise (Float_t a_noise)
Set the noise.
Float_t getNoise () const
Get the noise.
void setOldNoise (Float_t an_old_noise)
Set the old noise.
Float_t getOldNoise () const
Get the old noise.
void setMaxValue (Float_t a_max_value)
set the maximum value for a cell (shares storage with pedestal).
Float_t getMaxValue () const
get the maximum value of a cell (shares storage with pedestal) This function only returns the expected result before pedestals/noise are calculated.
void add (Float_t adc)
Build sums used to calculate pedestals and noise.
void sub (Float_t adc)
Subtract a previously added adc value from the sums to return to the prior condition.
void calculate ()
Caluclate the pedestal and the noise from the sums.
void adjustPedestalNoise (Float_t adc, UInt_t keep_n_minus_one)
Adjust the pedestal and the noise using the new ADC value.
Bool_t isDead () const
Return kTRUE if the pad is considered to be dead.
void setDead (Bool_t is_dead=true)
Declare the pad to be dead (or revive pad (is_dead=kFALSE).
UInt_t getSaturationCounter () const
Get the value of the saturation counter.
void incrementSaturationCounter ()
Increment the saturation counter.
UInt_t getNHits () const
Get the number of hits.
void incrementNHits ()
Increment the hit counter.
Float_t getNHitsFloat () const
Function which returns the number of hits converted into a float.
void initADCMemory ()
Initialse the array which memorises the last pedestal subtracted values.
void setADCMemoryValue (UInt_t memory_cell_i, Float_t an_adc_value)
Memorise an ADC value in the given cell.
Float_t getADCMemoryValue (UInt_t memory_cell_i) const
Get a memorised ADC value from the given cell.
void setADCMemoryWritePos (UInt_t memory_cell_i)
Set the current ADC memory cell.
void setNextADCMemory ()
Float_t getADCMemoryValue () const
Get a memorised ADC value.
void setADCMemoryValue (Float_t pedestal_subtracted_value)
Memorise an ADC value.
Float_t getMeanADCValue (Float_t pedestal_subtracted_value)
Get the mean value of a group of pedestal subtracted ADC values (the maximum is removed).
void shiftPedestal (Float_t shift)
Shift the current and the old pedestal by this value.
UInt_t getNPedestalChanges () const
Get the value of the pedestal change counter.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Protected Member Functions
void setSaturationCounter (UInt_t saturation)
Set the value of the saturation counter.
void setNHits (UInt_t n_hits)
Set the value of the hit counter.
void setNPedestalChanges (UInt_t n_pedestal_changes)
Set the value of the pedestal change counter.
void incrementNPedestalChanges ()
Increment the pedestal change counter.
Detailed Description
Information about a pad: Pedestal, noise, etc. This class hold the pedestal, the noise, the number of accumulated hits, a saturation counter and a flag which indicates whether the pad is considered to be dead.
Definition at line 70 of file CellParameter.hh.
Member Function Documentation
void CALICE::CellParameter::add (Float_t adc) [inline]
Build sums used to calculate pedestals and noise. The storage for the old pedestals and noise is abused to store the sums
See also
CellParameter::sub
Definition at line 190 of file CellParameter.hh.
Referenced by CALICE::SimpleHitSearch::accumulateEventsForInitialPedestalNoiseCalculation(), CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejection(), and CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection().
void CALICE::CellParameter::adjustPedestalNoise (Float_t adc, UInt_t keep_n_minus_one) [inline]
Adjust the pedestal and the noise using the new ADC value.
Parameters
adc the new ADC value
keep_n_minus_one the current pedestal and noise are given a weight of this value + 1 and the new ADC value get the weight 1
The current pedestal and the current noise are memorised (getPedestal and getNoise) and then they are updated.
Definition at line 230 of file CellParameter.hh.
References getNoise(), getPedestal(), setNoise(), setOldNoise(), setOldPedestal(), and setPedestal().
Referenced by CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise().
Float_t CALICE::CellParameter::getMeanADCValue (Float_t pedestal_subtracted_value) [inline]
Get the mean value of a group of pedestal subtracted ADC values (the maximum is removed). The mean value is used to track jumps in the pedestal. If the jump is larger than a certain threshold the pedestal is considered to have changed.
Definition at line 387 of file CellParameter.hh.
References getADCMemoryValue(), and setADCMemoryValue().
Referenced by CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection().
UInt_t CALICE::CellParameter::getNHits () const [inline]
Get the number of hits. The hit counter is increased when ever the pedestal subtracted ADC value is above a signal or signal-to-noise threshold.
Definition at line 291 of file CellParameter.hh.
Referenced by getNHitsFloat(), and incrementNHits().
Float_t CALICE::CellParameter::getNHitsFloat () const [inline]
Function which returns the number of hits converted into a float. This function can be used together with getNoise and getPedestal in a generic way (e.g. typedef Float_t CellParameter::*GetFloatFunc_t();)
Definition at line 302 of file CellParameter.hh.
References getNHits().
Float_t CALICE::CellParameter::getNoise () const [inline]
Get the noise. The result is undefined before the pedestals and the noise are calculated.
Definition at line 153 of file CellParameter.hh.
Referenced by CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejection(), CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection(), adjustPedestalNoise(), CALICE::SimpleHitSearch::calculatePedestalNoiseAndDeclareCellsDead(), CALICE::PedestalNoiseHistograms::processEvent(), CALICE::AverageHistoryGraphs::processEvent(), CALICE::SimpleHitSearch::searchHits(), CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise(), and CALICE::SimpleHitSearch::showNoiseStat().
UInt_t CALICE::CellParameter::getNPedestalChanges () const [inline]
Get the value of the pedestal change counter. The PedestalChange counter is increased when ever the ADC value is outside of a certain range
Definition at line 425 of file CellParameter.hh.
Referenced by incrementNPedestalChanges().
Float_t CALICE::CellParameter::getOldNoise () const [inline]
Get the old noise. The result is undefined before the pedestals and the noise have been adjusted or calculated. In the latter case the old and the `new` noise are the same.
Definition at line 164 of file CellParameter.hh.
Referenced by CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise(), and CALICE::SimpleHitSearch::showCurrentNoiseStat().
Float_t CALICE::CellParameter::getOldPedestal () const [inline]
Get the old pedestal The result is undefined before the pedestals and the noise have been adjusted or calculated. In the latter case the old and the `new` pedestals are the same.
Definition at line 143 of file CellParameter.hh.
Referenced by CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise(), shiftPedestal(), and CALICE::SimpleHitSearch::showCurrentNoiseStat().
Float_t CALICE::CellParameter::getPedestal () const [inline]
Get the pedestal. The result is undefined before the pedestals and the noise are calculated.
Definition at line 131 of file CellParameter.hh.
Referenced by CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejection(), CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection(), adjustPedestalNoise(), CALICE::SimpleHitSearch::calculatePedestalNoiseAndDeclareCellsDead(), initADCMemory(), CALICE::PedestalNoiseHistograms::processEvent(), CALICE::AverageHistoryGraphs::processEvent(), CALICE::SimpleHitSearch::searchHits(), CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise(), shiftPedestal(), and CALICE::SimpleHitSearch::showNoiseStat().
UInt_t CALICE::CellParameter::getSaturationCounter () const [inline]
Get the value of the saturation counter. The saturation counter is increased when ever the ADC value is outside of a certain range. The saturation counter is used to mark cells as dead. Thus, it must not be incremented if a cell is dead.
Definition at line 274 of file CellParameter.hh.
Referenced by CALICE::SimpleHitSearch::calculatePedestalNoiseAndDeclareCellsDead(), incrementSaturationCounter(), and isDead().
Float_t CALICE::CellParameter::getSum () const [inline]
Get the sum of the adc values (used to calculate the pedestal). The result is undefined after the noise and the pedestals have been calculated.
Definition at line 101 of file CellParameter.hh.
Referenced by calculate().
Float_t CALICE::CellParameter::getSum2 () const [inline]
Get the sum of the adc values squared (used to calculate the noise). The result is undefined after the noise and the pedestals have been calculated.
Definition at line 112 of file CellParameter.hh.
Referenced by calculate().
void CALICE::CellParameter::incrementNHits () [inline]
Increment the hit counter. The hit counter is increased when ever the ADC value is outside of a certain range
Definition at line 296 of file CellParameter.hh.
References getNHits(), and setNHits().
Referenced by CALICE::SimpleHitSearch::searchHits(), and CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise().
void CALICE::CellParameter::incrementNPedestalChanges () [inline, protected]
Increment the pedestal change counter. The PedestalChange counter is increased when ever the ADC value is outside of a certain range
Definition at line 431 of file CellParameter.hh.
References getNPedestalChanges(), and setNPedestalChanges().
Referenced by shiftPedestal().
void CALICE::CellParameter::incrementSaturationCounter () [inline]
Increment the saturation counter. The saturation counter is increased when ever the ADC value is outside of a certain range
Definition at line 279 of file CellParameter.hh.
References getSaturationCounter(), and setSaturationCounter().
Referenced by CALICE::SimpleHitSearch::accumulateEventsForInitialPedestalNoiseCalculation(), CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejection(), CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection(), CALICE::SimpleHitSearch::searchHits(), and CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise().
void CALICE::CellParameter::initADCMemory () [inline]
Initialse the array which memorises the last pedestal subtracted values.
Todo initialsie with pedestal or zero?
Definition at line 308 of file CellParameter.hh.
References getPedestal(), and setADCMemoryValue().
void CALICE::CellParameter::resetSums () [inline]
Reset the sums which are used to calculate the pedestals and the noise. This function should be called before ADC values are accumulated and added with add to the sums.
Definition at line 86 of file CellParameter.hh.
References setNValues(), setSum(), and setSum2().
void CALICE::CellParameter::setADCMemoryValue (Float_t pedestal_subtracted_value) [inline]
Memorise an ADC value. The given pedestal subtracted ADC value is memorised at the current write postion and the position counter is advanced.
Definition at line 379 of file CellParameter.hh.
void CALICE::CellParameter::setDead (Bool_t is_dead = true) [inline]
Declare the pad to be dead (or revive pad (is_dead=kFALSE). The status whether a pad is dead is stored in the saturation counter. Thus, a reviving a cell will reset the saturation counter to zero.
Definition at line 260 of file CellParameter.hh.
References setSaturationCounter().
Referenced by CALICE::SimpleHitSearch::calculatePedestalNoiseAndDeclareCellsDead().
void CALICE::CellParameter::setMaxValue (Float_t a_max_value) [inline]
set the maximum value for a cell (shares storage with pedestal). The maximum value is stored in the same place as the pedestal. Thus, the maximum value can only be used during the initial accumulation of pedestal/noise statistics.
kCellParameterFloatMaxValue and kCellParameterFloatPedestal point to the same cell
Definition at line 174 of file CellParameter.hh.
Referenced by CALICE::SimpleHitSearch::accumulateEventsForInitialPedestalNoiseCalculation().
void CALICE::CellParameter::setNHits (UInt_t n_hits) [inline, protected]
Set the value of the hit counter. The hit counter is increased when ever the pedestal subtracted ADC value is above a signal or signal-to-noise threshold.
Definition at line 285 of file CellParameter.hh.
Referenced by incrementNHits().
void CALICE::CellParameter::setNPedestalChanges (UInt_t n_pedestal_changes) [inline, protected]
Set the value of the pedestal change counter. The PedestalChange counter is increased when ever the ADC value is outside of a certain range
Definition at line 419 of file CellParameter.hh.
Referenced by incrementNPedestalChanges().
void CALICE::CellParameter::setOldNoise (Float_t an_old_noise) [inline]
Set the old noise. The old noise shares the storage with the sum2. Thus, after this call the sum2 is invalid.
Definition at line 158 of file CellParameter.hh.
Referenced by adjustPedestalNoise(), and calculate().
void CALICE::CellParameter::setOldPedestal (Float_t an_old_pedestal) [inline]
Set the old pedestal. The old pedestal shares the storage with the sum. Thus, after this call the sum is invalid.
Definition at line 137 of file CellParameter.hh.
Referenced by adjustPedestalNoise(), calculate(), CALICE::SimpleHitSearch::searchHits(), and shiftPedestal().
void CALICE::CellParameter::setSaturationCounter (UInt_t saturation) [inline, protected]
Set the value of the saturation counter. The saturation counter is increased when ever the ADC value is outside of a certain range
Definition at line 266 of file CellParameter.hh.
Referenced by incrementSaturationCounter(), and setDead().
void CALICE::CellParameter::setSum (Float_t a_sum) [inline]
Set the sum of the adc values (used to calculate the pedestal). After this call the pedestals and the noise are invalid.
Definition at line 96 of file CellParameter.hh.
Referenced by resetSums().
void CALICE::CellParameter::setSum2 (Float_t a_sum2) [inline]
Set the sum of the adc values squared (used to calculate the noise). After this call the pedestals and the noise are invalid.
Definition at line 107 of file CellParameter.hh.
Referenced by resetSums().
void CALICE::CellParameter::shiftPedestal (Float_t shift) [inline]
Shift the current and the old pedestal by this value. The pedestal is shifted when a pedestal jump is detected.
Definition at line 409 of file CellParameter.hh.
References getOldPedestal(), getPedestal(), incrementNPedestalChanges(), setOldPedestal(), and setPedestal().
Referenced by CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection().
void CALICE::CellParameter::sub (Float_t adc) [inline]
Subtract a previously added adc value from the sums to return to the prior condition.
See also
CellParameter::add
Definition at line 199 of file CellParameter.hh.
Referenced by CALICE::SimpleHitSearch::accumulateEventsForInitialPedestalNoiseCalculation().
The documentation for this class was generated from the following file:
CellParameter.hh