histmgr::KeyMap_t< _MapElm_t_ > Class Template Reference
List of elements (KeyMap).
#include <KeyMap_t.hh>Inheritance diagram for histmgr::KeyMap_t< _MapElm_t_ >::
Public Types
typedef KeyMapIterator_t< _MapElm_t_ > iterator
typedef KeyMapConstIterator_t< _MapElm_t_ > const_iterator
Public Member Functions
bool hasKey (const Key_t &a_key) const
Check whether an element exist already for the given key.
void assign (const Key_t &a_key, const _MapElm_t_ &elm)
Assign an element to the given key.
_MapElm_t_ & operator[] (const Key_t &a_key)
Get the element assigned to the given key.
const _MapElm_t_ & operator[] (const Key_t &a_key) const
Get the element assigned to the given key (read only access).
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Private Attributes
std::vector< _MapElm_t_ > _elmList
Friends
class HistMgr
Detailed Description
template<typename _MapElm_t_> class histmgr::KeyMap_t< _MapElm_t_ >
List of elements (KeyMap). The elements are identified by their names. A contrinuous serial number is assigned to each element. The serial number can be used to quickly access the histograms
Definition at line 196 of file KeyMap_t.hh.
Member Function Documentation
template<typename _MapElm_t_> void histmgr::KeyMap_t< _MapElm_t_ >::assign (const Key_t & a_key, const _MapElm_t_ & elm) [inline]
Assign an element to the given key.
Parameters
a_key the key to which an element should be assigned.
elm the element. If an element is already assigned to the key, then the old element is deleted.
Definition at line 221 of file KeyMap_t.hh.
Referenced by histmgr::HistMgr::getOrCreatehistogramGroup(), histmgr::HistMgr::Group_t::setGraphCollection(), histmgr::HistMgr::Group_t::setHistogram2DCollection(), histmgr::HistMgr::Group_t::setHistogramCollection(), and histmgr::HistMgr::Group_t::setProfileCollection().
template<typename _MapElm_t_> const _MapElm_t_& histmgr::KeyMap_t< _MapElm_t_ >::operator[] (const Key_t & a_key) const [inline]
Get the element assigned to the given key (read only access).
Parameters
a_key the key of the element.
Definition at line 247 of file KeyMap_t.hh.
template<typename _MapElm_t_> _MapElm_t_& histmgr::KeyMap_t< _MapElm_t_ >::operator[] (const Key_t & a_key) [inline]
Get the element assigned to the given key.
Parameters
a_key the key of the element.
Definition at line 236 of file KeyMap_t.hh.
The documentation for this class was generated from the following file:
KeyMap_t.hh