CALICE::HoldScanAnalysis Class Reference
Create Signal histograms per pad of all hits of all reconstructed clusters.
#include <HoldScanAnalysis.hh>Inheritance diagram for CALICE::HoldScanAnalysis::
Public Member Functions
Processor * newProcessor ()
void init ()
Called at the begin of the job before anything is read.
void processRunHeader (LCRunHeader *run)
Called for every run, e.g.
void processEvent (LCEvent *evtP)
Called for every event - the working horse.
void end ()
Protected Types
enum EHistType { kHistSignalPerHoldValue,
kHistTotalSignalPerHoldValue,
kNHist
 }
Protected Member Functions
void createHistograms ()
create and register histogram collections.
void feConfChanged (EVENT::LCCollection *col)
Handle changes of Fe configuration data.
void moduleTypeChanged (lcio::LCCollection *col)
void moduleLocationChanged (lcio::LCCollection *col)
void moduleConnectionChanged (lcio::LCCollection *col)
Protected Attributes
FloatVec _signalHistPar
binning of the per hold value histograms.
std::string _clusterColName
std::string _feConfColName
histmgr::Key_t _histGroupKey
Key for the histogram group.
int _nHistMax
Maximum number of hold values for which signal histograms can be created (parameter).
int _minNumberOfHits
Minimum number of hits of accepted clusters (parameter).
Float_t _minClusterSignal
Minimum signal of accepted clusters (parameter).
ConditionsChangeDelegator< HoldScanAnalysis > _feConfChange
ModuleIndexReverseLookup _indexLookup
LCCollection * _nHitsHistogram
LCCollection * _clusterSignalHistogram
LCCollection * _holdValueContainer
histmgr::Key_t _histKey [kNHist]
UInt_t _nHist
std::map< int, UInt_t > _holdStartMap
std::vector< UInt_t > _histogramIndex
UInt_t _nClusters
UInt_t _nMissingHoldChanges
UInt_t _moduleIndexOutOfRange
UInt_t _nBeamOrCosmicsEvents
UInt_t _currentCommonHoldStart
Detailed Description
Create Signal histograms per pad of all hits of all reconstructed clusters. This class derives from VRawADCValueProcessor, since the information about the detector is needed to setup the signal histograms.
Definition at line 25 of file HoldScanAnalysis.hh.
Member Function Documentation
void CALICE::HoldScanAnalysis::createHistograms () [protected]
create and register histogram collections.
Definition at line 105 of file HoldScanAnalysis.cc.
References _histGroupKey, _nHistMax, _signalHistPar, histmgr::HistMgr::createHistogramGroup(), and histmgr::HistMgr::createHistograms().
Referenced by init().
void CALICE::HoldScanAnalysis::init ()
Called at the begin of the job before anything is read. Use to initialize the processor, e.g. book histograms.
Reimplemented from CALICE::VRawADCValueProcessor .
Definition at line 128 of file HoldScanAnalysis.cc.
References _histGroupKey, _nHistMax, histmgr::HistMgr::createHistograms(), and createHistograms().
void CALICE::HoldScanAnalysis::processEvent (LCEvent * evtP)
Called for every event - the working horse.
Definition at line 161 of file HoldScanAnalysis.cc.
References _histGroupKey, _minClusterSignal, histmgr::HistMgr::getHistogramCollection(), CALICE::ModuleIndexReverseLookup::getModuleAndCellIndex(), and histmgr::HistogramCollection_t::histogram().
void CALICE::HoldScanAnalysis::processRunHeader (LCRunHeader * run) [inline]
Called for every run, e.g. overwrite to initialize run dependent histograms.
Definition at line 43 of file HoldScanAnalysis.hh.
Field Documentation
histmgr::Key_t CALICE::HoldScanAnalysis::_histGroupKey [protected]
Key for the histogram group.
Definition at line 63 of file HoldScanAnalysis.hh.
Referenced by createHistograms(), init(), and processEvent().
Float_t CALICE::HoldScanAnalysis::_minClusterSignal [protected]
Minimum signal of accepted clusters (parameter).
Definition at line 68 of file HoldScanAnalysis.hh.
Referenced by processEvent().
int CALICE::HoldScanAnalysis::_minNumberOfHits [protected]
Minimum number of hits of accepted clusters (parameter).
Definition at line 67 of file HoldScanAnalysis.hh.
FloatVec CALICE::HoldScanAnalysis::_signalHistPar [protected]
binning of the per hold value histograms.
Definition at line 56 of file HoldScanAnalysis.hh.
Referenced by createHistograms().
The documentation for this class was generated from the following files:
HoldScanAnalysis.hh
HoldScanAnalysis.cc