histmgr::GraphCollection_t Class Reference
Light wrapper around a LCCollection to facilitate the handling of collections of graphs.
#include <GraphCollection_t.hh>Inheritance diagram for histmgr::GraphCollection_t::
Public Member Functions
GraphCollection_t (const std::string &collection_name, unsigned int n_graphs, const EVENT::StringVec &type_names, unsigned int n_expected_values, const EVENT::StringVec &opt_major_names) throw (std::bad_alloc, std::runtime_error)
GraphCollection_t (const std::string &collection_name, const std::vector< unsigned int > &n_graphs, const std::vector< std::string > &type_names, unsigned int n_expected_values, const std::vector< std::string > &opt_major_names) throw (std::bad_alloc, std::runtime_error)
GraphCollection_t (lcio::LCCollection *graphs, lcio::IntVec *indices)
GraphCollection_t (lcio::LCCollection *graphs)
Create a histogram collection from lcio collection.
GraphCollection_t (const GraphCollection_t &a)
copy constructor.
void deleteCollection ()
delete the histogram collection and the index array This method exists instead of a destrctor to prevent copying the arrays (FIXME)
void deleteSharedStorage ()
lcio::LCCollection * collection ()
get the unique group id
const lcio::LCCollection * collection () const
get the collection of graphs (read only).
unsigned int n () const
Get the number of graphs.
bool is2D () const
Check whether the graph collection contains more than one graph group.
unsigned int nTypes () const
unsigned int nMajor () const
Get the number of major indices.
unsigned int nMinor (unsigned int major_index) const
Get the number of elements for the collection slice addressed by the given major index.
GraphCollection_t (const std::string &collection_name, unsigned int n_graphs, const EVENT::StringVec &type_names, unsigned int n_expected_values, const EVENT::StringVec &opt_major_names, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
Create a collection of graphs.
GraphCollection_t (const std::string &collection_name, const std::vector< int > &n_graphs, const std::vector< std::string > &type_names, unsigned int n_expected_values, const std::vector< std::string > &opt_major_names, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
Create a 2D collection of graphs.
std::string & getMajorName (unsigned int major_index, unsigned int type_index) const
Get the name of the graph group addressed by the major index.
std::string & getName (unsigned int major_index, unsigned int minor_index, unsigned int type_index) const
Get the full name of the graph which is part of a specfic graph group addressed by the major index.
std::string & getName (unsigned int index, unsigned int type_index) const
Get the full name of the graph addressed by the index.
unsigned int appendXValue (double x_value)
Set the common x value of all the graphs of the graph collection.
void setYValue (unsigned int major_index, unsigned int minor_index, unsigned int type_index, unsigned int value_index, float a_value)
Set the y-value of the adddressed graph.
void setYValue (unsigned int index, unsigned int type_index, unsigned int value_index, float a_value)
Set the y-value of the adddressed graph.
float getYValue (unsigned int index, unsigned int type_index, unsigned int value_index) const
Get the y-value of the adddressed graph.
float getYValue (unsigned int major_index, unsigned int minor_index, unsigned int type_index, unsigned int value_index) const
Get the y-value of the adddressed graph.
double getXValue (unsigned int index, unsigned int value_index) const
Get the x-value of the adddressed graph.
const std::string & getName (unsigned int major_index) const
Get the name of the specified element of the graph collection.
const std::string & getTypeName (unsigned int type_index) const
Get the addressed type name.
Static Public Attributes
static const std::string __colorParameterName
static const std::string __widthParameterName
static const std::string __styleParameterName
static const std::string __majorColorParameterName
Protected Member Functions
unsigned int appendFloatValue (unsigned int full_index, float a_value)
append a new value to the addressed graph,
unsigned int appendValue (unsigned int full_index, double a_value)
append a new value to the addressed graph,
void setFloatValue (unsigned int full_index, unsigned int value_index, float a_value)
set a value of the addressed graph,
void setValue (unsigned int full_index, unsigned int value_index, float a_value)
set a value of the addressed graph,
double getValue (unsigned int full_index, unsigned int value_index) const
set a value of the addressed graph,
double getFloatValue (unsigned int full_index, unsigned int value_index) const
set a value of the addressed graph,
void addToFloatValue (unsigned int full_index, unsigned int value_index, float a_value)
Add the given value to a certain value of the addressed graph.
unsigned int getIndex (unsigned int major_index, unsigned int minor_index, unsigned int type_index) const
Calculate the full graph index in case of 2d graph groups.
unsigned int getIndex (unsigned int index, unsigned int type_index) const
Calculate the full graph index in case of a flat graph group.
EVENT::LCGenericObject * getXArray ()
EVENT::LCGenericObject * getArray (unsigned int full_index)
Static Protected Attributes
static const std::string __graphNameParameterName
Private Member Functions
void copyNames () const
Assignment operation which deletes the old collections.
Private Attributes
lcio::LCCollection * _graphCol
the histogram collection
unsigned int _nGraphs
the number of graphs
lcio::IntVec * _majorIndex
optional list of offset to form a two dimensional array out of the list.
unsigned int _nTypes
number of types.
lcio::StringVec _typeNameList
A vector which contains one name for all graphs of the collection or a name for each element (this list is only filled if a names are accessed).
lcio::StringVec _nameList
A vector which contains one name for all graphs of the collection or a name for each element.
Static Private Attributes
static const std::string __majorIndexParameterName
static const std::string __typeNameParameterName
static const std::string __defaultGraphName
Friends
class HistMgr
Detailed Description
Light wrapper around a LCCollection to facilitate the handling of collections of graphs. All the graphs of the collection share the same x values. The wrapper supports 1 or 2 dimensional collections of graphs. Where each graph collection is composed of several graph groups and each graph group contains a fixed set of graphs of different types. More correctly the collection has a 2 dimensional or 3d diemensional structure.
Definition at line 27 of file GraphCollection_t.hh.
Constructor & Destructor Documentation
histmgr::GraphCollection_t::GraphCollection_t (lcio::LCCollection * graphs, lcio::IntVec * indices)
Parameters
graphs the linearised one or two dimensional collection of graphs
indices optional list of indicies used to give two dimensional access to the histogram list. for each possible index of the first dimension is needed which contains the offset in the list. The second index is added to this offset.
Definition at line 124 of file GraphCollection_t.cc.
References _graphCol, _majorIndex, _nGraphs, and _nTypes.
histmgr::GraphCollection_t::GraphCollection_t (lcio::LCCollection * graphs)
Create a histogram collection from lcio collection.
Parameters
graphs the linearised one or two dimensional collection of graphs (two dimensional collections have the collection parameter `major`). The method does not verify whether the lcio collection really is a histogram collection. However, if the collection has the parameter `major` it creates an index vector (costly operation) assuming that it is a 2d array instead of a 1d array(i.e. collection). The unique group id remains undedfined since it is not stored in the lcio collection.
Definition at line 151 of file GraphCollection_t.cc.
References _graphCol, _majorIndex, _nGraphs, and _nTypes.
histmgr::GraphCollection_t::GraphCollection_t (const std::string & collection_name, unsigned int n_graphs, const EVENT::StringVec & type_names, unsigned int n_expected_values, const EVENT::StringVec & opt_major_names, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error)
Create a collection of graphs. Where for each element the given number of graph types is created.
Definition at line 17 of file GraphCollection_t.cc.
histmgr::GraphCollection_t::GraphCollection_t (const std::string & collection_name, const std::vector< int > & n_graphs, const std::vector< std::string > & type_names, unsigned int n_expected_values, const std::vector< std::string > & opt_major_names, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error)
Create a 2D collection of graphs. Where for each element of the 2 dimensional collection, the not only a single but for each graph type one..
Definition at line 63 of file GraphCollection_t.cc.
Member Function Documentation
unsigned int histmgr::GraphCollection_t::appendXValue (double x_value) [inline]
Set the common x value of all the graphs of the graph collection.
Returns
the index of the new value which can be used to set the corresponding values in all the other graphs.
Definition at line 204 of file GraphCollection_t.hh.
References appendValue().
Referenced by CALICE::AverageHistoryGraphs::processEvent().
const lcio::LCCollection* histmgr::GraphCollection_t::collection () const [inline]
get the collection of graphs (read only). The index array needed for the two dimensional acces is added as a parameter named `major`.
Definition at line 118 of file GraphCollection_t.hh.
References _graphCol.
lcio::LCCollection* histmgr::GraphCollection_t::collection () [inline]
get the unique group id get the collection of graphs. The index array needed for the two dimensional acces is added as a parameter named `major`.
Definition at line 113 of file GraphCollection_t.hh.
References _graphCol.
void histmgr::GraphCollection_t::copyNames () const [inline, private]
Assignment operation which deletes the old collections. Copy the names from the collection to an accessible vector. The vector of histogram names is attached as a parameter to the LCCollection.
Definition at line 444 of file GraphCollection_t.hh.
References _graphCol, _nameList, and nMajor().
Referenced by getName().
std::string& histmgr::GraphCollection_t::getMajorName (unsigned int major_index, unsigned int type_index) const
Get the name of the graph group addressed by the major index. The result is undefined if the graph group is not 2D.
const std::string& histmgr::GraphCollection_t::getName (unsigned int major_index) const [inline]
Get the name of the specified element of the graph collection.
Parameters
major_index the index of the histogram element or in case of an 2D histogram array the major index.
Returns
a reference to the name. The index must be valid.
Definition at line 381 of file GraphCollection_t.hh.
References _nameList, and copyNames().
std::string& histmgr::GraphCollection_t::getName (unsigned int index, unsigned int type_index) const
Get the full name of the graph addressed by the index.
Parameters
index the index of the graph in the graph group.
type_index the index of the graph type.
Returns
the full graph name. The result is undefined if the graph group is not 2D.
std::string& histmgr::GraphCollection_t::getName (unsigned int major_index, unsigned int minor_index, unsigned int type_index) const
Get the full name of the graph which is part of a specfic graph group addressed by the major index.
Parameters
major_index the index of the sub graph group.
minor_index the index of the graph in the graph group.
type_index the index of the graph type.
Returns
the full graph name. The result is undefined if the graph group is not 2D.
const std::string& histmgr::GraphCollection_t::getTypeName (unsigned int type_index) const [inline]
Get the addressed type name.
Parameters
type_index the index of the type.
Returns
a reference to the type name. The index must be valid.
Definition at line 397 of file GraphCollection_t.hh.
References _graphCol, and _typeNameList.
bool histmgr::GraphCollection_t::is2D () const [inline]
Check whether the graph collection contains more than one graph group.
Returns
true if the graph collection contains more than one graph group which can be addressed by a major index.
Definition at line 130 of file GraphCollection_t.hh.
References _majorIndex.
Referenced by getIndex().
unsigned int histmgr::GraphCollection_t::n () const [inline]
Get the number of graphs. This value does not take into account that for each graph several types are created.
Definition at line 123 of file GraphCollection_t.hh.
References _nGraphs.
Referenced by histmgr::HistMgr::fillHistogramCollectionList().
unsigned int histmgr::GraphCollection_t::nMajor () const [inline]
Get the number of major indices. The collection is sliced in nMajor slices each having nMinor(major_index) elements.
Definition at line 144 of file GraphCollection_t.hh.
References _majorIndex.
Referenced by copyNames().
unsigned int histmgr::GraphCollection_t::nMinor (unsigned int major_index) const [inline]
Get the number of elements for the collection slice addressed by the given major index. The major index must be valid.
Definition at line 154 of file GraphCollection_t.hh.
References _majorIndex.
Field Documentation
lcio::IntVec* histmgr::GraphCollection_t::_majorIndex [private]
optional list of offset to form a two dimensional array out of the list.
Definition at line 459 of file GraphCollection_t.hh.
Referenced by deleteCollection(), getIndex(), GraphCollection_t(), is2D(), nMajor(), and nMinor().
lcio::StringVec histmgr::GraphCollection_t::_nameList [mutable, private]
A vector which contains one name for all graphs of the collection or a name for each element.
Definition at line 466 of file GraphCollection_t.hh.
Referenced by copyNames(), and getName().
unsigned int histmgr::GraphCollection_t::_nTypes [private]
number of types.
Definition at line 461 of file GraphCollection_t.hh.
Referenced by GraphCollection_t().
lcio::StringVec histmgr::GraphCollection_t::_typeNameList [mutable, private]
A vector which contains one name for all graphs of the collection or a name for each element (this list is only filled if a names are accessed).
Definition at line 463 of file GraphCollection_t.hh.
Referenced by getTypeName().
The documentation for this class was generated from the following files:
GraphCollection_t.hh
GraphCollection_t.cc