Ahc2MipTrackFinder Class Reference
Public Member Functions
virtual Processor * newProcessor ()
Ahc2MipTrackFinder ()
Default constructor.
~Ahc2MipTrackFinder ()
Default destructor.
virtual void init ()
Marlin init() function.
virtual void processRunHeader (LCEvent *evt)
Marlin processRunHeader() function.
virtual void processEvent (LCEvent *evt)
Marlin processEvent() function.
virtual void check (LCEvent *evt)
Marlin check() function.
virtual void end ()
Marlin end() function.
void printParameters ()
int Fill2DMap (TowerHitVectorHCAL &TowerMap, int I, int J, int K, float x, float y, float z, Float_t ahc_hitEnergy, Float_t ahc_hitTime, Int_t ahc_hitType, int CellID0)
Fill HCAL Towers.
int Fill2DMap (TowerHitVectorECAL &TowerMap, int I, int J, int K, float x, float y, float z, Float_t emc_hitEnergy, Float_t emc_hitTime, Int_t emc_hitType, int CellID0)
Fill ECAL Towers.
int selectTowerNHits (TowerHitVectorHCAL &towers, unsigned int MinNHits)
Select HCAL Towers with number of hits over MinNHits.
bool Check_T0 (int Ihit, int Jhit, int Khit)
Reject T0 hits.
bool Check_Cherenkow (int Ihit, int Jhit, int Khit)
Reject Cherenkow hits.
bool CheckOverlap (pair< float, float > Coordinates_ECAL, pair< float, float > Coordinates_HCAL)
Check ECAL Strip overlap with HCAL Tower.
int IncrementOverlap (vector< EcalSingleHit > &ECALHits)
Increment Overlap parameter of a ECAL Hit.
Protected Attributes
TowerHitVectorHCAL _towerHCALHits
HCAL Tower.
TowerHitVectorECAL _towerECALHits
ECAL Tower.
std::string _ahcinputColName
HCAL input Collection.
std::string _emcinputColName
ECAL input Collection.
std::string _ahcHitOutputColName
HCAL output Collection.
std::string _emcHitOutputColName
ECAL output Collection.
std::string _encodingECAL
std::string _encodingHCAL
bool _keepT0Cherenkow
int _cutNTowerHits
keep T0 and Cherenkow in output collection
int _cutNLayerHits
Cut on Number of hits in a Layer.
int _nMaxHits
Maximum number of hits per event.
int _nMinHits
Minimum number of hits per event.
StringVec _T0Vector
Vector containing T0s.
StringVec _CherenkowVector
Vector containing Cherenkows.
vector< int > _mapT0s
map for T0s
vector< int > _mapCherenkows
map for Cherenkows
vector< int > HitPerlayer
Number of hits per layer before tracking to reject late pion showers.
int nHCALtracks
int _nEvt
int _nRun
Detailed Description
Definition at line 27 of file Ahc2MipTrackFinder.hh.
Member Function Documentation
bool Ahc2MipTrackFinder::Check_Cherenkow (int Ihit, int Jhit, int Khit)
Reject Cherenkow hits.
Parameters
Ihit - I coordinate of the hit
Jhit - J coordinate of the hit
Khit - K coordinate of the hit
ahc_hitEnergy - Energy of the hit
Returns
- true if Cherenkow Hit otherwise false
Definition at line 661 of file Ahc2MipTrackFinder.cc.
References _mapCherenkows.
Referenced by processEvent().
bool Ahc2MipTrackFinder::Check_T0 (int Ihit, int Jhit, int Khit)
Reject T0 hits.
Parameters
Ihit - I coordinate of the hit
Jhit - J coordinate of the hit
Khit - K coordinate of the hit
ahc_hitEnergy - Energy of the hit
Returns
- true if T0 Hit otherwise false
Definition at line 639 of file Ahc2MipTrackFinder.cc.
References _mapT0s.
Referenced by processEvent().
bool Ahc2MipTrackFinder::CheckOverlap (pair< float, float > Coordinates_ECAL, pair< float, float > Coordinates_HCAL)
Check ECAL Strip overlap with HCAL Tower.
Parameters
Coordinates_ECAL - x,y coordinates of the ECAL hit
Coordinates_HCAL - x,y coordinates of the HCAL hit
Returns
- true if overlap otherwise false
Definition at line 620 of file Ahc2MipTrackFinder.cc.
Referenced by processEvent().
int Ahc2MipTrackFinder::Fill2DMap (TowerHitVectorECAL & TowerMap, int I, int J, int K, float x, float y, float z, Float_t emc_hitEnergy, Float_t emc_hitTime, Int_t emc_hitType, int CellID0)
Fill ECAL Towers.
Parameters
TowerMap - ECAL TowerMap
I - I coordinate of the hit
J - J coordinate of the hit
K - K coordinate of the hit
x - x coordinate of the hit
y - y coordinate of the hit
z - z coordinate of the hit
emc_hitEnergy - Energy of the hit
emc_hitTime - Time of the hit
emc_hitType - Type of the hit
CellID0 - CellID of the hit
Definition at line 536 of file Ahc2MipTrackFinder.cc.
int Ahc2MipTrackFinder::Fill2DMap (TowerHitVectorHCAL & TowerMap, int I, int J, int K, float x, float y, float z, Float_t ahc_hitEnergy, Float_t ahc_hitTime, Int_t ahc_hitType, int CellID0)
Fill HCAL Towers.
Parameters
TowerMap - HCAL TowerMap
I - I coordinate of the hit
J - J coordinate of the hit
K - K coordinate of the hit
x - x coordinate of the hit
y - y coordinate of the hit
z - z coordinate of the hit
ahc_hitEnergy - Energy of the hit
ahc_hitTime - Time of the hit
ahc_hitType - Type of the hit
CellID0 - CellID of the hit
Definition at line 509 of file Ahc2MipTrackFinder.cc.
Referenced by processEvent().
int Ahc2MipTrackFinder::IncrementOverlap (vector< EcalSingleHit > & ECALHits)
Increment Overlap parameter of a ECAL Hit.
Parameters
ECALHits - vector containing ECAL hits
Definition at line 603 of file Ahc2MipTrackFinder.cc.
Referenced by processEvent().
int Ahc2MipTrackFinder::selectTowerNHits (TowerHitVectorHCAL & towers, unsigned int MinNHits)
Select HCAL Towers with number of hits over MinNHits.
Parameters
towers - HCAL Towers
MinNHits - Minimum on Number of hits in a Tower
Returns
- Number of Towers left
Definition at line 565 of file Ahc2MipTrackFinder.cc.
Referenced by processEvent().
Field Documentation
int Ahc2MipTrackFinder::_cutNTowerHits [protected]
keep T0 and Cherenkow in output collection Cut on Number of hits in a Tower
Definition at line 144 of file Ahc2MipTrackFinder.hh.
Referenced by Ahc2MipTrackFinder(), and processEvent().
The documentation for this class was generated from the following files:
Ahc2MipTrackFinder.hh
Ahc2MipTrackFinder.cc