RunComparator Class Reference
A class to facilitate the comparison of two runs.
#include <RunComparator.h>
Public Member Functions
RunComparator (SpectrumPropertiesRunInfo const &firstRunInfo, SpectrumPropertiesRunInfo const &secondRunInfo)
Initialise the class by giving the two SpectrumPropertiesRunInfo objects of the two runs.
~RunComparator ()
Destructor to free the dynamically allocated histograms.
void prepareGraph (std::pair< double, double >(*calculatorFunction)(TChannelSpectrumProperties const &, TChannelSpectrumProperties const &))
Convenience function which fills the graph and the histograms for all channels.
void prepareGraph (std::pair< double, double >(*calculatorFunction)(TChannelSpectrumProperties const &, TChannelSpectrumProperties const &), std::vector< SpectrumPropertiesRunInfo::ChannelID > const &channelList)
This function fills the graph and the histograms with the values calculates by the calculatorFunction (first value on the x axis, second on the y axis).
TGraph * getGraph ()
Gets a pointer to the graph object.
TH1D * getXAxisHisto ()
Gets a pointer to the x axis histogram (histogram of the first variable of the calculator function).
TH1D * getYAxisHisto ()
Gets a pointer to the y axis histogram (histogram of the first variable of the calculator function).
std::map< SpectrumPropertiesRunInfo::ChannelID, std::pair< double, double > > const & getChannelValuesMap () const
Returns a map with all channels and the correlated x and y values.
std::set< SpectrumPropertiesRunInfo::ChannelID > getChannelsWithCut (Double_t yMin=-DBL_MAX, Double_t yMax=DBL_MAX, Double_t xMin=-DBL_MAX, Double_t xMax=DBL_MAX) const
Returns a set with the channels and the correlated x and y values and cuts on x and y.
Static Public Member Functions
static std::pair< double, double > calculateChannelAndPedestalCorrectedMean (TChannelSpectrumProperties const &spectrumPropertiesPMNoise, TChannelSpectrumProperties const &spectrumPropertiesOther)
This function returns the global channel number for the x axis (first value) and channelSpectrumPropertiesOther._mean - channelSpectrumPropertiesPMNoise._mean for the y axis (second value).
Protected Attributes
SpectrumPropertiesRunInfo const & _firstRunInfo
pointer to the first SpectrumPropertiesRunInfo
SpectrumPropertiesRunInfo const & _secondRunInfo
pointer to the first SpectrumPropertiesRunInfo
TGraph * _theGraph
The internal instance of the graph.
TH1D * _xAxisHisto
The internal instance of the x axis histogram.
TH1D * _yAxisHisto
The internal instance of the y axis histogram.
std::map< SpectrumPropertiesRunInfo::ChannelID, std::pair< double, double > > _channelValuesMap
A map to correlate channelID and the calculated values.
Detailed Description
A class to facilitate the comparison of two runs. It creates a TGraph with two numbers calculated from the TChannelSpectrumPropertiess for the two runs for each channel, and the `projections` on the axes, i. e. a 1D histogram of each of the values.
The numbers calculated are defined by a function which takes two TChannelSpectrumPropertiess as input and returns a pair of doubles. The most important functions are defined within this class, but the user can also define his own functions, which provides full flexibility.
Although the definition of function pointers look complicated and lengthy, the usage is simple:
  // a PMNoise run
  SpectrumPropertiesRunInfo priPMNoise(123, "myAHCConfig.cfg");
  // a PMLedVcalib run
  SpectrumPropertiesRunInfo priPMLED(124, "myAHCConfig.cfg");
  RunComparator myRunComparator(priPMNoise, priPMLED);
  // create the graph with the channel number on the x axis and the
  // pedestal corrected mean on the y axis. Just pass the address of the
  // function (thus the &).
  myRunComparator.prepareGraph(&calculateChannelAndPedestalCorrectedMean);
  myRunComparator.getGraph()->Draw("AP"); //draw the graph
  myRunComparator.getXAxisHisto()->Draw(); //draw the histo for the x axis values
      
Todo Make the return values of the clones graphs and histos auto pointers. Damn, CINT does not support auto pointers :-(
Definition at line 51 of file RunComparator.h.
Constructor & Destructor Documentation
RunComparator::RunComparator (SpectrumPropertiesRunInfo const & firstRunInfo, SpectrumPropertiesRunInfo const & secondRunInfo)
Initialise the class by giving the two SpectrumPropertiesRunInfo objects of the two runs.
Definition at line 6 of file RunComparator.cxx.
RunComparator::~RunComparator ()
Destructor to free the dynamically allocated histograms.
Definition at line 12 of file RunComparator.cxx.
References _theGraph, _xAxisHisto, and _yAxisHisto.
Member Function Documentation
std::pair< double, double > RunComparator::calculateChannelAndPedestalCorrectedMean (TChannelSpectrumProperties const & spectrumPropertiesPMNoise, TChannelSpectrumProperties const & spectrumPropertiesOther) [static]
This function returns the global channel number for the x axis (first value) and channelSpectrumPropertiesOther._mean - channelSpectrumPropertiesPMNoise._mean for the y axis (second value). This usually only makes sense if the first argument (spectrumPropertiesPMNoise) is a noise run, where the mean value is the pedestal.
Definition at line 86 of file RunComparator.cxx.
References TChannelSpectrumProperties::_channel, TChannelSpectrumProperties::_chip, TChannelSpectrumProperties::_mean, TChannelSpectrumProperties::_module, and SpectrumPropertiesRunInfo::getGlobalChannelNumber().
Referenced by main().
std::set< SpectrumPropertiesRunInfo::ChannelID > RunComparator::getChannelsWithCut (Double_t yMin = -DBL_MAX, Double_t yMax = DBL_MAX, Double_t xMin = -DBL_MAX, Double_t xMax = DBL_MAX) const
Returns a set with the channels and the correlated x and y values and cuts on x and y. Note the ordering of the cut parameter: The cuts on y come first for convenience since there will be cuts on y more often than on x, so one can just leave the default values which do not cut at all. n.b.: The return value is a set because it has a find() which allows to check whether a channel is in the set.
Definition at line 144 of file RunComparator.cxx.
References _channelValuesMap.
std::map< SpectrumPropertiesRunInfo::ChannelID, std::pair< double, double > > const & RunComparator::getChannelValuesMap () const
Returns a map with all channels and the correlated x and y values.
Definition at line 138 of file RunComparator.cxx.
References _channelValuesMap.
TGraph * RunComparator::getGraph ()
Gets a pointer to the graph object. The first variable of the return value of the calculatorFunction is in the x axis, the second one on the y axis.
Attention
This pointer is only valid until the next call of prepareGraph(). If you want to preserve the graph make a clone of it:
  myRunComparator.prepareGraph(&functionForMyFirstGraph);
  // clone the graph to preserve it
  TGraph *myFirstGraph = myRunComparator.getGraph()->Clone();
  // Now create the second graph. The first graph inside the RunComparator is del
      eted.
  myRunComparator.prepareGraph(&functionForMySecondGraph);
  // If we need no further graphs we don't need to clone this one:
  TGraph *mySecondGraph = myRunComparator.getGraph();
Definition at line 101 of file RunComparator.cxx.
References _theGraph.
Referenced by main().
TH1D * RunComparator::getXAxisHisto ()
Gets a pointer to the x axis histogram (histogram of the first variable of the calculator function).
Attention
This pointer is only valid until the next call of prepareGraph(). If you want to preserve the graph make a clone of it.
Definition at line 113 of file RunComparator.cxx.
References _xAxisHisto.
Referenced by main().
TH1D * RunComparator::getYAxisHisto ()
Gets a pointer to the y axis histogram (histogram of the first variable of the calculator function).
Attention
This pointer is only valid until the next call of prepareGraph() (or the RunComparator is deleted). If you want to preserve the graph make a clone of it.
Definition at line 125 of file RunComparator.cxx.
References _yAxisHisto.
Referenced by main().
void RunComparator::prepareGraph (std::pair< double, double >(*)(TChannelSpectrumProperties const &, TChannelSpectrumProperties const &) calculatorFunction, std::vector< SpectrumPropertiesRunInfo::ChannelID > const & channelList)
This function fills the graph and the histograms with the values calculates by the calculatorFunction (first value on the x axis, second on the y axis).
Parameters
calculatorFunction The first parameter is a pointer to a function which returns a pair of doubles and takes two const references to TChannelSpectrumProperties as argument. This function calculates the values for the x and y axis from the channel spectrumPropertiess.
channelList A const reference to a vector of channel IDs. These are the channels for which the graph and the histograms are filled.
Definition at line 29 of file RunComparator.cxx.
References _channelValuesMap, _firstRunInfo, _secondRunInfo, _theGraph, _xAxisHisto, _yAxisHisto, SpectrumPropertiesRunInfo::getChannelSpectrumProperties(), and SpectrumPropertiesRunInfo::getRunNumber().
void RunComparator::prepareGraph (std::pair< double, double >(*)(TChannelSpectrumProperties const &, TChannelSpectrumProperties const &) calculatorFunction)
Convenience function which fills the graph and the histograms for all channels.
Definition at line 19 of file RunComparator.cxx.
References _firstRunInfo, and SpectrumPropertiesRunInfo::getChannelsWithRMSCut().
Referenced by main().
Field Documentation
std::map< SpectrumPropertiesRunInfo::ChannelID, std::pair<double, double> > RunComparator::_channelValuesMap [protected]
A map to correlate channelID and the calculated values.
Definition at line 154 of file RunComparator.h.
Referenced by getChannelsWithCut(), getChannelValuesMap(), and prepareGraph().
SpectrumPropertiesRunInfo const& RunComparator::_firstRunInfo [protected]
pointer to the first SpectrumPropertiesRunInfo
Definition at line 146 of file RunComparator.h.
Referenced by prepareGraph().
SpectrumPropertiesRunInfo const& RunComparator::_secondRunInfo [protected]
pointer to the first SpectrumPropertiesRunInfo
Definition at line 147 of file RunComparator.h.
Referenced by prepareGraph().
TGraph* RunComparator::_theGraph [protected]
The internal instance of the graph.
Definition at line 149 of file RunComparator.h.
Referenced by getGraph(), prepareGraph(), and ~RunComparator().
TH1D* RunComparator::_xAxisHisto [protected]
The internal instance of the x axis histogram.
Definition at line 150 of file RunComparator.h.
Referenced by getXAxisHisto(), prepareGraph(), and ~RunComparator().
TH1D* RunComparator::_yAxisHisto [protected]
The internal instance of the y axis histogram.
Definition at line 151 of file RunComparator.h.
Referenced by getYAxisHisto(), prepareGraph(), and ~RunComparator().
The documentation for this class was generated from the following files:
RunComparator.h
RunComparator.cxx