SpectrumPropertiesRunInfo Class Reference
The SpectrumPropertiesRunInfo is a utility class to access the spectrum properties for all channels of one specific run.
#include <SpectrumPropertiesRunInfo.h>
Data Structures
class ChannelID
A channel identifier helper class. The key in the map.
Public Member Functions
SpectrumPropertiesRunInfo (Int_t runNumber, std::string AHCConfigFileName=``, bool apply5RMSCut=false, std::string runFileName=``, unsigned int moduleTypes=ModuleType::AHC|ModuleType::AHC8)
This constructor opens a root file with histograms containing the spectrum per channel, named 'runNumber.root', and instantiates an SimpleMapper from the AHCConfigFileName.
SpectrumPropertiesRunInfo (Int_t runNumber, TTree *spectrumPropertiesTree)
A constructor to initialise the class from a previously calculated spectrum properties tree.
~SpectrumPropertiesRunInfo ()
The destructor to clean up the allocated objects.
TTree * getSpectrumPropertiesTree ()
Get a pointer to the spectrum properties tree.
void print (std::string fileName=``) const
Print the spectrum properties tree.
std::vector< SpectrumPropertiesRunInfo::ChannelID > getNoisyChannels (Double_t noisyCut) const
Returns a vector with all ChannelIDs of channels which have an rms larger or equal to noisyCut.
std::vector< SpectrumPropertiesRunInfo::ChannelID > getChannelsWithRMSCut (Double_t lowerCut=0, Double_t upperCut=DBL_MAX) const
Returns all channels with an RMS in the cut range (rms >= lowerCut) and (rms <=upperCut).
std::vector< SpectrumPropertiesRunInfo::ChannelID > getChannelsWithMeanCut (Double_t lowerCut=-DBL_MAX, Double_t upperCut=DBL_MAX) const
Returns all channels with a mean value in the cut range (mean >= lowerCut) and (mean <=upperCut).
void printChannels (std::vector< SpectrumPropertiesRunInfo::ChannelID > const &listOfChannels)
Convenience function to print a list of channels to the console.
TH1D * getChannelHisto (SpectrumPropertiesRunInfo::ChannelID channelID)
Get the ADC spectrum histogram of a specific channel.
TH1D * getChannelHisto (Int_t module, Int_t chip, Int_t channel)
Convenience function to call getChannelHisto(ChannelID) from the three identifying integers.
TH1D * getChannelHisto (Int_t globalChannelNumber)
Convenience function to call getChannelHisto(ChannelID) from the global channel number.
TChannelSpectrumProperties getChannelSpectrumProperties (ChannelID const &channelID) const
Get the channel's spectrum properties knowing the channel ID.
TChannelSpectrumProperties getChannelSpectrumProperties (Int_t globalChannelNumber) const
Get the channel's spectrum properties knowing the global channel number.
TChannelSpectrumProperties const *const * getSpectrumPropertiesTreeObject ()
Get the object in memory which is in the branch address of the channel properties tree.
THStack * drawGetDeadChannelsPlot (Double_t deadCut=20.5, Double_t xAxisMax=70.)
Returns a THStack containing two histograms: One with the RMS spectrum and the second only with the part being cut as dead (in red).
Int_t getRunNumber () const
Returns the run number.
Static Public Member Functions
static Int_t getGlobalChannelNumber (ChannelID const &channelID)
Get the global channel number $( moduleID \cdot nChipsPerModule + chipID ) \cdot nChannelsPerChip + channelNumber $ from the channelID.
static ChannelID getChannelID (Int_t globalChannelNumber)
Get a ChannelID class from the global channel number.
static void setNChipsPerModule (Int_t nChipsPerModule)
Set the number of chips per module.
static void setNChannelsPerChip (Int_t nChannelsPerChip)
Set the number of channels per chip.
static Int_t getNChannelsPerChip ()
Get the number of channels per chip.
static Int_t getNChipsPerModule ()
Get the number of chips per module.
Protected Member Functions
bool openRunFile (std::string runFileName)
Protected Attributes
Int_t _runNumber
TFile * _runFile
SimpleMapper * _simpleMapper
TTree * _spectrumPropertiesTree
TChannelSpectrumProperties * _channelSpectrumProperties
std::map< ChannelID, std::string > _histogramTitleMap
A map to store the ChannelID and the associated histogram titles.
std::map< ChannelID, TChannelSpectrumProperties > _channelSpectrumPropertiesMap
A map for random access to the TChannelSpectrumPropertiess.
bool createdTree
unsigned int _moduleTypeMask
The mask for the module types to accept.
Static Protected Attributes
static Int_t _nChannelsPerChip = 18
static Int_t _nChipsPerModule = 12
Detailed Description
The SpectrumPropertiesRunInfo is a utility class to access the spectrum properties for all channels of one specific run. It uses a global channel number which is calculated as $( moduleID \cdot nChipsPerModule + chipID ) \cdot nChannelsPerChip + channelNumber $, for instance for the channel number on the x-axis of the plots. You can used the getChannelID(int globalChannelNumber) to retrieve the module, chip, and channel number. The default values for nChipsPerModule and nChannelsPerChip are:
nChipsPerModule = 12
nChannelsPerChip = 18
You can change this during runtime. You should do it immediately after using the conctructor to avoid inconsistencies. In order not to overcomplicate the constructor it is not in there. These values can only change with new readout hardware.
The 5*RMS cut
In the spectrum there might be very few outliers which are extremely far away. To cut them away a `5RMSCut` can be turned on in the conctructor. Here the RMS of the histogram is taken and the histogam is limited to $mean \pm 5\cdot rms$. Afterwards the new rms is calculated. This procedure is repeated iteratively until it converges (maximal 10 times). Usually the convergense needs less than 5 iterations.
Definition at line 42 of file SpectrumPropertiesRunInfo.h.
Constructor & Destructor Documentation
SpectrumPropertiesRunInfo::SpectrumPropertiesRunInfo (Int_t runNumber, std::string AHCConfigFileName = ``, bool apply5RMSCut = false, std::string runFileName = ``, unsigned int moduleTypes = ModuleType::AHC | ModuleType::AHC8)
This constructor opens a root file with histograms containing the spectrum per channel, named 'runNumber.root', and instantiates an SimpleMapper from the AHCConfigFileName. From this it fills the spectrumPropertiesTree. If no file name for the AHCConfig is given, the mapping has to be one in ahcBinHst.
The 5RMSCut is off by default to avoid cutting information. But usually it's a good idea to turn it on.
The runFileName for the file with the input histograms is optional. If not given or empty it tries to open 'runNumber.root'.
You can select the module type be providing a word with the ModuleType bits. Default is the calorimeter (HCAL and HCAL8).
Definition at line 23 of file SpectrumPropertiesRunInfo.cxx.
References _channelSpectrumProperties, _channelSpectrumPropertiesMap, _histogramTitleMap, _moduleTypeMask, _runFile, _runNumber, _simpleMapper, _spectrumPropertiesTree, SimpleMapper::getModuleLayerID(), SimpleMapper::getModuleType(), SimpleMapper::isAHC8(), MAX_ITERATIONS, openRunFile(), and TChannelSpectrumProperties::Set().
SpectrumPropertiesRunInfo::SpectrumPropertiesRunInfo (Int_t runNumber, TTree * spectrumPropertiesTree)
A constructor to initialise the class from a previously calculated spectrum properties tree. This is much faster and less memory consuming than creating it from the input file with the per-channel histograms.
Definition at line 233 of file SpectrumPropertiesRunInfo.cxx.
References TChannelSpectrumProperties::_channel, _channelSpectrumProperties, _channelSpectrumPropertiesMap, TChannelSpectrumProperties::_chip, TChannelSpectrumProperties::_module, _runFile, and _spectrumPropertiesTree.
SpectrumPropertiesRunInfo::~SpectrumPropertiesRunInfo ()
The destructor to clean up the allocated objects.
Definition at line 217 of file SpectrumPropertiesRunInfo.cxx.
References _runFile, _simpleMapper, _spectrumPropertiesTree, and createdTree.
Member Function Documentation
THStack * SpectrumPropertiesRunInfo::drawGetDeadChannelsPlot (Double_t deadCut = 20.5, Double_t xAxisMax = 70.)
Returns a THStack containing two histograms: One with the RMS spectrum and the second only with the part being cut as dead (in red). For convenience they are put into a THStack to draw them using hStack->Draw(`nostack`). Please note that drawing the histograms stacked (i. e. without the nostack option) does not make sense.
The Draw command is executed before the THStack is returned. It just draws to the currently active pad. The stack with the histograms is returned to facilitate modifications.
The function hands over the ownership of the THStack and of the histograms. The histograms are not owned by the stack. Delete the histograms and the stack if you don't need them any more to avoid memory leaks.
Definition at line 478 of file SpectrumPropertiesRunInfo.cxx.
References _channelSpectrumPropertiesMap, TChannelSpectrumProperties::_rms, and _runNumber.
TH1D * SpectrumPropertiesRunInfo::getChannelHisto (Int_t globalChannelNumber)
Convenience function to call getChannelHisto(ChannelID) from the global channel number.
Definition at line 410 of file SpectrumPropertiesRunInfo.cxx.
References getChannelHisto(), and getChannelID().
TH1D * SpectrumPropertiesRunInfo::getChannelHisto (Int_t module, Int_t chip, Int_t channel)
Convenience function to call getChannelHisto(ChannelID) from the three identifying integers.
Definition at line 405 of file SpectrumPropertiesRunInfo.cxx.
References getChannelHisto().
TH1D * SpectrumPropertiesRunInfo::getChannelHisto (SpectrumPropertiesRunInfo::ChannelID channelID)
Get the ADC spectrum histogram of a specific channel. The histogram is loaded from the input file. Keep in mind that the histogram stays in memory if you don't delete it. It is safe to delete it after usage. The SpectrumPropertiesRunInfo class does have the ownership over the histogram, only root does the usual bookkeeping.
When using the constructor which takes the tree as input the file name 'runNumber.root' is assumed as source for the histograms. If this file could not be opened the return value is 0.
Definition at line 383 of file SpectrumPropertiesRunInfo.cxx.
References _histogramTitleMap, and _runFile.
Referenced by getChannelHisto().
SpectrumPropertiesRunInfo::ChannelID SpectrumPropertiesRunInfo::getChannelID (Int_t globalChannelNumber) [static]
Get a ChannelID class from the global channel number.
Definition at line 426 of file SpectrumPropertiesRunInfo.cxx.
References SpectrumPropertiesRunInfo::ChannelID::_channel, SpectrumPropertiesRunInfo::ChannelID::_chip, SpectrumPropertiesRunInfo::ChannelID::_module, _nChannelsPerChip, and _nChipsPerModule.
Referenced by getChannelHisto(), getChannelSpectrumProperties(), and printChannelStatusMap().
TChannelSpectrumProperties SpectrumPropertiesRunInfo::getChannelSpectrumProperties (Int_t globalChannelNumber) const
Get the channel's spectrum properties knowing the global channel number.
Definition at line 468 of file SpectrumPropertiesRunInfo.cxx.
References getChannelID(), and getChannelSpectrumProperties().
TChannelSpectrumProperties SpectrumPropertiesRunInfo::getChannelSpectrumProperties (ChannelID const & channelID) const
Get the channel's spectrum properties knowing the channel ID.
Definition at line 452 of file SpectrumPropertiesRunInfo.cxx.
References _channelSpectrumPropertiesMap.
Referenced by getChannelSpectrumProperties(), and RunComparator::prepareGraph().
std::vector< SpectrumPropertiesRunInfo::ChannelID > SpectrumPropertiesRunInfo::getChannelsWithMeanCut (Double_t lowerCut = -DBL_MAX, Double_t upperCut = DBL_MAX) const
Returns all channels with a mean value in the cut range (mean >= lowerCut) and (mean <=upperCut). The default maximal value of DBL_MAX (the highest number a double can hold in C++) allows to conveniently use only a lower cut. To apply only an upper cut use -DBL_MAX for the lower cut. This is the smallest negative number a double can hold. Note that DBL_MIN is the smallest positive number a double can hold, i.e. the smallest value that can be ditinguished from 0. Do not use this or 0 if you do not want to cut. Mean values can be negative!
Definition at line 347 of file SpectrumPropertiesRunInfo.cxx.
References TChannelSpectrumProperties::_channel, _channelSpectrumProperties, TChannelSpectrumProperties::_chip, TChannelSpectrumProperties::_mean, TChannelSpectrumProperties::_module, and _spectrumPropertiesTree.
std::vector< SpectrumPropertiesRunInfo::ChannelID > SpectrumPropertiesRunInfo::getChannelsWithRMSCut (Double_t lowerCut = 0, Double_t upperCut = DBL_MAX) const
Returns all channels with an RMS in the cut range (rms >= lowerCut) and (rms <=upperCut). The default maximal value of DBL_MAX (the highest number a double can hold in C++) allows to conveniently use only a lower cut. The lower cut of 0 should be fine since the rms by definition is larger or equals zero.
Definition at line 325 of file SpectrumPropertiesRunInfo.cxx.
References TChannelSpectrumProperties::_channel, _channelSpectrumProperties, TChannelSpectrumProperties::_chip, TChannelSpectrumProperties::_module, TChannelSpectrumProperties::_rms, and _spectrumPropertiesTree.
Referenced by getNoisyChannels(), and RunComparator::prepareGraph().
Int_t SpectrumPropertiesRunInfo::getGlobalChannelNumber (ChannelID const & channelID) [static]
Get the global channel number $( moduleID \cdot nChipsPerModule + chipID ) \cdot nChannelsPerChip + channelNumber $ from the channelID.
Definition at line 420 of file SpectrumPropertiesRunInfo.cxx.
References SpectrumPropertiesRunInfo::ChannelID::_channel, SpectrumPropertiesRunInfo::ChannelID::_chip, SpectrumPropertiesRunInfo::ChannelID::_module, _nChannelsPerChip, and _nChipsPerModule.
Referenced by RunComparator::calculateChannelAndPedestalCorrectedMean(), and main().
Int_t SpectrumPropertiesRunInfo::getNChannelsPerChip () [static]
Get the number of channels per chip.
Definition at line 448 of file SpectrumPropertiesRunInfo.cxx.
References _nChannelsPerChip.
Int_t SpectrumPropertiesRunInfo::getNChipsPerModule () [static]
Get the number of chips per module.
Definition at line 450 of file SpectrumPropertiesRunInfo.cxx.
References _nChipsPerModule.
std::vector< SpectrumPropertiesRunInfo::ChannelID > SpectrumPropertiesRunInfo::getNoisyChannels (Double_t noisyCut) const
Returns a vector with all ChannelIDs of channels which have an rms larger or equal to noisyCut. Just calls getChannelsWithRMSCut(noisyCut); Kept for convenience and backward conpatiblility.
Definition at line 320 of file SpectrumPropertiesRunInfo.cxx.
References getChannelsWithRMSCut().
Int_t SpectrumPropertiesRunInfo::getRunNumber () const
Returns the run number.
Definition at line 520 of file SpectrumPropertiesRunInfo.cxx.
References _runNumber.
Referenced by RunComparator::prepareGraph().
TTree * SpectrumPropertiesRunInfo::getSpectrumPropertiesTree ()
Get a pointer to the spectrum properties tree.
Attention
You do not get the ownership of this tree. It belongs to the SpectrumPropertiesRunInfo class which will delete the tree in its destructor. After that the pointer is no longer valid.
Do not use TTree->SetBranchAddress()! There is the _channelSpectrumProperties variable of SpectrumPropertiesRunInfo which is already set. You can access it with getSpectrumPropertiesTreeObject(). If you change the branch address of the tree getNoisyChannels will fail, might even cause a segfault.
Definition at line 256 of file SpectrumPropertiesRunInfo.cxx.
References _spectrumPropertiesTree.
Referenced by main().
TChannelSpectrumProperties const *const * SpectrumPropertiesRunInfo::getSpectrumPropertiesTreeObject ()
Get the object in memory which is in the branch address of the channel properties tree. With this you can access data from the tree by saying tree->GetEntry(i).
This function returns a pointer to a const pointer to a const TChannelSpectrumProperties. The reason for this is that ROOT modifies the contents of the pointer TChannelSpectrumProperties * _channelSpectrumProperties with every call of tree->GetEntry(i). If it would just return the pointer you would have to call getChannelPropertiesTreeObject() after every call of tree->GetEntry(i).
  mySpectrumPropertiesRunInfo.getChannelPropertiesTree()->GetEntry(1); // get one
       object in the tree
  TChannelSpectrumProperties const * const * channelSpectrumPropertiesObjectHandl
      er
                                                   = mySpectrumPropertiesRunInfo.
      getChannelPropertiesTreeObject();
  // Attention: Do not dereference the handler and save the pointer
  TChannelSpectrumProperties const * const channelSpectrumPropertiesPointer = * c
      hannelSpectrumPropertiesObjectHandler; // It it BAD to store the pointer;
  
  mySpectrumPropertiesRunInfo.getChannelPropertiesTree()->GetEntry(2); // get ano
      ther object in the tree
  // Attention: channelSpectrumPropertiesPointer still points to the first object
      , which might be
  // invalid. A nive way to create segfaults if you access it.
  // correct: dereference when accessising the data
  Double_t mean = (*channelSpectrumPropertiesObjectHandler)->_mean;
Definition at line 473 of file SpectrumPropertiesRunInfo.cxx.
References _channelSpectrumProperties.
bool SpectrumPropertiesRunInfo::openRunFile (std::string runFileName) [protected]
Definition at line 526 of file SpectrumPropertiesRunInfo.cxx.
References _runFile, and _runNumber.
Referenced by SpectrumPropertiesRunInfo().
void SpectrumPropertiesRunInfo::print (std::string fileName = ``) const
Print the spectrum properties tree. Give the name of the file as argument. The file will be recreated, not appended. If the file name is empty print to stdout.
Definition at line 262 of file SpectrumPropertiesRunInfo.cxx.
References TChannelSpectrumProperties::_channel, _channelSpectrumProperties, TChannelSpectrumProperties::_chip, TChannelSpectrumProperties::_mean, TChannelSpectrumProperties::_module, TChannelSpectrumProperties::_rms, _runNumber, and _spectrumPropertiesTree.
void SpectrumPropertiesRunInfo::printChannels (std::vector< SpectrumPropertiesRunInfo::ChannelID > const & listOfChannels)
Convenience function to print a list of channels to the console.
Definition at line 369 of file SpectrumPropertiesRunInfo.cxx.
void SpectrumPropertiesRunInfo::setNChannelsPerChip (Int_t nChannelsPerChip) [static]
Set the number of channels per chip. This is used to calculate the global channel number.
Definition at line 443 of file SpectrumPropertiesRunInfo.cxx.
References _nChannelsPerChip.
void SpectrumPropertiesRunInfo::setNChipsPerModule (Int_t nChipsPerModule) [static]
Set the number of chips per module. This is used to calculate the global channel number.
Definition at line 438 of file SpectrumPropertiesRunInfo.cxx.
References _nChipsPerModule.
Field Documentation
TChannelSpectrumProperties* SpectrumPropertiesRunInfo::_channelSpectrumProperties [protected]
Definition at line 257 of file SpectrumPropertiesRunInfo.h.
Referenced by getChannelsWithMeanCut(), getChannelsWithRMSCut(), getSpectrumPropertiesTreeObject(), print(), and SpectrumPropertiesRunInfo().
std::map< ChannelID, TChannelSpectrumProperties > SpectrumPropertiesRunInfo::_channelSpectrumPropertiesMap [protected]
A map for random access to the TChannelSpectrumPropertiess. This is a duplication of the data in the tree. We pay this price for fast random access, not having to search the tree for every request.
Definition at line 277 of file SpectrumPropertiesRunInfo.h.
Referenced by drawGetDeadChannelsPlot(), getChannelSpectrumProperties(), and SpectrumPropertiesRunInfo().
std::map< ChannelID, std::string > SpectrumPropertiesRunInfo::_histogramTitleMap [protected]
A map to store the ChannelID and the associated histogram titles. This is necessary as the title contains the serial number which is never mapped anywhere and discarded when reading in the histo. This map avoids scanning all keys of the file when accessing individual histograms.
Definition at line 265 of file SpectrumPropertiesRunInfo.h.
Referenced by getChannelHisto(), and SpectrumPropertiesRunInfo().
unsigned int SpectrumPropertiesRunInfo::_moduleTypeMask [protected]
The mask for the module types to accept.
Definition at line 287 of file SpectrumPropertiesRunInfo.h.
Referenced by SpectrumPropertiesRunInfo().
Int_t SpectrumPropertiesRunInfo::_nChannelsPerChip = 18 [static, protected]
Definition at line 279 of file SpectrumPropertiesRunInfo.h.
Referenced by getChannelID(), getGlobalChannelNumber(), getNChannelsPerChip(), and setNChannelsPerChip().
Int_t SpectrumPropertiesRunInfo::_nChipsPerModule = 12 [static, protected]
Definition at line 280 of file SpectrumPropertiesRunInfo.h.
Referenced by getChannelID(), getGlobalChannelNumber(), getNChipsPerModule(), and setNChipsPerModule().
TFile* SpectrumPropertiesRunInfo::_runFile [protected]
Definition at line 252 of file SpectrumPropertiesRunInfo.h.
Referenced by getChannelHisto(), openRunFile(), SpectrumPropertiesRunInfo(), and ~SpectrumPropertiesRunInfo().
Int_t SpectrumPropertiesRunInfo::_runNumber [protected]
Definition at line 250 of file SpectrumPropertiesRunInfo.h.
Referenced by drawGetDeadChannelsPlot(), getRunNumber(), openRunFile(), print(), and SpectrumPropertiesRunInfo().
SimpleMapper* SpectrumPropertiesRunInfo::_simpleMapper [protected]
Definition at line 254 of file SpectrumPropertiesRunInfo.h.
Referenced by SpectrumPropertiesRunInfo(), and ~SpectrumPropertiesRunInfo().
TTree* SpectrumPropertiesRunInfo::_spectrumPropertiesTree [protected]
Definition at line 256 of file SpectrumPropertiesRunInfo.h.
Referenced by getChannelsWithMeanCut(), getChannelsWithRMSCut(), getSpectrumPropertiesTree(), print(), SpectrumPropertiesRunInfo(), and ~SpectrumPropertiesRunInfo().
bool SpectrumPropertiesRunInfo::createdTree [protected]
Definition at line 284 of file SpectrumPropertiesRunInfo.h.
Referenced by ~SpectrumPropertiesRunInfo().
The documentation for this class was generated from the following files:
SpectrumPropertiesRunInfo.h
SpectrumPropertiesRunInfo.cxx