/********************************************************************
* /afs/desy.de/user/t/torimart/work/CosmiTestLCIO/build_calice_calib/calibmulti/rootdict/_afs_desy.de_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/desy.de/user/t/torimart/work/CosmiTestLCIO/build_calice_calib/calibmulti/rootdict/_afs_desy.de_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution();
extern void G__cpp_setup_inheritance_afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution();
extern void G__cpp_setup_typetable_afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution();
extern void G__cpp_setup_memvar_afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution();
extern void G__cpp_setup_global_afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution();
extern void G__cpp_setup_memfunc_afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution();
extern void G__cpp_setup_func_afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution();
extern void G__set_cpp_environment_afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolution();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/afs/desy.de/user/t/torimart/work/CosmiTestLCIO/calice_calib/calibmulti/include/TConvolution.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_TClass;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_TBuffer;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_TMemberInspector;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_TObject;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_string;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_TF1;
extern G__linked_taginfo G___afs_desydOde_user_t_torimart_work_CosmiTestLCIO_calice_calib_calibmulti_src_TConvolutionLN_TConvolution;

/* STUB derived class for protected member access */
