CALICE::PedestalNoiseHistograms Class Reference
Public Member Functions
Processor * newProcessor ()
void init ()
Called at the begin of the job before anything is read.
void processRunHeader (LCRunHeader *run)
Called for every run, e.g.
void processEvent (LCEvent *evtP)
Called for every event - the working horse.
void end ()
Protected Types
enum EH1Type { kH1Noise,
kH1Pedestal,
kNH1
 }
Protected Member Functions
void moduleTypeChanged (lcio::LCCollection *col)
void moduleLocationChanged (lcio::LCCollection *col)
void moduleConnectionChanged (lcio::LCCollection *col)
void detectorChanged ()
void createHistograms ()
Protected Attributes
std::string _cellParameterCollectionName
IntVec _eventPar
histmgr::Key_t _histogramGroupKey
lcio::FloatVec _noiseHistPar
lcio::FloatVec _adcHistPar
histmgr::Key_t _histKey [kNH1]
UInt_t _missingCellParameters
Detailed Description
Definition at line 14 of file PedestalNoiseHistograms.hh.
Member Function Documentation
void CALICE::PedestalNoiseHistograms::init ()
Called at the begin of the job before anything is read. Use to initialize the processor, e.g. book histograms.
Reimplemented from CALICE::VRawADCValueProcessor .
Definition at line 76 of file PedestalNoiseHistograms.cc.
References histmgr::HistMgr::createHistogramGroup().
void CALICE::PedestalNoiseHistograms::processEvent (LCEvent * evtP)
Called for every event - the working horse.
Definition at line 89 of file PedestalNoiseHistograms.cc.
References CALICE::CellParameterAccess::getCellParameter(), histmgr::HistMgr::getHistogramCollection(), CALICE::CellParameter::getNoise(), CALICE::CellParameter::getPedestal(), and histmgr::HistogramCollection_t::histogram().
void CALICE::PedestalNoiseHistograms::processRunHeader (LCRunHeader * run) [inline]
Called for every run, e.g. overwrite to initialize run dependent histograms.
Definition at line 31 of file PedestalNoiseHistograms.hh.
The documentation for this class was generated from the following files:
PedestalNoiseHistograms.hh
PedestalNoiseHistograms.cc