histmgr::FloatHistogram1D Class Reference
A 1-dimensional histogram using float values for the bins.
#include <FloatHistogram1D.hh>Inheritance diagram for histmgr::FloatHistogram1D::
Public Member Functions
FloatHistogram1D (UInt_t id, const HistPar &binning)
Create a histogram with a certain binning.
FloatHistogram1D (lcio::LCObject *a_obj)
FloatHistogram1D (const FloatHistogram1D &a)
void fill (Float_t value, Float_t weight=1.)
fill a value into the histogram
void reset ()
reset the histograms and the number of entries
void addToBinContent (UInt_t bin_index, Float_t value)
manipulate a histogram bin
void setBinContent (UInt_t bin_index, Float_t value)
manipulate a histogram bin
Float_t binContent (UInt_t bin_index) const
Float_t overflow () const
Float_t underflow () const
Float_t mean () const
Float_t rms () const
Root mean square as defined by ROOT.
Float_t variance () const
Variance.
Double_t integral (UInt_t first_bin, UInt_t last_bin) const
sum contentes of bins within the given range
lcio::LCObject * clone () const
Detailed Description
A 1-dimensional histogram using float values for the bins.
Definition at line 12 of file FloatHistogram1D.hh.
Constructor & Destructor Documentation
histmgr::FloatHistogram1D::FloatHistogram1D (UInt_t id, const HistPar & binning)
Create a histogram with a certain binning.
Parameters
id a unique histogram ID,
binning number of bins and range of the axis
Todo a name would be better than an ID but a string can not be easily stored in an LCGenericObject
Definition at line 8 of file FloatHistogram1D.cc.
References HistPar::nBins(), reset(), and histmgr::Histogram1D::setBinning().
Member Function Documentation
Double_t histmgr::FloatHistogram1D::integral (UInt_t first_bin, UInt_t last_bin) const
sum contentes of bins within the given range
Parameters
first_bin index of the first bin
last_bin index of the last bin (included in the sum)
Returns
the sum of the bins
Definition at line 109 of file FloatHistogram1D.cc.
Float_t histmgr::FloatHistogram1D::rms () const
Root mean square as defined by ROOT. divided by n
Definition at line 61 of file FloatHistogram1D.cc.
References histmgr::Histogram1D::entries(), histmgr::Histogram1D::firstBinIndex(), histmgr::Histogram1D::lastBinIndex(), histmgr::Histogram1D::nBins(), histmgr::Histogram1D::xMax(), and histmgr::Histogram1D::xMin().
Float_t histmgr::FloatHistogram1D::variance () const
Variance. divided by n-1
Definition at line 85 of file FloatHistogram1D.cc.
References histmgr::Histogram1D::entries(), histmgr::Histogram1D::firstBinIndex(), histmgr::Histogram1D::lastBinIndex(), histmgr::Histogram1D::nBins(), histmgr::Histogram1D::xMax(), and histmgr::Histogram1D::xMin().
The documentation for this class was generated from the following files:
FloatHistogram1D.hh
FloatHistogram1D.cc