histmgr::HistMgr Class Reference
Manages lists of histograms which can be written to prior assigned files.
#include <HistMgr.hh>
Data Structures
class Group_t
class HistogramGroupData_t
id, destination file and folder of a histogram group
Public Types
enum ECollectionType {
kH1,
kH2,
kProfile,
kGraph,
kNTypes
 }
Public Member Functions
bool histogramGroupExists (const Key_t &group_key) const
Group_t & histogramGroup (const Key_t &group_key)
const Group_t & histogramGroup (const Key_t &group_key) const
Group_t & getOrCreatehistogramGroup (const Key_t &group_key)
Get the addressed histrogram group.
void createHistogramGroup (const Key_t &group_key)
Create an empty histogram group to which histograms can be assigned.
lcio::LCCollection * createHistograms (const Key_t &group_key, const Key_t &collection_key, UInt_t n_hist, const HistPar &par, bool may_overwrite=false) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * createHistograms (const Key_t &group_key, const Key_t &collection_key, const EVENT::StringVec &name_list, UInt_t n_hist, const HistPar &par, bool may_overwrite=false) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * createHistograms (const Key_t &group_key, const Key_t &collection_key, const lcio::IntVec &n_hist_list, const HistPar &par, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
create 2D array of histograms which will all have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * createHistograms (const Key_t &group_key, const Key_t &collection_key, const EVENT::StringVec &name_list, const lcio::IntVec &n_hist_list, const HistPar &par, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
create 2D array of histograms which will all have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * create2DHistograms (const Key_t &group_key, const Key_t &collection_key, UInt_t n_hist, const HistPar &x_par, const HistPar &y_par, bool may_overwrite=false) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * create2DHistograms (const Key_t &group_key, const Key_t &collection_key, const EVENT::StringVec &name_list, UInt_t n_hist, const HistPar &x_par, const HistPar &y_par, bool may_overwrite=false) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * create2DHistograms (const Key_t &group_key, const Key_t &collection_key, const lcio::IntVec &n_hist_list, const HistPar &x_par, const HistPar &y_par, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
create 2D array of histograms which will all have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * create2DHistograms (const Key_t &group_key, const Key_t &collection_key, const EVENT::StringVec &name_list, const lcio::IntVec &n_hist_list, const HistPar &x_par, const HistPar &y_par, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
create 2D array of histograms which will all have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * createProfile (const Key_t &group_key, const Key_t &collection_key, UInt_t n_hist, const HistPar &par, bool may_overwrite=false) throw (std::bad_alloc,std::runtime_error)
create an array of profile histograms which will all have the same binning of the x-axis and the same name (except of a numeric extension).
lcio::LCCollection * createProfile (const Key_t &group_key, const Key_t &collection_key, const EVENT::StringVec &name_list, UInt_t n_hist, const HistPar &par, bool may_overwrite=false) throw (std::bad_alloc,std::runtime_error)
create an array of profile histograms which will all have the same binning of the x-axis and the same name (except of a numeric extension).
lcio::LCCollection * createProfile (const Key_t &group_key, const Key_t &collection_key, const lcio::IntVec &n_hist_list, const HistPar &par, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
create 2D array of profile histograms which will all have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * createProfile (const Key_t &group_key, const Key_t &collection_key, const EVENT::StringVec &name_list, const lcio::IntVec &n_hist_list, const HistPar &par, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
create 2D array of profile histograms which will all have the same binning of the x-axis.
lcio::LCCollection * createGraphCollection (const Key_t &group_key, const Key_t &collection_key, unsigned int n_graphs, const EVENT::StringVec &type_names, unsigned int n_expected_values, const EVENT::StringVec &opt_major_names, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
Create a collection of graphs.
lcio::LCCollection * createGraphCollection (const Key_t &group_key, const Key_t &collection_key, const std::vector< int > &n_graphs, const std::vector< std::string > &type_names, unsigned int n_expected_values, const std::vector< std::string > &opt_major_names, bool may_overwrite=false) throw (std::bad_alloc, std::runtime_error)
Double_t getNEntriesTotal (const Key_t &group_key) const
return the total number of entries in the whole histogram group.
FloatHistogram1D * getHistogram (const Key_t &group_key, const Key_t &hist_key, UInt_t index)
get a histogram of the collection with the given name.
const FloatHistogram1D * getHistogram (const Key_t &group_key, const Key_t &hist_key, UInt_t index) const
get a histogram of the collection with the given name (read only).
const FloatHistogram1D * getHistogram (const Key_t &group_key, const Key_t &hist_key, UInt_t major_index, UInt_t minor_index) const
get a histogram of the collection which is organised as a two dimensional array (read only).
FloatHistogram1D * getHistogram (const Key_t &group_key, const Key_t &hist_key, UInt_t major_index, UInt_t minor_index)
get a histogram of the collection which is organised as a two dimensional array.
FloatHistogram2D * get2DHistogram (const Key_t &group_key, const Key_t &hist_key, UInt_t index)
get a 2D histogram of the collection with the given name.
const FloatHistogram2D * get2DHistogram (const Key_t &group_key, const Key_t &hist_key, UInt_t index) const
get a 2D histogram of the collection with the given name (read only).
const FloatHistogram2D * get2DHistogram (const Key_t &group_key, const Key_t &hist_key, UInt_t major_index, UInt_t minor_index) const
get a 2D histogram of the collection which is organised as a two dimensional array (read only).
FloatHistogram2D * get2DHistogram (const Key_t &group_key, const Key_t &hist_key, UInt_t major_index, UInt_t minor_index)
get a 2D histogram of the collection which is organised as a two dimensional array.
bool exists (const Key_t &group_key, const Key_t &hist_key) const
verify if a histogram of the given name exists already.
HistogramCollection_t & getHistogramCollection (const Key_t &group_key, const Key_t &hist_key)
get the one or two dimensional histogram collection.
const HistogramCollection_t & getHistogramCollection (const Key_t &group_key, const Key_t &hist_key) const
get the one or two dimensional histogram collection (read only).
GraphCollection_t & getGraphCollection (const Key_t &group_key, const Key_t &graph_key)
Get a graph collection.
const GraphCollection_t & getGraphCollection (const Key_t &group_key, const Key_t &graph_key) const
Get a graph collection.
Histogram2DCollection_t & getHistogram2DCollection (const Key_t &group_key, const Key_t &histogram2D_key)
Get a histogram2D collection.
const Histogram2DCollection_t & getHistogram2DCollection (const Key_t &group_key, const Key_t &histogram2D_key) const
Get a histogram2D collection.
ProfileCollection_t & getProfileCollection (const Key_t &group_key, const Key_t &profile_key)
Get a profile collection.
const ProfileCollection_t & getProfileCollection (const Key_t &group_key, const Key_t &profile_key) const
Get a profile collection.
void assignFileName (const Key_t &group_key, const std::string &file_name, const std::string &folder_name=``)
get the histogram collection of the given name (read only) The collection must not be deleted.
void warnOnUnassigned ()
Issue a warning for all histogram groups which are not assigned to a file.
void writeHistograms (bool snapshot=false)
write all histograms groups to the assigned files.
void writeHistograms (const Key_t &group_key, bool snapshot=false)
write all histograms of the specified group to the assigned root file.
void registerWriter (const std::string &name, HistWriterKit *kit)
register a histogram writer.
void listRegisteredGroups () const
UInt_t getNGroups () const
Get the number of groups.
void lockGroup (const Key_t &group_key)
Lock a histogram group.
void unlockGroup (const Key_t &group_key)
Release the lock on the histogram group.
bool hasLockedGroups () const
Return true if some of the groups are locked.
void fillGroupList (std::vector< std::string > &dest_group_list) const
Copy the groups names into the given vecotor.
void fillHistogramCollectionList (const Key_t &group_key, ECollectionType type, std::vector< std::string > &dest_histogram_collection_list) const
Copy the histogram collection names of the specified group to the given vector.
void deleteFolder (const std::string &folder)
Static Public Member Functions
static ECollectionType findType (const std::string &type_name)
static std::pair< std::string, HistMgr::ECollectionType > getGroupNameAndCollectionType (const std::string &full_name)
Split the name which combines the group name and the collection type into its components.
static HistMgr * getInstance ()
static void deleteInstance ()
Protected Types
typedef KeyMap_t< accounting_ptr< Histogram2DCollection_t > > Histogram2DList_t
typedef KeyMap_t< accounting_ptr< HistogramCollection_t > > HistogramList_t
typedef KeyMap_t< accounting_ptr< GraphCollection_t > > GraphList_t
typedef KeyMap_t< Group_t > HistogramGroupList_t
Protected Member Functions
HistMgr ()
constructor
~HistMgr ()
destructor
void writeHistograms (Group_t &group, const std::string &group_name, bool snapshot)
Protected Attributes
HistogramGroupList_t _histogramGroupList
std::map< std::string, HistWriterKit * > _writerKitList
HistWriterKit * _writerKit
Static Protected Attributes
static HistMgr * __histMgr = 0
static const char * __typeName [kNTypes]
Friends
class HistMgrPtr
Detailed Description
Manages lists of histograms which can be written to prior assigned files.
Definition at line 43 of file HistMgr.hh.
Member Function Documentation
void histmgr::HistMgr::assignFileName (const Key_t & group_key, const std::string & file_name, const std::string & folder_name = ``)
get the histogram collection of the given name (read only) The collection must not be deleted.
Parameters
name of the histogram collection
Returns
pointer to the histogram collection or zero. get the histogram collection of the given name The collection must not be deleted.
Parameters
name of the histogram collection
Returns
pointer to the histogram collection or zero. assign a histogram group to the file of the given name
Parameters
group_key the key of the histogram group
file_name the name of the file
folder_name the name of a folder insider the file
Definition at line 270 of file HistMgr.cc.
References histmgr::HistMgr::Group_t::header().
Referenced by histmgr::HistogramOutput::init().
lcio::LCCollection * histmgr::HistMgr::create2DHistograms (const Key_t & group_key, const Key_t & collection_key, const EVENT::StringVec & name_list, const lcio::IntVec & n_hist_list, const HistPar & x_par, const HistPar & y_par, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error)
create 2D array of histograms which will all have the same binning and the same name (except of a numeric extension). To create an array of 2x3 histograms lcio::IntVec index index.push_back(3) index.push_back(3) histmgr::Key_t hist_arr_2d_key(`hist_arr_2d`) histogramList->createHistograms(group_key,hist_arr_2d_key,index,HistPar(4,-.5,.5)); The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Parameters
group_key the name of the group this histogram belongs to
collection_key name of the collection to which the histogram belongs
name_list a vector containing the names of the histograms whose length is either one or equals the number of elements of n_hist_list
n_hist_list an array of histograms per major index
x_par the binning of the x-axis of the histogram
y_par the binning of the y-axis the histogram
may_overwrite flag to overwrite or not the histogram (default: false)
Returns
the index of the first histogram for
Definition at line 195 of file HistMgr.cc.
lcio::LCCollection* histmgr::HistMgr::create2DHistograms (const Key_t & group_key, const Key_t & collection_key, const lcio::IntVec & n_hist_list, const HistPar & x_par, const HistPar & y_par, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error) [inline]
create 2D array of histograms which will all have the same binning and the same name (except of a numeric extension). The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Parameters
group_key the name of the group this histogram belongs to
collection_key name of the collection to which the histogram belongs
n_hist_list an array of histograms per major index
x_par the binning of the x-axis of the histogram
y_par the binning of the y-axis the histogram
may_overwrite flag to overwrite or not the histogram, if existing (default: false)
Returns
the index of the first histogram for
Definition at line 464 of file HistMgr.hh.
References create2DHistograms().
lcio::LCCollection * histmgr::HistMgr::create2DHistograms (const Key_t & group_key, const Key_t & collection_key, const EVENT::StringVec & name_list, UInt_t n_hist, const HistPar & x_par, const HistPar & y_par, bool may_overwrite = false) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension). The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Parameters
group_key the name of the group this histogram belongs to
collection_key the name of the histogram collection
name_list a vector containing the names of the histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all histograms.
n_hist the number of histograms to be created
x_par the binning of the x-axis of the histogram
y_par the binning of the y-axis of the histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
the index of the first histogram for
Definition at line 169 of file HistMgr.cc.
lcio::LCCollection* histmgr::HistMgr::create2DHistograms (const Key_t & group_key, const Key_t & collection_key, UInt_t n_hist, const HistPar & x_par, const HistPar & y_par, bool may_overwrite = false) throw (std::bad_alloc,std::runtime_error) [inline]
create several histograms which will have the same binning and the same name (except of a numeric extension). The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Parameters
group_key the name of the group this histogram belongs to
collection_key the of the histogram collection
n_hist the number of histograms to be created
x_par the binning of the histogram along x
y_par the binning of the histogram along x
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
the index of the first histogram for
Definition at line 425 of file HistMgr.hh.
Referenced by create2DHistograms(), and CALICE::SquareFinder::init().
lcio::LCCollection * histmgr::HistMgr::createGraphCollection (const Key_t & group_key, const Key_t & collection_key, unsigned int n_graphs, const EVENT::StringVec & type_names, unsigned int n_expected_values, const EVENT::StringVec & opt_major_names, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error)
Create a collection of graphs. The graphs are addressed by a major and a minor index. The graph collection can for example be used to create mean, rms, min,max graphs per module. The following parameters can be supplied to the collection:
minor_width : a vector which contains the width for each minor index of the line to be drawn.
minor_style : a vector which contains the style for each minor index used to draw the line.
minor_color : a vector which contains the color for each minor index used to draw the line.
major_color : a vector which contains the color for each major index used to draw the line. This color has precedence over the minor_color
Definition at line 222 of file HistMgr.cc.
Referenced by CALICE::AverageHistoryGraphs::init().
void histmgr::HistMgr::createHistogramGroup (const Key_t & group_key) [inline]
Create an empty histogram group to which histograms can be assigned.
Parameters
group_key the key to address the group
Returns
ID assigned to the group of the given name The group name is uniqe. If the group exists already the id of the existing group is returned.
See also
createHistograms
Definition at line 313 of file HistMgr.hh.
References getOrCreatehistogramGroup().
Referenced by CALICE::HoldScanAnalysis::createHistograms(), CALICE::TriggerAnalysis::init(), CALICE::SimpleHitSearch::init(), CALICE::PedestalNoiseHistograms::init(), and CALICE::AverageHistoryGraphs::init().
lcio::LCCollection * histmgr::HistMgr::createHistograms (const Key_t & group_key, const Key_t & collection_key, const EVENT::StringVec & name_list, const lcio::IntVec & n_hist_list, const HistPar & par, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error)
create 2D array of histograms which will all have the same binning and the same name (except of a numeric extension). To create an array of 2x3 histograms lcio::IntVec index index.push_back(3) index.push_back(3) histmgr::Key_t hist_arr_2d_key(`hist_arr_2d`) histogramList->createHistograms(group_key,hist_arr_2d_key,index,HistPar(4,-.5,3.5)); The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Parameters
group_key the name of the group this histogram belongs to
collection_key name of the collection to which the histogram belongs
name_list a vector containing the names of the histograms whose length is either one or equals the number of elements of n_hist_list
n_hist_list an array of histograms per major index
par the binning of the histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
the index of the first histogram for
Definition at line 142 of file HistMgr.cc.
lcio::LCCollection* histmgr::HistMgr::createHistograms (const Key_t & group_key, const Key_t & collection_key, const lcio::IntVec & n_hist_list, const HistPar & par, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error) [inline]
create 2D array of histograms which will all have the same binning and the same name (except of a numeric extension). The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Parameters
group_key the name of the group this histogram belongs to
collection_key name of the collection to which the histogram belongs
n_hist_list an array of histograms per major index
par the binning of the histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
the index of the first histogram for
Definition at line 378 of file HistMgr.hh.
References createHistograms().
lcio::LCCollection * histmgr::HistMgr::createHistograms (const Key_t & group_key, const Key_t & collection_key, const EVENT::StringVec & name_list, UInt_t n_hist, const HistPar & par, bool may_overwrite = false) throw (std::bad_alloc,std::runtime_error)
create several histograms which will have the same binning and the same name (except of a numeric extension). The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Parameters
group_key the name of the group this histogram belongs to
collection_key the name of the histogram collection
name_list a vector containing the names of the histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all histograms.
n_hist the number of histograms to be created
par the binning of the histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
the index of the first histogram for
Definition at line 117 of file HistMgr.cc.
lcio::LCCollection* histmgr::HistMgr::createHistograms (const Key_t & group_key, const Key_t & collection_key, UInt_t n_hist, const HistPar & par, bool may_overwrite = false) throw (std::bad_alloc,std::runtime_error) [inline]
create several histograms which will have the same binning and the same name (except of a numeric extension). The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Parameters
group_key the name of the group this histogram belongs to
collection_key name the of the histogram collection
n_hist the number of histograms to be created
par the binning of the histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
the index of the first histogram for
Definition at line 341 of file HistMgr.hh.
Referenced by CALICE::HoldScanAnalysis::createHistograms(), createHistograms(), CALICE::TriggerAnalysis::init(), CALICE::SquareFinder::init(), CALICE::HoldScanAnalysis::init(), and CALICE::Clusteriser::init().
lcio::LCCollection* histmgr::HistMgr::createProfile (const Key_t & group_key, const Key_t & collection_key, const EVENT::StringVec & name_list, const lcio::IntVec & n_hist_list, const HistPar & par, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error)
create 2D array of profile histograms which will all have the same binning of the x-axis.
Parameters
group_key the name of the group this profile histogram belongs to
collection_key name of the collection to which the histogram belongs
name_list a vector containing the names of the profile histograms whose length is either one or equals the number of elements of n_hist_list
n_hist_list an array of histograms per major index
par the binning of the x-axis of the profile histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
a pointer to the the profile histogram collection
lcio::LCCollection* histmgr::HistMgr::createProfile (const Key_t & group_key, const Key_t & collection_key, const lcio::IntVec & n_hist_list, const HistPar & par, bool may_overwrite = false) throw (std::bad_alloc, std::runtime_error) [inline]
create 2D array of profile histograms which will all have the same binning and the same name (except of a numeric extension).
Parameters
group_key the name of the group this profile histogram belongs to
collection_key name of the collection to which the histogram belongs
n_hist_list an array of histograms per major index
par the binning of the x-axis of the profile histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
a pointer to the the profile histogram collection
Definition at line 544 of file HistMgr.hh.
References createProfile().
lcio::LCCollection* histmgr::HistMgr::createProfile (const Key_t & group_key, const Key_t & collection_key, const EVENT::StringVec & name_list, UInt_t n_hist, const HistPar & par, bool may_overwrite = false) throw (std::bad_alloc,std::runtime_error)
create an array of profile histograms which will all have the same binning of the x-axis and the same name (except of a numeric extension).
Parameters
group_key the name of the group this profile histogram belongs to
collection_key name of the collection to which the histogram belongs
name_list a vector containing the names of the profile histograms whose length is either one or equals the number of elements of n_hist_list
n_hist the number of histograms to be created
par the binning of the x-axis of the profile histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
a pointer to the the profile histogram collection
lcio::LCCollection* histmgr::HistMgr::createProfile (const Key_t & group_key, const Key_t & collection_key, UInt_t n_hist, const HistPar & par, bool may_overwrite = false) throw (std::bad_alloc,std::runtime_error) [inline]
create an array of profile histograms which will all have the same binning of the x-axis and the same name (except of a numeric extension).
Parameters
group_key the name of the group this profile histogram belongs to
collection_key name of the collection to which the histogram belongs
n_hist the number of histograms to be created
par the binning of the x-axis of the profile histogram
may_overwrite flag to overwrite or not the histogram, if already existing (default: false)
Returns
a pointer to the the profile histogram collection
Definition at line 511 of file HistMgr.hh.
Referenced by createProfile().
void histmgr::HistMgr::fillGroupList (std::vector< std::string > & dest_group_list) const
Copy the groups names into the given vecotor.
Parameters
dest_group_list the vector which will be filled with the group names. First the given vector will be cleared. Then all group names will be copied to it.
Definition at line 317 of file HistMgr.cc.
void histmgr::HistMgr::fillHistogramCollectionList (const Key_t & group_key, ECollectionType type, std::vector< std::string > & dest_histogram_collection_list) const
Copy the histogram collection names of the specified group to the given vector.
Parameters
group_key the name of the group whose histogram collection are considered.
type type of the collection to which the histogram belongs
dest_histogram_collection_list the vector which will be filled with the names of the histgram collections which are associated to the specified group. First the given vector will be cleared. Then all the names of the histogram collections which are associated to the specfied group will be copied to it.
Definition at line 354 of file HistMgr.cc.
References histmgr::HistMgr::Group_t::graphCollection(), histmgr::HistMgr::Group_t::histogram2DCollection(), histmgr::HistMgr::Group_t::histogramCollection(), histmgr::GraphCollection_t::n(), histmgr::ProfileCollection_t::n(), histmgr::Histogram2DCollection_t::n(), histmgr::HistogramCollection_t::n(), histmgr::HistMgr::Group_t::nameListIterators(), and histmgr::HistMgr::Group_t::profileCollection().
FloatHistogram2D* histmgr::HistMgr::get2DHistogram (const Key_t & group_key, const Key_t & hist_key, UInt_t major_index, UInt_t minor_index) [inline]
get a 2D histogram of the collection which is organised as a two dimensional array. The histogram must not be deleted. Generally, the method does not check the validity of the indices. the method throws exceptions if the collection does not exist or If BOUNDARY_CHECK is defined and the indices are out of range.
Parameters
group_key name of the histogram's group
hist_key name of the histogram
major_index the major index within the collection
minor_index the major index within the collection
Returns
pointer to the histogram collection or zero.
Definition at line 797 of file HistMgr.hh.
const FloatHistogram2D* histmgr::HistMgr::get2DHistogram (const Key_t & group_key, const Key_t & hist_key, UInt_t major_index, UInt_t minor_index) const [inline]
get a 2D histogram of the collection which is organised as a two dimensional array (read only). The histogram must not be deleted. Generally, the method does not check the validity of the indices. the method throws exceptions if the collection does not exist or If BOUNDARY_CHECK is defined and the indices are out of range.
Parameters
group_key name of the histogram's group
hist_key name of the histogram
major_index the major index within the collection
minor_index the major index within the collection
Returns
pointer to the histogram collection or zero.
Definition at line 770 of file HistMgr.hh.
const FloatHistogram2D* histmgr::HistMgr::get2DHistogram (const Key_t & group_key, const Key_t & hist_key, UInt_t index) const [inline]
get a 2D histogram of the collection with the given name (read only). The histogram must not be deleted. Generally, the method does not check the validity of the index. the method throws exceptions if the collection does not exist or If BOUNDARY_CHECK is defined and the index is out of range.
Parameters
group_key name of the histogram's group
hist_key name of the histogram
index the index within the collection
Returns
pointer to the histogram collection or zero.
Definition at line 744 of file HistMgr.hh.
FloatHistogram2D* histmgr::HistMgr::get2DHistogram (const Key_t & group_key, const Key_t & hist_key, UInt_t index) [inline]
get a 2D histogram of the collection with the given name. The histogram must not be deleted. Generally, the method does not check the validity of the index. the method throws exceptions if the collection does not exist or If BOUNDARY_CHECK is defined and the index is out of range.
Parameters
group_key name of the histogram's group
hist_key name of the histogram
index the index within the collection
Returns
pointer to the histogram collection or zero.
Definition at line 718 of file HistMgr.hh.
const GraphCollection_t& histmgr::HistMgr::getGraphCollection (const Key_t & group_key, const Key_t & graph_key) const [inline]
Get a graph collection. (read only).
Definition at line 865 of file HistMgr.hh.
FloatHistogram1D* histmgr::HistMgr::getHistogram (const Key_t & group_key, const Key_t & hist_key, UInt_t major_index, UInt_t minor_index) [inline]
get a histogram of the collection which is organised as a two dimensional array. The histogram must not be deleted. Generally, the method does not check the validity of the indices. the method throws exceptions if the collection does not exist or If BOUNDARY_CHECK is defined and the indices are out of range.
Parameters
group_key name of the histogram's group
hist_key name of the histogram
major_index the major index within the collection
minor_index the major index within the collection
Returns
pointer to the histogram collection or zero.
Definition at line 693 of file HistMgr.hh.
const FloatHistogram1D* histmgr::HistMgr::getHistogram (const Key_t & group_key, const Key_t & hist_key, UInt_t major_index, UInt_t minor_index) const [inline]
get a histogram of the collection which is organised as a two dimensional array (read only). The histogram must not be deleted. Generally, the method does not check the validity of the indices. the method throws exceptions if the collection does not exist or If BOUNDARY_CHECK is defined and the indices are out of range.
Parameters
group_key name of the histogram's group
hist_key name of the histogram
major_index the major index within the collection
minor_index the major index within the collection
Returns
pointer to the histogram collection or zero.
Definition at line 666 of file HistMgr.hh.
const FloatHistogram1D* histmgr::HistMgr::getHistogram (const Key_t & group_key, const Key_t & hist_key, UInt_t index) const [inline]
get a histogram of the collection with the given name (read only). The histogram must not be deleted. Generally, the method does not check the validity of the index. the method throws exceptions if the collection does not exist or If BOUNDARY_CHECK is defined and the index is out of range.
Parameters
group_key name of the histogram's group
hist_key name of the histogram
index the index within the collection
Returns
pointer to the histogram collection or zero.
Definition at line 640 of file HistMgr.hh.
FloatHistogram1D* histmgr::HistMgr::getHistogram (const Key_t & group_key, const Key_t & hist_key, UInt_t index) [inline]
get a histogram of the collection with the given name. The histogram must not be deleted. Generally, the method does not check the validity of the index. the method throws exceptions if the collection does not exist or If BOUNDARY_CHECK is defined and the index is out of range.
Parameters
group_key name of the histogram's group
hist_key name of the histogram
index the index within the collection
Returns
pointer to the histogram collection or zero.
Definition at line 614 of file HistMgr.hh.
const Histogram2DCollection_t& histmgr::HistMgr::getHistogram2DCollection (const Key_t & group_key, const Key_t & histogram2D_key) const [inline]
Get a histogram2D collection. (read only).
Definition at line 883 of file HistMgr.hh.
Double_t histmgr::HistMgr::getNEntriesTotal (const Key_t & group_key) const
return the total number of entries in the whole histogram group.
Definition at line 409 of file HistMgr.cc.
References histmgr::Histogram1D::entries(), histmgr::HistogramCollection_t::histogram(), histmgr::HistogramCollection_t::is2D(), histmgr::HistogramCollection_t::n(), histmgr::HistogramCollection_t::nMajor(), and histmgr::HistogramCollection_t::nMinor().
const ProfileCollection_t& histmgr::HistMgr::getProfileCollection (const Key_t & group_key, const Key_t & profile_key) const [inline]
Get a profile collection. (read only).
Definition at line 901 of file HistMgr.hh.
void histmgr::HistMgr::lockGroup (const Key_t & group_key) [inline]
Lock a histogram group. If a group is locked it will not be deleted until the lock is released.
See also
unlockGroup
Definition at line 981 of file HistMgr.hh.
Referenced by CALICE::TriggerAnalysis::init(), CALICE::SimpleHitSearch::init(), and CALICE::AverageHistoryGraphs::init().
void histmgr::HistMgr::registerWriter (const std::string & name, HistWriterKit * kit) [inline]
register a histogram writer. At least one writer is needed to write histograms to disk.
Definition at line 964 of file HistMgr.hh.
void histmgr::HistMgr::unlockGroup (const Key_t & group_key)
Release the lock on the histogram group. If a group is locked it will not be deleted until the lock is released.
See also
lockGroup
Definition at line 101 of file HistMgr.cc.
void histmgr::HistMgr::warnOnUnassigned ()
Issue a warning for all histogram groups which are not assigned to a file.
Definition at line 306 of file HistMgr.cc.
Referenced by histmgr::HistogramOutput::init().
void histmgr::HistMgr::writeHistograms (const Key_t & group_key, bool snapshot = false)
write all histograms of the specified group to the assigned root file. If no file name was
See also
HistWriter, HistWriterKit
Definition at line 442 of file HistMgr.cc.
References writeHistograms().
void histmgr::HistMgr::writeHistograms (bool snapshot = false)
write all histograms groups to the assigned files. groups to which no file was assigned are not written
See also
HistWriter, HistWriterKit
Definition at line 291 of file HistMgr.cc.
References histmgr::HistMgr::Group_t::header().
Referenced by histmgr::HistogramOutput::end(), and writeHistograms().
Field Documentation
const char * histmgr::HistMgr::__typeName [static, protected]
Initial value:
    "1D",
    "2D",
    "Profile",
    "Graph"
  
Definition at line 1103 of file HistMgr.hh.
The documentation for this class was generated from the following files:
HistMgr.hh
HistMgr.cc