Calibration Class Reference
Abstract interface of a calibration object.
#include <Calibration.hh>Inheritance diagram for Calibration::
Public Member Functions
virtual Float_t getCalibratedValue (UInt_t module_id, UInt_t module_type, UInt_t cell_index, Float_t adc_value) const =0
Determine from a pedestal subtracted ADC value a calibrated value.
virtual Bool_t isValid (UInt_t module_id, UInt_t module_type, UInt_t cell_index) const
Return true if a the calibration constants for the given cell are in the allowed range.
virtual Bool_t checkForCalibrationConstantsOfModule (UInt_t module_id, UInt_t module_type, UInt_t n_cells) const =0
Verify that calibration constants exist for a certain module.
virtual Int_t getMiniumADCForMipThreshold (Float_t mip_energy_fraction) const =0
Get the minimum adc value mips will have for the given energy fraction on all pads.
Detailed Description
Abstract interface of a calibration object. The calibration object returns for a value measured with a certain cell a calibrated value.
Definition at line 9 of file Calibration.hh.
Member Function Documentation
virtual Bool_t Calibration::checkForCalibrationConstantsOfModule (UInt_t module_id, UInt_t module_type, UInt_t n_cells) const [pure virtual]
Verify that calibration constants exist for a certain module.
Parameters
module_id id Or serial number of a module which uniquely identifies a detector module of a certain type.
module_type the type of the detector module
n_cells the number of cells on this module. Return true if calibration constants exist for the given module and the number of cells matches the number of calibration constants.
Implemented in ConstantCalibration , and NoOpCalibration .
Referenced by CALICE::SimpleHitSearch::buildCellParameters().
virtual Float_t Calibration::getCalibratedValue (UInt_t module_id, UInt_t module_type, UInt_t cell_index, Float_t adc_value) const [pure virtual]
Determine from a pedestal subtracted ADC value a calibrated value.
Parameters
module_id id Or serial number of a module which uniquely identifies a detector module of a certain type.
module_type the type of the detector module
cell_index the cell_index in read order: first the ADC values of the first sample from all chips, then the next sample ...
adc_value the ADC value which should be calibrated.
Returns
the calibrated value.
Implemented in ConstantCalibration , and NoOpCalibration .
Referenced by CALICE::CalibrateAndApplyThreshold::processEvent().
virtual Int_t Calibration::getMiniumADCForMipThreshold (Float_t mip_energy_fraction) const [pure virtual]
Get the minimum adc value mips will have for the given energy fraction on all pads.
Parameters
mip_energy_fraction the energy in mips
Returns
minimum adc value which is below the given energy on all pads. This method can be used to get the lowest adc value a mip of the given energy fraction will have on all pads. This value is useful to select candidates before actually performing th calibration. This function is intended to be called at the beginning of each event.
Implemented in ConstantCalibration , and NoOpCalibration .
Referenced by CALICE::CalibrateAndApplyThreshold::processEvent(), CALICE::SimpleHitSearch::searchHits(), and CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise().
virtual Bool_t Calibration::isValid (UInt_t module_id, UInt_t module_type, UInt_t cell_index) const [inline, virtual]
Return true if a the calibration constants for the given cell are in the allowed range.
Parameters
module_id id Or serial number of a module which uniquely identifies a detector module of a certain type.
module_type the type of the detector module
cell_index the cell_index in read order: first the ADC values of the first sample from all chips, then the next sample ...
Returns
true for cells with valid calibration constants, false for cells which should be declared dead.
This method is used to find, after module connection changes, cells which should be declared dead.
Definition at line 31 of file Calibration.hh.
Referenced by CALICE::SimpleHitSearch::buildCellParameters(), CALICE::CalibrateAndApplyThreshold::processRunHeader(), CALICE::SimpleHitSearch::resetForInitialPedestalNoiseCalculation(), and CALICE::SimpleHitSearch::resetForPedestalNoiseReCalculation().
The documentation for this class was generated from the following file:
Calibration.hh