histmgr::Profile1D Class Reference
A 1-dimensional histogram using float values for the bins.
#include <Profile1D.hh>Inheritance diagram for histmgr::Profile1D::
Public Member Functions
Profile1D (UInt_t id, const HistPar &binning)
Create a histogram with a certain binning.
Profile1D (lcio::LCObject *a_obj)
Profile1D (const Profile1D &a)
void fill (Float_t x_value, Double_t value, Double_t weight=1.)
fill a value into the histogram
void reset ()
reset the histograms and the number of entries
Double_t sum (UInt_t bin_index) const
Double_t sum2 (UInt_t bin_index) const
Double_t mean (UInt_t bin_index) const
Double_t sigma (UInt_t bin_index) const
Return the rms of the bin.
Double_t rms (UInt_t bin_index) const
Double_t min (UInt_t bin_index) const
Double_t max (UInt_t bin_index) const
Double_t sumOfWeights (UInt_t bin_index) const
void calculate ()
Float_t mean () const
Float_t rms () const
Root mean square as defined by ROOT.
Float_t variance () const
Variance.
lcio::LCObject * clone () const
Protected Types
enum EBinType {
kSum,
kSum2,
kMin,
kMax,
kWeightSum,
kNBinTypes
 }
Protected Member Functions
void addToBinContent (UInt_t type_i, UInt_t bin_index, Double_t value)
void setBinContent (UInt_t type_i, UInt_t bin_index, Double_t value)
Double_t binContent (UInt_t type_i, UInt_t bin_index) const
bool isCalculated (UInt_t bin_index) const
UInt_t getValueIndex (UInt_t type_i, UInt_t bin_index) const
Detailed Description
A 1-dimensional histogram using float values for the bins.
Definition at line 13 of file Profile1D.hh.
Constructor & Destructor Documentation
histmgr::Profile1D::Profile1D (UInt_t id, const HistPar & binning)
Create a histogram with a certain binning.
Parameters
id a unique histogram ID,
binning number of bins and range of the axis
Todo a name would be better than an ID but a string can not be easily stored in an LCGenericObject
Definition at line 8 of file Profile1D.cc.
References HistPar::nBins(), reset(), and histmgr::Histogram1D::setBinning().
Member Function Documentation
Float_t histmgr::Profile1D::rms () const
Root mean square as defined by ROOT. divided by n
Definition at line 63 of file Profile1D.cc.
References histmgr::Histogram1D::firstBinIndex(), histmgr::Histogram1D::lastBinIndex(), histmgr::Histogram1D::nBins(), sum(), histmgr::Histogram1D::xMax(), and histmgr::Histogram1D::xMin().
Referenced by sigma().
Double_t histmgr::Profile1D::sigma (UInt_t bin_index) const [inline]
Return the rms of the bin. deprecated.
Definition at line 81 of file Profile1D.hh.
References rms().
Double_t histmgr::Profile1D::sum (UInt_t bin_index) const [inline]
manipulate a histogram bin
Definition at line 201 of file Profile1D.hh.
Referenced by rms(), and variance().
Float_t histmgr::Profile1D::variance () const
Variance. divided by n-1
Definition at line 94 of file Profile1D.cc.
References histmgr::Histogram1D::firstBinIndex(), histmgr::Histogram1D::lastBinIndex(), histmgr::Histogram1D::nBins(), sum(), histmgr::Histogram1D::xMax(), and histmgr::Histogram1D::xMin().
The documentation for this class was generated from the following files:
Profile1D.hh
Profile1D.cc