marlin::RunInfoProcessor Class Reference
Preprocessor which is supposed to run at the !very! beginning of the processor chain.
#include <RunInfoProcessor.hh>
Data Structures
class LCRunModifier
Helper class to for the modification of the Run Header.
Public Member Functions
virtual Processor * newProcessor ()
virtual void init ()
Called at the begin of the job before anything is read.
virtual void processRunHeader (LCRunHeader *run)
Called for every run.
virtual void processEvent (LCEvent *evt)
Called for every event - the working horse.
virtual const std::string & name () const
Needed for modifyEvent.
virtual void modifyEvent (LCEvent *evt)
virtual void check (LCEvent *evt)
virtual void end ()
Called after data processing for clean up.
void printRunParameters (const LCRunHeader *run)
Method to write the histograms in a ROOT file.
Private Member Functions
void setVersString (std::string)
The function which sets the version string.
unsigned int handleBeamParameters (LCCDTimeStamp)
Handling of beam parameters to extract energy.
float timeCor ()
A helper function which determines corrections to be applied when check for r/o time of (cern) database of cern beam parameters.
unsigned int getBeamEnergy (const LCCDTimeStamp)
Method to get the beam energy from the database for a given time stamp (default).
unsigned int getBeamEnergyUser (const LCCDTimeStamp)
Method to get the beam energy from the database for a given time stamp (user defined settings).
Private Attributes
std::string _dbInit
dbinit string, note that in this Processor we cannot make use of the ConditionsDataProcessor Mechanism as it may run also on MC where the event time has to be set by this processor
std::string _folderRunTime
The variable holding the folder name from which we fetch the runinfo.
std::string _folderBeamParameter
The folder which holds the information on the beam parameter.
float _currentTolerance
Tolerance in % allowed until current reading at run begin and run end is considered to be inconsinstent.
float _timeTolerance
Tolerance in s allowed until reading of beam parameters is considered to be outdated.
std::string _folderBeamParameterException
The variable which holds the folder name for the BeamParameterException, i.e.
std::string _folderLocation
The variable which holds the name of the folder to look up the run location.
RunLocationWhizard * _runlocationwhizard
The object which holds the information on the run location.
std::string _vers_string
A string which contains the version of the converter and therefore of the db entry.
int _vers_length
The length of the version string.
int _runNumber
Obvious variables.
unsigned int _beamEnergy
int _bendingCurrentToCheck
variables needed to convert current to energy
float _currentToEnergy
float _toMeV
int _safetyMargin
Variable which can be used to ensure validity of conditions data in case of MC.
int _nRun
Obvious counter variables, needed?
int _nEvt
RunInformation * _runInformation
An object which assembles run information.
UTIL::LCTime _eventTime
The event time, created for MC, not in use for real data.
bool _overwriteRunNumber
Detailed Description
Preprocessor which is supposed to run at the !very! beginning of the processor chain. Adding information to the Run and EventHeader, for data and MC. In partcular the beam energy is extracted from the database for a given run and the MC events get assigned a timestamp.
Author
: A.M. Magnan Imperial College, modifs R.Poeschl LAL
Date
Apr 2007
Todo reduce even more the dependency on hardcoded, god given parameters in the code (valid for many processors)
Definition at line 52 of file RunInfoProcessor.hh.
Member Function Documentation
unsigned int marlin::RunInfoProcessor::handleBeamParameters (LCCDTimeStamp starttime) [private]
Handling of beam parameters to extract energy.
Todo extend scope of function and maybe turn into dedicated class
Definition at line 429 of file RunInfoProcessor.cc.
References _bendingCurrentToCheck, _currentTolerance, _dbInit, _folderBeamParameter, _folderBeamParameterException, _runNumber, _timeTolerance, and timeCor().
Referenced by getBeamEnergy().
void marlin::RunInfoProcessor::init () [virtual]
Called at the begin of the job before anything is read. Use to initialize the processor, e.g. book histograms.
Definition at line 153 of file RunInfoProcessor.cc.
References _nRun.
float marlin::RunInfoProcessor::timeCor () [private]
A helper function which determines corrections to be applied when check for r/o time of (cern) database of cern beam parameters.
Todo remove hardcoded times
Definition at line 570 of file RunInfoProcessor.cc.
References _runInformation.
Referenced by handleBeamParameters().
Field Documentation
std::string marlin::RunInfoProcessor::_folderBeamParameterException [private]
The variable which holds the folder name for the BeamParameterException, i.e. to be queried in case of pbs. with automatic r/o of beam parameters.
Definition at line 108 of file RunInfoProcessor.hh.
Referenced by getBeamEnergy(), and handleBeamParameters().
The documentation for this class was generated from the following files:
RunInfoProcessor.hh
RunInfoProcessor.cc