CALICE::HodoscopeBlock Class Reference
#include <hodoscopeBlock.hh>
Public Member Functions
HodoscopeBlock (int header, int size, int trigN, int cycleN, int tdc, int data_0, int data_1, int data_2, int data_3, int data_4, int data_5, int data_6, int data_7, int data_8, int data_9, int data_10, int data_11, int data_12, int data_13, int data_14, int data_15, int data_16, int data_17, int data_18, int data_19, int data_20, int data_21, int data_22, int data_23, int data_24, int data_25, int data_26, int data_27, int data_28, int data_29, int data_30, int data_31, int data_32, int data_33, int data_34, int data_35, int data_36, int data_37, int data_38, int data_39, int data_40, int data_41, int data_42, int data_43, int data_44, int data_45, int data_46, int data_47, int data_48, int data_49, int data_50, int data_51, int data_52, int data_53, int data_54, int data_55, int data_56, int data_57, int data_58, int data_59, int data_60, int data_61, int data_62, int data_63)
HodoscopeBlock (LCObject *obj)
virtual ~HodoscopeBlock ()
int GetHeader () const
int GetSize () const
int GetTrigN () const
int GetCycleN () const
int GetTDC () const
int GetAccept () const
std::vector< int > GetADC () const
std::vector< int > GetChannel () const
void print (std::ostream &os, int)
const std::string getTypeName () const
const std::string getDataDescription () const
Detailed Description
Class for the SLCIO hododscope as acquired by the EUDAQ system.
Author
L. Liu, based on the EUDAQBlock writen by A. Irles DESY Hamburg
Date
November 9 2017 Created for cosmic test hodoscope data format.
Definition at line 23 of file hodoscopeBlock.hh.
Constructor & Destructor Documentation
CALICE::HodoscopeBlock::HodoscopeBlock (int header, int size, int trigN, int cycleN, int tdc, int data_0, int data_1, int data_2, int data_3, int data_4, int data_5, int data_6, int data_7, int data_8, int data_9, int data_10, int data_11, int data_12, int data_13, int data_14, int data_15, int data_16, int data_17, int data_18, int data_19, int data_20, int data_21, int data_22, int data_23, int data_24, int data_25, int data_26, int data_27, int data_28, int data_29, int data_30, int data_31, int data_32, int data_33, int data_34, int data_35, int data_36, int data_37, int data_38, int data_39, int data_40, int data_41, int data_42, int data_43, int data_44, int data_45, int data_46, int data_47, int data_48, int data_49, int data_50, int data_51, int data_52, int data_53, int data_54, int data_55, int data_56, int data_57, int data_58, int data_59, int data_60, int data_61, int data_62, int data_63) [inline]
Very ugly constructor because we use a Generic Object with many integers
Definition at line 31 of file hodoscopeBlock.hh.
CALICE::HodoscopeBlock::HodoscopeBlock (LCObject * obj) [inline]
'Copy constructor' needed to interpret LCCollection read from file/database.
Definition at line 114 of file hodoscopeBlock.hh.
virtual CALICE::HodoscopeBlock::~HodoscopeBlock () [inline, virtual]
Important for memory handling
Definition at line 117 of file hodoscopeBlock.hh.
Member Function Documentation
int CALICE::HodoscopeBlock::GetAccept () const [inline]
get the accept.
Definition at line 151 of file hodoscopeBlock.hh.
Referenced by marlin::HodoscopeWriteEngine::fillVariables().
std::vector<int> CALICE::HodoscopeBlock::GetADC () const [inline]
get the ADC.
Definition at line 157 of file hodoscopeBlock.hh.
Referenced by marlin::HodoscopeWriteEngine::fillVariables().
std::vector<int> CALICE::HodoscopeBlock::GetChannel () const [inline]
get the channel.
Definition at line 168 of file hodoscopeBlock.hh.
int CALICE::HodoscopeBlock::GetCycleN () const [inline]
get the cycle number.
Definition at line 139 of file hodoscopeBlock.hh.
Referenced by marlin::HodoscopeWriteEngine::fillVariables().
const std::string CALICE::HodoscopeBlock::getDataDescription () const [inline]
Return a brief description of the data members
Definition at line 200 of file hodoscopeBlock.hh.
int CALICE::HodoscopeBlock::GetHeader () const [inline]
get the header (0xffff7368 = -35992).
Definition at line 121 of file hodoscopeBlock.hh.
int CALICE::HodoscopeBlock::GetSize () const [inline]
get the size.
Definition at line 127 of file hodoscopeBlock.hh.
int CALICE::HodoscopeBlock::GetTDC () const [inline]
get the tdc.
Definition at line 145 of file hodoscopeBlock.hh.
Referenced by marlin::HodoscopeWriteEngine::fillVariables().
int CALICE::HodoscopeBlock::GetTrigN () const [inline]
get the trigger number (up to 4095).
Definition at line 133 of file hodoscopeBlock.hh.
const std::string CALICE::HodoscopeBlock::getTypeName () const [inline]
Return the type of the class
Definition at line 194 of file hodoscopeBlock.hh.
void CALICE::HodoscopeBlock::print (std::ostream & os, int)
Convenient print method
The documentation for this class was generated from the following file:
hodoscopeBlock.hh