marlin::HodoscopeWriteEngine Class Reference
Public Member Functions
HodoscopeWriteEngine (RootTreeWriter *host)
virtual const std::string & getEngineName ()
virtual void registerParameters ()
virtual void registerBranches (TTree *hostTree)
virtual void fillVariables (EVENT::LCEvent *)
double adc2nph (int adc, int ihod, int ch)
void recoverDeadCh ()
void reconstruct (int ihod)
double trackDistance (double x1, double y1, double x2, double y2, float *pos)
void chAt (int fiber, int ihod, int axis, int *ch)
double thetaWith (int fiber)
double fiberWith (double theta)
double argWith (double x, double y)
double edgeCorrection (double x)
Public Attributes
xx xx xx xx xx xx xx xx xx
struct {
 int cycle [2]
 int tdc [2]
 int accept [2]
 int adc [2][64]
 double nph [2][64]
 int nRecoX [2]
 int nRecoY [2]
 double recoX [2][8]
 double recoY [2][8]
 double trueRecoX [2]
 double trueRecoY [2]
} _hitsFill
xx xx xx xx xx xx xx xx xx
struct {
 int nHits
 int hitI [MAXCELLS]
 int hitJ [MAXCELLS]
 int hitK [MAXCELLS]
 float hitEnergy [MAXCELLS]
 float hitPos [MAXCELLS][3]
} _ahcHits
Static Public Attributes
static const unsigned int MAXCELLS = 7609
Detailed Description
Definition at line 19 of file HodoscopeWriteEngine.hh.
Member Function Documentation
void marlin::HodoscopeWriteEngine::fillVariables (EVENT::LCEvent * evt) [virtual]
Implement this to extract the variables which you want to fill into the ROOT tree from the event. Write the value of the variables you want to add to the tree to the member variables, which you registered to the ROOT tree. The RootTreeWriter will call TTree::Fill() for you.
Parameters
evt the current event
Implements marlin::RootWriteEngine .
Definition at line 156 of file HodoscopeWriteEngine.cc.
References CALICE::HodoscopeBlock::GetAccept(), CALICE::HodoscopeBlock::GetADC(), CALICE::HodoscopeBlock::GetCycleN(), and CALICE::HodoscopeBlock::GetTDC().
virtual const std::string& marlin::HodoscopeWriteEngine::getEngineName () [inline, virtual]
Returns the name of the engine to the RootTreeWriter processor.
Returns
Must return a string with the engine name.
Todo fixme: should be const, but must be declared const in implementations too. Need to fix all existing engines?!?
Implements marlin::RootWriteEngine .
Definition at line 28 of file HodoscopeWriteEngine.hh.
void marlin::HodoscopeWriteEngine::registerBranches (TTree *) [virtual]
Implement to register local variables to the output tree
Parameters
pointer to the ROOT tree, which the RootTreeWriter processor fills at the end of each event. Usually the implementation looks like
    /// hostTree->Branch("variable",&_variable" ,"variable/F"  );
    /// 
. But you can add any type of branch you like.
Implements marlin::RootWriteEngine .
Definition at line 102 of file HodoscopeWriteEngine.cc.
void marlin::HodoscopeWriteEngine::registerParameters () [virtual]
Used to register steering parameters. Implement to register marlin steering file parameters. Use marlin syntax to register parameters for the calling RootTreeWriter processor.
use
    /// _hostProc.relayRegisterProcessorParameter(...)
    /// _hostProc.relayRegister...()
    /// 
 instead of marlin processors
register...() 
 methods
Implements marlin::RootWriteEngine .
Definition at line 35 of file HodoscopeWriteEngine.cc.
References marlin::RootTreeWriter::relayRegisterInputCollection(), and marlin::RootTreeWriter::relayRegisterProcessorParameter().
The documentation for this class was generated from the following files:
HodoscopeWriteEngine.hh
HodoscopeWriteEngine.cc