createSpriTree.cpp File Reference
#include `SpectrumPropertiesRunInfo.h`
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <TGraph.h>
#include <TVector.h>
#include <TCanvas.h>
#include <TLegend.h>
#include <TStyle.h>
Functions
void printUsage (void)
void printChannelStatusMap (std::map< int, int > const &channelStatusMap, std::ostream &s=std::cout)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 64 of file createSpriTree.cpp.
References SpectrumPropertiesRunInfo::getSpectrumPropertiesTree(), and printUsage().
void printChannelStatusMap (std::map< int, int > const & channelStatusMap, std::ostream & s = std::cout)
Definition at line 45 of file createSpriTree.cpp.
References SpectrumPropertiesRunInfo::ChannelID::_channel, SpectrumPropertiesRunInfo::ChannelID::_chip, SpectrumPropertiesRunInfo::ChannelID::_module, and SpectrumPropertiesRunInfo::getChannelID().
void printUsage (void)
Definition at line 28 of file createSpriTree.cpp.