Langaus Class Reference
Class for handling with a fitting function defined as $ (l\otimes g)(x)=\int_{-\infty}^{\infty}\mbox{d}y\ l(x-y)\cdot g(y)$, where $l(x)$ is a Landau function and $ g(x)$ is a Gaus function.
#include <Langaus.hh>
Public Member Functions
Langaus (const double *fitrange, const double *startValues, const double *parlimitslo, const double *parlimitshi, bool useFFT)
Constructor (Initialization of range, initial parameters, low and high limits of parameters).
RooAbsReal * getT (void)
RooAbsReal * getMg (void)
RooAbsReal * getSg (void)
RooAbsReal * getMl (void)
RooAbsReal * getSl (void)
RooLandau * getLandau (void)
RooGaussian * getGauss (void)
double getPeak ()
double getEpeak ()
double getLogL ()
double getChiSquare ()
double getMlerror (void)
double getSlerror (void)
double getSgerror (void)
Langaus & setMl (double ml)
Langaus & setSl (double sl)
Langaus & setSg (double sg)
Langaus & setFitRange (double *fitrange)
Set range of fit.
Langaus & setStartValues (double *startValues)
Set start values (Landau sigma, Landau mean, Gaus sigma).
Langaus & setParlimitslo (double *parlimitslo)
Set low limits of parameters.
Langaus & setParlimitshi (double *parlimitshi)
Set high limits of parameters.
RooFFTConvPdf * getLangaus () const
Return RooFit object for function $(l\otimes g)(x)$ computed via Fast Fourier transformation.
RooNumConvPdf * getLangausNum () const
Return RooFit object for function $(l\otimes g)(x)$ computed numericaly.
RooAbsReal * getLangausBase () const
Return RooFit object for function $(l\otimes g)(x)$ without regarding on computation type.
Langaus & setData (TH1 *h)
Obtain datas from histogram.
RooDataHist * getData ()
Get data object created with setData.
double findPeak ()
Find peak position.
double findPeak (const double *par)
Find peak position for given parameters.
double findePeak ()
Calculate error of peak position $A(x|\rho)$, where $\rho$ are parameters of function.
RooFitResult * Fit ()
Get RooFitResult object by fitting of RooDataHist.
void langaufit (const TH1 *h, double *fitparams, double *fiterrors, double &peak, double &epeak)
Make whole fit of dataset with numerical finding of peak position and propagated error estimation.
double getCorrelation (const char *par1, const char *par2)
Obtain fit correlation factors between parameters (Landau mean, Landau sigma, Gaus sigma) obtained by fit.
Private Attributes
bool _useFFT
const double * _fitrange
range of fit
const double * _startValues
starting values
const double * _parlimitslo
low limit of parameters
const double * _parlimitshi
high limit of parameters
double _peak
position of most probable value
double _ePeak
error of most probable value
double _logL
$ -\log(L)$, where L is a likelihood function
RooRealVar * _t
RooRealVar * _mg
RooRealVar * _sg
RooRealVar * _ml
RooRealVar * _sl
RooLandau * _landau
RooGaussian * _gauss
RooFFTConvPdf * _lxg
RooNumConvPdf * _lxgNum
RooDataHist * _data
RooArgSet * _var
RooFitResult * _r
double _mlerror
double _slerror
double _sgerror
Static Private Attributes
static int FFT_CACHE = 50000
Sampling of fit range for Fast Fourier transformation (number of points used for computation of function).
static float NUM_RATIO = 0.01
Precision of finding peak by number given like ratio of width of `binning` to range of fit for direct numerical computation.
static int NUM_SAMPLING = 1000
Sampling of interval, where is iterative finding peak.
static float EPS_REL = 0.0000001
Precision of numerical computation of convolution integral.
static float EPS_ABS = 0.0000001
Precision of numerical computation of convolution integral.
Detailed Description
Class for handling with a fitting function defined as $ (l\otimes g)(x)=\int_{-\infty}^{\infty}\mbox{d}y\ l(x-y)\cdot g(y)$, where $l(x)$ is a Landau function and $ g(x)$ is a Gaus function. Detailed description follows here.
Author
Boris Bulanek, DESY
Date
June 2010
Definition at line 37 of file Langaus.hh.
Constructor & Destructor Documentation
Langaus::Langaus (const double * fitrange, const double * startValues, const double * parlimitslo, const double * parlimitshi, bool useFFT)
Constructor (Initialization of range, initial parameters, low and high limits of parameters).
See also
_fitrange
_startValues
_parlimitslo
_parlimitshi
Definition at line 10 of file Langaus.cc.
References _ePeak, _fitrange, _parlimitshi, _parlimitslo, _peak, _startValues, _useFFT, EPS_ABS, and EPS_REL.
Member Function Documentation
double Langaus::findePeak ()
Calculate error of peak position $A(x|\rho)$, where $\rho$ are parameters of function. The error is calculated with the formula $ \sigma^2_{peak}=\sum_{i,j} \frac{dA(x=peak|\rho)}{d\rho_i} \mbox{cor}(\rho_i,\rho_j)\cdot {\sigma_{\rho}}_i\cdot{\sigma_{\rho}}_j \frac{dA(x=peak|\rho)}{d\rho_j}$. The correlation factors $\mbox{cor}(\rho_i,\rho_j)$ are obtained by fit.
See also
getCorrelation(const char*, const char*)
Definition at line 234 of file Langaus.cc.
References _ePeak, _peak, and findPeak().
Referenced by langaufit().
double Langaus::findPeak (const double * par)
Find peak position for given parameters. Precision of finding the peak position is given by number of points in Fast Fourier transformation (FFT) and by ratio of width of `binning` to range of fit for direct numerical computation. The number of points for FFT can be adjusted by setFFTCache and ratio by setNumRatio.
Parameters
par - pointer to array of three parameters: par[0]=Landau mean, par[1]=Landau sigma, par[2]=Gaus sigma
Definition at line 157 of file Langaus.cc.
References _useFFT, NUM_RATIO, and NUM_SAMPLING.
double Langaus::findPeak ()
Find peak position.
Definition at line 95 of file Langaus.cc.
References _peak, _useFFT, FFT_CACHE, NUM_RATIO, and NUM_SAMPLING.
Referenced by findePeak(), and langaufit().
RooFitResult * Langaus::Fit (void)
Get RooFitResult object by fitting of RooDataHist.
Definition at line 304 of file Langaus.cc.
References _fitrange, _logL, and _useFFT.
Referenced by langaufit().
double Langaus::getCorrelation (const char * par1, const char * par2)
Obtain fit correlation factors between parameters (Landau mean, Landau sigma, Gaus sigma) obtained by fit.
Parameters
par1,par2 - parameters of fitting function given as: `ml`(Landau mean), `sl`(Landau sigma), `sg`(Gaus sigma).
Returns
Correlation between parameters given as inputs. If inputs are wrong, return value is 0.
Definition at line 349 of file Langaus.cc.
RooDataHist * Langaus::getData ()
Get data object created with setData.
Definition at line 81 of file Langaus.cc.
void Langaus::langaufit (const TH1 * h, double * fitparams, double * fiterrors, double & peak, double & epeak)
Make whole fit of dataset with numerical finding of peak position and propagated error estimation.
See also
findPeak()
Fit()
Parameters
h - fitted histogram
fitparams - found parameters: Landau sigma, Landau mean, Gaus sigma
fiterrors - found errors of fitparams
peak - found peak position.
epeak - found error of peak position. 100000, numerical calculation: 0.00001)
Definition at line 320 of file Langaus.cc.
References FFT_CACHE, findePeak(), findPeak(), Fit(), and setData().
Langaus & Langaus::setData (TH1 * h)
Obtain datas from histogram.
Definition at line 73 of file Langaus.cc.
Referenced by langaufit().
Field Documentation
const double* Langaus::_fitrange [private]
range of fit $\left<\mbox{\_fitrange[0]},\mbox{\_fitrange[1]}\right>$
Definition at line 163 of file Langaus.hh.
Referenced by Fit(), Langaus(), and setFitRange().
const double* Langaus::_parlimitshi [private]
high limit of parameters (Landau sigma, Landau mean, Gaus sigma)
Definition at line 173 of file Langaus.hh.
Referenced by Langaus(), and setParlimitshi().
const double* Langaus::_parlimitslo [private]
low limit of parameters (Landau sigma, Landau mean, Gaus sigma)
Definition at line 170 of file Langaus.hh.
Referenced by Langaus(), and setParlimitslo().
const double* Langaus::_startValues [private]
starting values (Landau sigma, Landau mean, Gaus sigma)
Definition at line 167 of file Langaus.hh.
Referenced by Langaus(), and setStartValues().
bool Langaus::_useFFT [private]
Set the method of convolution function computing (Fast Fourier transformation, Numerical computation)
Definition at line 160 of file Langaus.hh.
Referenced by findPeak(), Fit(), getLangausBase(), and Langaus().
float Langaus::EPS_ABS = 0.0000001 [static, private]
Precision of numerical computation of convolution integral. precision for numerical computation of convolution integral
(Not documented in RooFit.)
Definition at line 157 of file Langaus.hh.
Referenced by Langaus().
float Langaus::EPS_REL = 0.0000001 [static, private]
Precision of numerical computation of convolution integral. precision for numerical computation of convolution integral
(Not documented in RooFit.)
Definition at line 155 of file Langaus.hh.
Referenced by Langaus().
int Langaus::FFT_CACHE = 50000 [static, private]
Sampling of fit range for Fast Fourier transformation (number of points used for computation of function). cache for discrete fourier transformation
Definition at line 147 of file Langaus.hh.
Referenced by findPeak(), and langaufit().
float Langaus::NUM_RATIO = 0.01 [static, private]
Precision of finding peak by number given like ratio of width of `binning` to range of fit for direct numerical computation.
Definition at line 150 of file Langaus.hh.
Referenced by findPeak().
int Langaus::NUM_SAMPLING = 1000 [static, private]
Sampling of interval, where is iterative finding peak.
Definition at line 152 of file Langaus.hh.
Referenced by findPeak().
The documentation for this class was generated from the following files:
Langaus.hh
fitMIP.cc
Langaus.cc