CALICE::FeTrgData Class Reference
Stores the trigger history (i.e.
#include <FeTrgData.hh>Inheritance diagram for CALICE::FeTrgData::
Public Member Functions
FeTrgData (unsigned int board_id)
UsefulConstructor.
FeTrgData (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
FeTrgData & setBoardID (int boardID)
set the packed board id.
int getBoardID () const
Get the board id.
FeTrgData & setRecordLabel (int label)
set the record label.
int getRecordLabel () const
get the record label
FeTrgData & setHeaderWord (int header)
The header which comes along with the CrcVlinkTrgData.
int getHeaderWord () const
Get the header word.
FeTrgData & setTrailerWord (int trailer)
The trailer which comes along with the CrcVlinkTrgData.
int getTrailerWord () const
Get the trailer word.
FeTrgData & setTriggerCounter (int trigcount)
Set the trigger counter (=trigger number).
int getTriggerCounter () const
Get the trigger number.
FeTrgData & setFifoWord (unsigned int word_index, unsigned int word)
Set the fifo word.
FeTrgData & setAllFifoWords (unsigned int n_words, const unsigned int *const word_list)
Set all the fifo words.
int getNFifoWords () const
Get the number of words contained in the fifo.
int getFifoWord (unsigned int word_index) const
Get a fifo word.
IntVec & getFifoWords (IntVec &dest) const
Get a fifo word.
void print (std::ostream &os)
Convenient print method.
const std::string getTypeName () const
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Stores the trigger history (i.e. fifo content).when it appears in the front end as realized for runs starting in May 2006 (Ask Paul for firmware version) in older versions of the DAQ these data came along wiith the BeTrgEventData which still contains information related to the data handled by the present interface class.
To acces the configuration:
   void processEvent(LCEvent *event) {
       try {
        // string _colName = "BeTrgEventData"
        LCCollection *col=event->getCollection(_colName);
        for (unsigned int element_i=0; element_i<col->getNumberOfElements(); element_i++) {
           BeTrgEvent event(col->getElementAt(element_i));
        }
   }
Author
R. Pöschl (LAL Orsay)
Date
Jul 2006
Definition at line 56 of file FeTrgData.hh.
Constructor & Destructor Documentation
CALICE::FeTrgData::FeTrgData (unsigned int board_id) [inline]
UsefulConstructor.
Parameters
board_id the packed board id (CALICE::BoardID).
Definition at line 64 of file FeTrgData.hh.
References setBoardID(), setHeaderWord(), setRecordLabel(), setTrailerWord(), and setTriggerCounter().
Member Function Documentation
int CALICE::FeTrgData::getFifoWord (unsigned int word_index) const [inline]
Get a fifo word.
Parameters
word_index of the word in the fifo.
Definition at line 156 of file FeTrgData.hh.
References getNFifoWords().
Referenced by getFifoWords(), and print().
IntVec& CALICE::FeTrgData::getFifoWords (IntVec & dest) const [inline]
Get a fifo word.
Parameters
dest reference to a vector of integers whiich will be cleared in filled with the contents of the fifo.
Returns
for convenience a reference to the filled vector (i.e. is the one given as argument).
NOTE: Unless a vector is needed to pass the data to some function, it is adviced to get the individual values with getFifoWord() since this avoids copying (On the other hand, each access has the penalty of a virtual function call, so in some cases it might be advantages to make a copy which will allow faster element acces in subsequent calls.)
Definition at line 177 of file FeTrgData.hh.
References getFifoWord(), and getNFifoWords().
FeTrgData& CALICE::FeTrgData::setAllFifoWords (unsigned int n_words, const unsigned int *const word_list) [inline]
Set all the fifo words.
Parameters
n_words the number of words in the fifo.
word_list a pointer to the fifo words.
Definition at line 137 of file FeTrgData.hh.
References CALICE::LCGenericObjectImplExt::obj().
FeTrgData& CALICE::FeTrgData::setBoardID (int boardID) [inline]
set the packed board id.
See also
BoardID
Definition at line 87 of file FeTrgData.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by FeTrgData().
FeTrgData& CALICE::FeTrgData::setFifoWord (unsigned int word_index, unsigned int word) [inline]
Set the fifo word. Remmeber the fifo contains the -trigger history-
Parameters
word_index of the word in the fifo.
word the value of the word.
Definition at line 130 of file FeTrgData.hh.
References CALICE::LCGenericObjectImplExt::obj().
FeTrgData& CALICE::FeTrgData::setRecordLabel (int label) [inline]
set the record label.
Definition at line 93 of file FeTrgData.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by FeTrgData().
The documentation for this class was generated from the following file:
FeTrgData.hh