CALICE::FastDecoder Class Reference
decode IDs with encoding string
#include <FastDecoder.hh>
Public Member Functions
int decode (const int input) const
decode signed
unsigned int decodeU (const int input) const
decode unsigned
int encode (const int value) const
encode signed
int encodeU (const unsigned int value) const
encode signed
Static Public Member Functions
static FastDecoder * generateDecoder (const std::string &encodingString, const std::string &variableName)
function to generate a specific decoder for one variable
Private Member Functions
FastDecoder (const unsigned int position, const unsigned int mask, const bool isSigned, const int offset)
Private Attributes
unsigned int _position
unsigned int _mask
bool _isSigned
int _offset
Detailed Description
decode IDs with encoding string This class decodes a single value from a CELL ID. In differs to the LCIO::BitField in two ways.
interpretation of Y-n
If the encoding string contains a variable name in the form of $ name\pm N $, $ N $ is interpreted as offset to variable $ name $. It will be subsracted automatically. Example: If encodingstring is `K-1:3,I:3,J:3` and variable name is `K`, $ value+1 $ will be returned.
no string comparison in decoding
All necessary string comparison is done during the initialisation. This should give some performance increase, if the same decoder is used many times.
The constructor is private. Use the FastDecoder::generateDecoder() function to get an object.
Author
Benjamin.Lutz@desy.de
Date
April 2009
Definition at line 28 of file FastDecoder.hh.
Member Function Documentation
int CALICE::FastDecoder::decode (const int input) const [inline]
decode signed
Parameters
$\leftarrow$ input ID to be interpreted
Returns
value of the variable
Exceptions
WrongDataFormatException if called for an unsigned variable
Definition at line 43 of file FastDecoder.hh.
unsigned int CALICE::FastDecoder::decodeU (const int input) const [inline]
decode unsigned
Parameters
$\leftarrow$ input ID to be interpreted
Returns
value of the variable
Exceptions
WrongDataFormatException if called for a signed variable
Definition at line 53 of file FastDecoder.hh.
Referenced by CALICE::DecoderSet::getChannelFromDAQID(), CALICE::DecoderSet::getChannelFromModuleID(), CALICE::DecoderSet::getChipFromDAQID(), CALICE::DecoderSet::getChipFromModuleID(), CALICE::DecoderSet::getCrateFromDAQID(), CALICE::DecoderSet::getFeFromDAQID(), CALICE::DecoderSet::getIFromCellID(), CALICE::DecoderSet::getJFromCellID(), CALICE::DecoderSet::getKFromCellID(), CALICE::DecoderSet::getModuleFromModuleID(), CALICE::DecoderSet::getSlotFromDAQID(), and CALICE::TcmtEventIdentifier::process().
int CALICE::FastDecoder::encode (const int value) const [inline]
encode signed
Parameters
$\leftarrow$ value to encode
Returns
ID with value set
Exceptions
WrongDataFormatException if called for an unsigned variable
Definition at line 63 of file FastDecoder.hh.
int CALICE::FastDecoder::encodeU (const unsigned int value) const [inline]
encode signed
Parameters
$\leftarrow$ value to encode
Returns
ID with value set
Exceptions
WrongDataFormatException if called for an unsigned variable
Definition at line 73 of file FastDecoder.hh.
Referenced by CALICE::DecoderSet::getCellID(), CALICE::DecoderSet::getDAQID(), and CALICE::DecoderSet::getModuleID().
FastDecoder * CALICE::FastDecoder::generateDecoder (const std::string & encodingString, const std::string & variableName) [static]
function to generate a specific decoder for one variable
Parameters
$\leftarrow$ encodingString encoding string used to interprete the input
$\leftarrow$ variableName variable the encoder should extract
Returns
decoder for specific string and variable
Definition at line 10 of file FastDecoder.cc.
Referenced by CALICE::TcmtEventIdentifier::process(), CALICE::DecoderSet::setCellIDEncoding(), CALICE::DecoderSet::setDAQEncoding(), and CALICE::DecoderSet::setModuleEncoding().
The documentation for this class was generated from the following files:
FastDecoder.hh
FastDecoder.cc