CALICE::BinnedVector< K, D > Class Template Reference
Template class to store data via a linear binned keys.
#include <BinnedVector.hh>
Public Member Functions
BinnedVector ()
standard constructor
BinnedVector (const unsigned int N, const K &minRange, const K &maxRange, const D &initValue)
constructor which sets dimensions
void setBinning (const unsigned int N, const K &minRange, const K &maxRange, const D &initValue)
function to set the dimensions
D & operator[] (const K &position)
access operator
const D & operator[] (const K &position) const
const access operator
void clear ()
clear content of bins
const std::vector< D > & getVector () const
get vector of bins
std::vector< K > getBinCenters () const
get vector of bin centers
Private Member Functions
unsigned int getIndex (const K &position) const
Private Attributes
K _binWidth
K _minRange
K _maxRange
unsigned int _N
std::vector< D > _data
D _default
Detailed Description
template<class K, class D> class CALICE::BinnedVector< K, D >
Template class to store data via a linear binned keys. This is like a histogram, but without graphical functionallity.
Parameters
K type of the key
D type of the data
Author
Benjamin.Lutz@desy.de
Version
0.2
Date
October 2009
Definition at line 24 of file BinnedVector.hh.
Constructor & Destructor Documentation
template<class K , class D > CALICE::BinnedVector< K, D >::BinnedVector () [inline]
standard constructor
Warning
Dimensions have to be set with setBinning() before the vector can be used.
Definition at line 103 of file BinnedVector.hh.
template<class K, class D> CALICE::BinnedVector< K, D >::BinnedVector (const unsigned int N, const K & minRange, const K & maxRange, const D & initValue) [inline]
constructor which sets dimensions
Parameters
N number bins (without under and over range bins)
minRange lower end of range
maxRange upper end of range
initValue value for initialisation of bins
Definition at line 107 of file BinnedVector.hh.
References CALICE::BinnedVector< K, D >::setBinning().
Member Function Documentation
template<class K , class D > void CALICE::BinnedVector< K, D >::clear () [inline]
clear content of bins all bins will be set to initValue
Definition at line 112 of file BinnedVector.hh.
Referenced by CALICE::BinnedVector< K, D >::setBinning().
template<class K , class D > std::vector< K > CALICE::BinnedVector< K, D >::getBinCenters () const [inline]
get vector of bin centers the vector starts with the under range bin and ends with the over range bin
Returns
vector of bin centers
Definition at line 158 of file BinnedVector.hh.
template<class K, class D> const std::vector<D>& CALICE::BinnedVector< K, D >::getVector () const [inline]
get vector of bins the vector starts with the under range bin and ends with the over range bin
Returns
vector of bins
Definition at line 78 of file BinnedVector.hh.
Referenced by CALICE::TcmtEventIdentifier::addResults(), and CALICE::TcmtEventIdentifier::process().
template<class K, class D > const D & CALICE::BinnedVector< K, D >::operator[] (const K & position) const [inline]
const access operator
Parameters
position key to find bin
Returns
value at key
Definition at line 153 of file BinnedVector.hh.
template<class K, class D > D & CALICE::BinnedVector< K, D >::operator[] (const K & position) [inline]
access operator
Parameters
position key to find bin
Returns
value at key
Definition at line 148 of file BinnedVector.hh.
template<class K, class D> void CALICE::BinnedVector< K, D >::setBinning (const unsigned int N, const K & minRange, const K & maxRange, const D & initValue) [inline]
function to set the dimensions
Parameters
N number bins (without under and over range bins)
minRange lower end of range
maxRange upper end of range
initValue value for initialisation of bins
Definition at line 120 of file BinnedVector.hh.
References CALICE::BinnedVector< K, D >::clear().
Referenced by CALICE::BinnedVector< K, D >::BinnedVector(), and CALICE::TcmtEventIdentifier::TcmtEventIdentifier().
The documentation for this class was generated from the following file:
BinnedVector.hh