CALICE::TrgReadoutConfigurationBlock Class Reference
Stores the general readout configuration.
#include <TrgReadoutConfigurationBlock.hh>Inheritance diagram for CALICE::TrgReadoutConfigurationBlock::
Public Member Functions
TrgReadoutConfigurationBlock ()
Default Constructor.
TrgReadoutConfigurationBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
TrgReadoutConfigurationBlock & setEnable (int enable)
Set the enable of TrgReadConfiguration, i.e i.e.
int getEnable () const
Get the enable value.
TrgReadoutConfigurationBlock & setClearBeTrg (int clearbetrg)
Set the clear BeTrig indicator Note this a some of the following values are only bools so the setting of an integer is a wast of memory but anyway.
int getClearBeTrg () const
Get the clear BeTrg indicator.
TrgReadoutConfigurationBlock & setBeTrgSoftTrg (int betrgsofttrg)
Set the beTrgSoftTrg indicator.
int getBeTrgSoftTrg () const
Get the beTrgSoftTrg indicator.
TrgReadoutConfigurationBlock & setBeTrgSoftSpill (int betrgsoftspl)
Set the beTrg soft spill indicator.
int getBeTrgSoftSpill () const
Get the betrg soft spill indicator.
TrgReadoutConfigurationBlock & setBeTrgSquirt (int betrgsquirt)
Set the beTrg squirt indicator.
int getBeTrgSquirt () const
Get the beTrg squirt indicator.
TrgReadoutConfigurationBlock & setBeTrgVlink (int betrgvlink)
Set the beTrg Vlink indicator.
int getBeTrgVlink () const
Get the beTrg Vlink indicator.
TrgReadoutConfigurationBlock & setSpillInvert (int spillinvert)
Set the spill Invert indicator.
int getSpillInvert () const
Get the spill invert indicator.
TrgReadoutConfigurationBlock & setReadPeriod (int readperiod)
Set the read period.
int getReadPeriod () const
Get the read period.
TrgReadoutConfigurationBlock & setReadCounterPeriod (int readcperiod)
Set the readc period.
int getReadCounterPeriod () const
Get the readc period.
TrgReadoutConfigurationBlock & setBeTrgPollNumber (int betrgpollnum)
Set the BeTrg Pollnumber.
int getBeTrgPollNumber () const
Get the BeTrg Poll Number.
TrgReadoutConfigurationBlock & setBeTrgPollTime (int betrgpolltimesec, int betrgpolltimemus)
Set the BetrgPoll time.
int getBeTrgPollTimeSec () const
Get the BeTrgPoll time Sec.Part.
int getBeTrgPollTimeMus () const
Get the BeTrgPoll time mus.Part.
TrgReadoutConfigurationBlock & setBeTrgSpillNumber (int betrgspillnum)
Set the BeTrgSpill number.
int getBeTrgSpillNumber () const
Get the BeTrgSpill number.
TrgReadoutConfigurationBlock & setBeTrgSpillTime (int betrgspilltimesec, int betrgspilltimemus)
Set the BeTrgSpill time.
int getBeTrgSpillTimeSec () const
Get the BeTrgSpill time Sec.
int getBeTrgSpillTimeMus () const
Get the BeTrgSpill time Mus.
std::ostream & print (std::ostream &ostrm)
Convenient print method.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Stores the general readout configuration. e.g. to decide whether a softtrigger was -generally- enabled in contrast to the CrcReadoutConfiguration where the condig per board is given In addition information about general hardware configuration and run-conditions related items can be retrieved.
See also
ConditionsChangeDelegator
Author
R. Poeschl LAL (based on the other interface classes)
Date
Jul 2006
Definition at line 46 of file TrgReadoutConfigurationBlock.hh.
Member Function Documentation
int CALICE::TrgReadoutConfigurationBlock::getBeTrgSpillTimeMus () const [inline]
Get the BeTrgSpill time Mus. Part
Definition at line 235 of file TrgReadoutConfigurationBlock.hh.
Referenced by print().
int CALICE::TrgReadoutConfigurationBlock::getBeTrgSpillTimeSec () const [inline]
Get the BeTrgSpill time Sec. Part
Definition at line 230 of file TrgReadoutConfigurationBlock.hh.
Referenced by print().
std::ostream& CALICE::TrgReadoutConfigurationBlock::print (std::ostream & ostrm) [inline]
Convenient print method. dumps data content
Definition at line 243 of file TrgReadoutConfigurationBlock.hh.
References getBeTrgPollNumber(), getBeTrgPollTimeMus(), getBeTrgPollTimeSec(), getBeTrgSoftSpill(), getBeTrgSoftTrg(), getBeTrgSpillNumber(), getBeTrgSpillTimeMus(), getBeTrgSpillTimeSec(), getBeTrgSquirt(), getBeTrgVlink(), getClearBeTrg(), getEnable(), getReadCounterPeriod(), getReadPeriod(), and getSpillInvert().
TrgReadoutConfigurationBlock& CALICE::TrgReadoutConfigurationBlock::setEnable (int enable) [inline]
Set the enable of TrgReadConfiguration, i.e i.e. to decide whether the parameters here were active (?)
Definition at line 62 of file TrgReadoutConfigurationBlock.hh.
References CALICE::LCGenericObjectImplExt::obj().
The documentation for this class was generated from the following file:
TrgReadoutConfigurationBlock.hh