CALICE::FeInfo Class Reference
Stores the configuration data of the front-end of one CERC board.
#include <FeInfo.hh>
Public Member Functions
FeInfo (int boardID)
Convenient c'tor.
int getBoardID () const
Get the Crc Board ID.
FeInfo (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
FeInfo & setLabel (int label)
Set the fe link label(?).
int getLabel () const
Get the Fe link label(?).
FeInfo & setFeID (int fe_id)
Set the front-end id.
int getFeID () const
Get the front-end id.
FeInfo & setFrameSyncOut (int sync_words_01, int sync_words_23, int sync_word_4)
Set the four frame sync out half words.
int getFrameSyncOut (int word_i) const
Get the frame sync out half words.
FeInfo & setFeLength (int fe_length)
Set the fe length field (?).
int getFeLength () const
Get the fe length field (?).
FeInfo & setBeStatus (int be_status)
Set the back-end status word.
int getBeStatus () const
Get the back-end status word.
FeInfo & setTriggerCounter (int trigger_counter)
Set the trigger counter.
int getTriggerCounter () const
Get the trigger counter.
FeInfo & setFifo (int fifo)
Set the fifo status, and the front-end id.
int getFifoFeID () const
Get the front-end id from the fifo status word.
int getFifoStatus () const
Get the fifo status (without front-end ID.
int getNumberOfFifoWords () const
Get number of words in the fifo.
bool isFifoFull () const
Check whether the fifo is full.
bool isFifoEmpty () const
Check whether the fifo is empty.
void print (std::ostream &os) const
Convenient print method.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Stores the configuration data of the front-end of one CERC board. Based on AdcBlock. This is just a copy of the Calice DAQ class CrcFeConfigurationData. Since I don't have a profound understanding of the meaning of its members the documentation is mostly missing or at least very poor.
Author
Götz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Definition at line 42 of file FeInfo.hh.
Constructor & Destructor Documentation
CALICE::FeInfo::FeInfo (int boardID) [inline]
Convenient c'tor.
Parameters
boardID Crc board ID (VME crate, slot, fe))
Definition at line 50 of file FeInfo.hh.
Member Function Documentation
int CALICE::FeInfo::getBeStatus () const [inline]
Get the back-end status word.
Todo needs better explanation.
Definition at line 163 of file FeInfo.hh.
Referenced by print().
int CALICE::FeInfo::getFeID () const [inline]
Get the front-end id. This field is redundant since the front-end id is also encoded in the board ID.
Definition at line 81 of file FeInfo.hh.
Referenced by print().
int CALICE::FeInfo::getFeLength () const [inline]
Get the fe length field (?).
Todo needs better explanation.
Definition at line 140 of file FeInfo.hh.
Referenced by print().
int CALICE::FeInfo::getFifoFeID () const [inline]
Get the front-end id from the fifo status word. If this front-end id does not match the result of getFeID then all the front-end data for this particular event is corrupt.
Definition at line 186 of file FeInfo.hh.
Referenced by print().
int CALICE::FeInfo::getFrameSyncOut (int word_i) const [inline]
Get the frame sync out half words.
Parameters
word_i the index of the word (valid range 0-4).
Returns
the specified 16 bit half word.
Definition at line 106 of file FeInfo.hh.
Referenced by print().
int CALICE::FeInfo::getLabel () const [inline]
Get the Fe link label(?).
Todo needs better explanation.
Definition at line 71 of file FeInfo.hh.
Referenced by print().
int CALICE::FeInfo::getTriggerCounter () const [inline]
Get the trigger counter. The trigger counter can be used to identify front-end data of the same event.
Definition at line 175 of file FeInfo.hh.
Referenced by print().
bool CALICE::FeInfo::isFifoEmpty () const [inline]
Check whether the fifo is empty.
Returns
true if the fifo is empty;
Definition at line 206 of file FeInfo.hh.
Referenced by print().
bool CALICE::FeInfo::isFifoFull () const [inline]
Check whether the fifo is full.
Returns
true if the fifo is full;
Definition at line 201 of file FeInfo.hh.
Referenced by print().
FeInfo& CALICE::FeInfo::setBeStatus (int be_status) [inline]
Set the back-end status word.
Todo needs better explanation.
Definition at line 149 of file FeInfo.hh.
FeInfo& CALICE::FeInfo::setFeID (int fe_id) [inline]
Set the front-end id. This field is redundant since the front-end id is also encoded in the board ID.
Definition at line 76 of file FeInfo.hh.
FeInfo& CALICE::FeInfo::setFeLength (int fe_length) [inline]
Set the fe length field (?).
Todo needs better explanation.
Definition at line 130 of file FeInfo.hh.
FeInfo& CALICE::FeInfo::setFifo (int fifo) [inline]
Set the fifo status, and the front-end id.
Parameters
fifo the packed word which contains the front-end id, and the fifo status (overflow/underflow bits, fifo words).
Definition at line 180 of file FeInfo.hh.
FeInfo& CALICE::FeInfo::setFrameSyncOut (int sync_words_01, int sync_words_23, int sync_word_4) [inline]
Set the four frame sync out half words.
Parameters
sync_words_01 the first and the second half word packed in one 32bit integer.
sync_words_23 the third and the forth half word packed in one 32bit integer.
sync_word_4 the fifth half word packed in the lower 16 bits of a 32bit integer.
The first word should be in the lower 16 bit of the first argument, the second word in the upper 16 bits of the first argument and so forth:
 sync_words_01= (word_0 & 0xffff) + ((word_1 & xffff)<<16);
Definition at line 95 of file FeInfo.hh.
FeInfo& CALICE::FeInfo::setLabel (int label) [inline]
Set the fe link label(?).
Todo needs better explanation.
Definition at line 66 of file FeInfo.hh.
FeInfo& CALICE::FeInfo::setTriggerCounter (int trigger_counter) [inline]
Set the trigger counter. The trigger counter can be used to identify front-end data of the same event.
Definition at line 170 of file FeInfo.hh.
The documentation for this class was generated from the following files:
FeInfo.hh
FeInfo.cc