CALICE::BeTrgEvent Class Reference
Stores the trigger event data.
#include <BeTrgEvent.hh>Inheritance diagram for CALICE::BeTrgEvent::
Public Member Functions
BeTrgEvent (unsigned int board_id)
UsefulConstructor.
BeTrgEvent (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
BeTrgEvent & setBoardID (int boardID)
set the packed board id.
int getBoardID () const
Information on the FE chip the data was received.
BeTrgEvent & setInputStatus (int input_status)
Set the pre busy trigger counter (what ever that is ;-).
int getInputStatus () const
Get the input status.
BeTrgEvent & setInputCatch (int input_catch)
Set the input catch (what ever that is ;-).
int getInputCatch () const
Get the input catch (what ever that is ;-).
BeTrgEvent & setPreBusyCatch (int prebusy_catch)
Set the trigger busy status.
int getPrebusyCatch () const
Get the prebusy Catch.
BeTrgEvent & setSignalCatch (int signal_catch)
Set the signal Catch.
int getSignalCatch () const
Get the signal Catch.
BeTrgEvent & setControl (int control)
Set the contrl value.
int getControl () const
Get the control value.
BeTrgEvent & setInitialFifoStatus (int initial_fifo_status)
Set the inital fifo status.
int getInitialFifoStatus () const
Get the initial fifo status.
BeTrgEvent & setFinalFifoStatus (int final_fifo_status)
Set the final fifo status.
int getFinalFifoStatus () const
Get the final fifo status.
BeTrgEvent & setFifoWord (unsigned int word_index, unsigned int word)
Set the fifo word.
BeTrgEvent & setAllFifoWords (unsigned int n_words, const unsigned int *const word_list)
Set all the fifo words.
int getNFifoWords () const
Get the number of words contained in the fifo.
int getFifoWord (unsigned int word_index) const
Get a fifo word.
IntVec & getFifoWords (IntVec &dest) const
Get a fifo word.
BeTrgEvent & setTriggerCounter (int trigger_counter)
Set the trigger counter.
int getTriggerCounter () const
Get the trigger counter.
BeTrgEvent & setPreBusyTriggerCounter (int prebusy_counter)
Set the prebusy Trigger counter.
int getPreBusyTriggerCounter () const
Get the prebusy trigger counter.
void print (std::ostream &os)
Convenient print method.
const std::string getTypeName () const
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Stores the trigger event data. To acces the configuration:
   void processEvent(LCEvent *event) {
       try {
        // string _colName = "BeTrgEventData"
        LCCollection *col=event->getCollection(_colName);
        for (unsigned int element_i=0; element_i<col->getNumberOfElements(); element_i++) {
           BeTrgEvent event(col->getElementAt(element_i));
        }
   }
See also
ConditionsChangeDelegator
Author
Götz Gaycken LLR (Ecole Polytechnique)
Date
Sep 2005
Definition at line 74 of file BeTrgEvent.hh.
Constructor & Destructor Documentation
CALICE::BeTrgEvent::BeTrgEvent (unsigned int board_id) [inline]
UsefulConstructor.
Parameters
board_id the packed board id (CALICE::BoardID).
Definition at line 82 of file BeTrgEvent.hh.
References setBoardID().
Member Function Documentation
int CALICE::BeTrgEvent::getFifoWord (unsigned int word_index) const [inline]
Get a fifo word.
Parameters
word_index of the word in the fifo
Definition at line 225 of file BeTrgEvent.hh.
References getNFifoWords().
Referenced by getFifoWords(), and print().
IntVec& CALICE::BeTrgEvent::getFifoWords (IntVec & dest) const [inline]
Get a fifo word.
Parameters
dest reference to a vector of integers which will be cleared in filled with the contents of the fifo
Returns
for convenience a reference to the filled vector (i.e. is the one given as argument).
NOTE: Unless a vector is needed to pass the data to some function, it is adviced to get the individual values with getFifoWord() since this avoids copying (On the other hand, each access has the penalty of a virtual function call, so in some cases it might be advantages to make a copy which will allow faster element acces in subsequent calls.)
Definition at line 246 of file BeTrgEvent.hh.
References getFifoWord(), and getNFifoWords().
BeTrgEvent& CALICE::BeTrgEvent::setAllFifoWords (unsigned int n_words, const unsigned int *const word_list) [inline]
Set all the fifo words.
Parameters
n_words the number of words in the fifo.
word_list a pointer to the fifo words.
Definition at line 206 of file BeTrgEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
BeTrgEvent& CALICE::BeTrgEvent::setBoardID (int boardID) [inline]
set the packed board id.
See also
BoardID
Definition at line 98 of file BeTrgEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by BeTrgEvent().
BeTrgEvent& CALICE::BeTrgEvent::setFifoWord (unsigned int word_index, unsigned int word) [inline]
Set the fifo word.
Parameters
word_index of the word in the fifo.
word the value of the word.
Definition at line 199 of file BeTrgEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
BeTrgEvent& CALICE::BeTrgEvent::setInputStatus (int input_status) [inline]
Set the pre busy trigger counter (what ever that is ;-). Get the pre busy trigger counter (what ever that is ;-). Set the trigger counter. Get the trigger counter. Set the input status.
Definition at line 124 of file BeTrgEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
BeTrgEvent& CALICE::BeTrgEvent::setPreBusyCatch (int prebusy_catch) [inline]
Set the trigger busy status. Get the trigger busy status. Set the prebusy Catch.
Definition at line 151 of file BeTrgEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
The documentation for this class was generated from the following file:
BeTrgEvent.hh