CALICE::FeEvent Class Reference
Stores the trigger history (i.e.
#include <FeEvent.hh>Inheritance diagram for CALICE::FeEvent::
Public Member Functions
FeEvent ()
Simple Constructor.
FeEvent (unsigned int board_id)
UsefulConstructor.
FeEvent (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
FeEvent & setBoardID (int boardID)
Set the packed board id.
int getBoardID () const
Get the board id.
FeEvent & setRecordLabel (int label)
Set the Record Label.
short getRecordLabel () const
Return the Record Label.
FeEvent & setTriggerCounter (int trigger_counter)
Set the trigger counter.
int getTriggerCounter () const
Get the Trigger Counter.
FeEvent & setSpyRegister (int spyregister)
Set the Spy Register Value (Whatever this is .
int getSpyRegister () const
Get the Spy Register Value.
void print (std::ostream &os) const
Convenient print method.
const std::string getTypeName () const
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Stores the trigger history (i.e. fifo content).when it appears in the front end as realized for runs starting in May 2006 (Ask Paul for firmware version) in older versions of the DAQ these data came along wiith the BeTrgEventData which still contains information related to the data handled by the present interface class.
To acces the configuration:
   void processEvent(LCEvent *event) {
       try {
        // string _colName = "BeTrgEventData"
        LCCollection *col=event->getCollection(_colName);
        for (unsigned int element_i=0; element_i<col->getNumberOfElements(); element_i++) {
           FeEvent event(col->getElementAt(element_i));
        }
   }
Author
R. Pöschl (LAL Orsay)
Date
Jul 2006
Definition at line 53 of file FeEvent.hh.
Constructor & Destructor Documentation
CALICE::FeEvent::FeEvent (unsigned int board_id) [inline]
UsefulConstructor.
Parameters
board_id the packed board id (CALICE::BoardID).
Definition at line 72 of file FeEvent.hh.
References setBoardID(), setRecordLabel(), setSpyRegister(), and setTriggerCounter().
Member Function Documentation
FeEvent& CALICE::FeEvent::setBoardID (int boardID) [inline]
Set the packed board id.
See also
BoardID
Definition at line 91 of file FeEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by FeEvent().
FeEvent& CALICE::FeEvent::setSpyRegister (int spyregister) [inline]
Set the Spy Register Value (Whatever this is . ...
Definition at line 118 of file FeEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by FeEvent().
The documentation for this class was generated from the following files:
FeEvent.hh
FeEvent.cc