CALICE::TempGainConstants Class Reference
= class GainConstants but with temperature
#include <TempGainConstants.hh>Inheritance diagram for CALICE::TempGainConstants::
Public Member Functions
TempGainConstants ()
constructor
TempGainConstants (unsigned chip, unsigned channel, float value, float error, float gainTemp, float gainTempError, float Tslope, float TslopeError)
constructor, initialised by parameters
TempGainConstants (LCObject *obj)
void setCellTemp (float tempValue, float tempError)
set cell temperature
float getCorrGain () const
get temperature-corrected gain
float getCorrGainError () const
get uncertainty on temperature-corrected gain
float getCellTemp () const
get cell temperature
float getCellTempError () const
get cell temperature uncertainty
void setGainTemp (float value, float error)
set gain temperature
float getGainTemp () const
get gain temperature
float getGainTempError () const
get gain temperature uncertainty
void setTslope (float value, float error)
set temperature slope
float getTslope () const
get temperature slope
float getTslopeError () const
get temperature slope uncertainty
float applyCalibration (float inputValue) const
apply gain calibration to input value
float cancelCalibration (float outputValue) const
cancel an applied calibration from energy value
float applyCalibrationError (float inputValue, float inputError) const
apply calibration error to current error
float cancelCalibrationError (float outputValue, float outputError) const
apply error due to canceling a calibration to current error
bool calibrationValid () const
check if a valid gain calibration is available
void print (std::ostream &os)
convenient print method
const std::string getTypeName () const
return type of the class
const std::string getDataDescription () const
return a brief description of the data member
Private Attributes
float cellTemp
float cellTempError
float corrGain
float corrGainError
Detailed Description
= class GainConstants but with temperature
Author
S. Schaetzel DESY
Date
Apr 26 2007
Definition at line 23 of file TempGainConstants.hh.
Constructor & Destructor Documentation
CALICE::TempGainConstants::TempGainConstants (unsigned chip, unsigned channel, float value, float error, float gainTemp, float gainTempError, float Tslope, float TslopeError) [inline]
constructor, initialised by parameters
Parameters
chip chip number of the channel calibrated
channel channel number of the channel calibrated
value gain value of the cannel calibrated
error error on the gain value of the cannel calibrated
gainTemp temperature for which the gain was determined
gainTempError uncertainty of temperature for which the gain was determined
Tslope temperature slope of gain (dG/dT) in ADC ch./K
TslopeError uncertainty of temperature slope of gain (dG/dT) in ADC ch./K
Definition at line 44 of file TempGainConstants.hh.
References CALICE::LCHcalCalibrationObject::obj().
Member Function Documentation
float CALICE::TempGainConstants::applyCalibration (float inputValue) const [inline, virtual]
apply gain calibration to input value
Parameters
inputValue SiPM amplitude in ADC ch.
Returns
SiPM amplitude in pixels
Reimplemented from CALICE::GainConstants .
Definition at line 141 of file TempGainConstants.hh.
Referenced by applyCalibrationError().
float CALICE::TempGainConstants::applyCalibrationError (float inputValue, float inputError) const [inline, virtual]
apply calibration error to current error
Parameters
inputValue SiPM amplitude in ADC ch.
inputError SiPM amplitude error in ADC ch.
Returns
error of SiPM amplitude in pixels
Reimplemented from CALICE::GainConstants .
Definition at line 156 of file TempGainConstants.hh.
References applyCalibration().
bool CALICE::TempGainConstants::calibrationValid () const [inline, virtual]
check if a valid gain calibration is available
Returns
true if the gain value is a valid number
Reimplemented from CALICE::GainConstants .
Definition at line 168 of file TempGainConstants.hh.
References CALICE::GainConstants::calibrationValid().
The documentation for this class was generated from the following files:
TempGainConstants.hh
TempGainConstants.cc