CALICE::LCGenericObjectImplExt Class Reference
Extends functionality of the LCGenericObjectImpl Class It simply adds a new constructor to the LCGenericObject Class such that we can construct an interface class around without being restricted by the LCFixedObject It uses an instance of LCGenericObjectImpl that holds the data, thus there is no overhead when the data is read from a database or file for copying it to some local structure (Decorator pattern).
#include <LCGenericObjectImplExt.hh>Inheritance diagram for CALICE::LCGenericObjectImplExt::
Public Member Functions
LCGenericObjectImplExt ()
Default c'tor.
LCGenericObjectImplExt (LCObject *obj)
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~LCGenericObjectImplExt ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
Protected Attributes
LCGenericObjectImpl * _obj
bool _createdObject
Detailed Description
Extends functionality of the LCGenericObjectImpl Class It simply adds a new constructor to the LCGenericObject Class such that we can construct an interface class around without being restricted by the LCFixedObject It uses an instance of LCGenericObjectImpl that holds the data, thus there is no overhead when the data is read from a database or file for copying it to some local structure (Decorator pattern).
 This is still an abstract class: subclasses have to implement LCGenericObj ect::getTypeName() and LCGenericObject::getDataDescription(). It is basically a copy of the lcio::UTIL::LCFixedObject class I don't know whether this is the best solution, maybe it is better to use later on a real extension of the LCGenericObjectImpl
Author
Roman Poeschl, LAL Orsay
Date
Feb. 2006
Definition at line 30 of file LCGenericObjectImplExt.hh.
Member Function Documentation
LCGenericObjectImpl* CALICE::LCGenericObjectImplExt::obj () [inline]
The LCGenericObjectImpl . Sublcasses use this to access their data.
Definition at line 74 of file LCGenericObjectImplExt.hh.
Referenced by CALICE::AcquisitionData::AcquisitionData(), CALICE::BmlEventData::addTDCChannels(), CALICE::AhcVfeConfigurationBlock::AhcVfeConfigurationBlock(), CALICE::BeTrgConf::BeTrgConf(), CALICE::BeTrgPollData::BeTrgPollData(), CALICE::FeConfigurationBlock::clearCalibEnable(), CALICE::FeConfigurationBlock::clearHoldInvert(), CALICE::DhcRawChipContent::DhcRawChipContent(), CALICE::DhcReadoutConfBlock::DhcReadoutConfBlock(), CALICE::FeConfigurationBlock::FeConfigurationBlock(), CALICE::DhcReadoutConfBlock::fillMethod(), CALICE::DhcReadoutConfBlock::fillSlotToWordsAssociationMask(), CALICE::DaqTypeDataBlock::finalize(), CALICE::AcquisitionData::getAcquisitionNumberInConfiguration(), CALICE::AcquisitionData::getAcquisitionNumberInRun(), CALICE::AcquisitionData::getActAcquisitionTimeMus(), CALICE::AcquisitionData::getActAcquisitionTimeSec(), CALICE::AcquisitionData::getActEventNumberInAcquisition(), CALICE::BeTrgPollData::getEndTime(), CALICE::EventHeader::getEventNumberInAcquisition(), CALICE::EventHeader::getEventNumberInConfiguration(), CALICE::EventHeader::getEventNumberInRun(), CALICE::AcquisitionData::getMaxAcquisitionTimeMus(), CALICE::AcquisitionData::getMaxAcquisitionTimeSec(), CALICE::AcquisitionData::getMaxEventNumberInAcquisition(), CALICE::BeTrgPollData::getMaximumTimeMus(), CALICE::BeTrgPollData::getMaximumTimeSec(), CALICE::BeTrgPollData::getNumberOfPolls(), CALICE::AhcVfeConfigurationBlock::getShiftRegisterData(), CALICE::BeTrgPollData::getStartTime(), CALICE::ScintCaloSlowReadoutModBlock::getTimeStamp(), CALICE::AhcVfeConfigurationBlock::getVerificationData(), CALICE::BeTrgPollData::isTimeout(), CALICE::DaqTypeDataBlock::RestoreMaps(), CALICE::BmlSlowRunDataBlock::setAbsorberPosition(), CALICE::AcquisitionData::setAcquisitionState(), CALICE::FeConfigurationBlock::setAdcControlBits(), CALICE::FeConfigurationBlock::setAdcDelay(), CALICE::FeConfigurationBlock::setAdcEnd(), CALICE::FeConfigurationBlock::setAdcStart(), CALICE::FeTrgData::setAllFifoWords(), CALICE::BeTrgEvent::setAllFifoWords(), CALICE::BeTrgConf::setAndEnable(), CALICE::BmlEventData::setBaseAddress(), CALICE::BeamParameterException::setBeamEnergy(), CALICE::ReadOutConfigurationBlock::setBecPeriod(), CALICE::ReadOutConfigurationBlock::setBePeriod(), CALICE::ReadOutConfigurationBlock::setBeSoftTrigger(), CALICE::TrgReadoutConfigurationBlock::setBeTrgPollNumber(), CALICE::TrgReadoutConfigurationBlock::setBeTrgPollTime(), CALICE::TrgReadoutConfigurationBlock::setBeTrgSoftSpill(), CALICE::TrgReadoutConfigurationBlock::setBeTrgSoftTrg(), CALICE::TrgReadoutConfigurationBlock::setBeTrgSpillNumber(), CALICE::TrgReadoutConfigurationBlock::setBeTrgSpillTime(), CALICE::TrgReadoutConfigurationBlock::setBeTrgSquirt(), CALICE::TrgReadoutConfigurationBlock::setBeTrgVlink(), CALICE::DhcReadoutConfBlock::setBeWaitInterval(), CALICE::FeConfigurationBlock::setBoardComponentNumber(), CALICE::AhcVfeConfigurationBlock::setBoardComponentNumber(), CALICE::FeTrgData::setBoardID(), CALICE::FeEvent::setBoardID(), CALICE::FeConfigurationBlock::setBoardID(), CALICE::BmlEventData::setBoardID(), CALICE::BeTrgPollData::setBoardID(), CALICE::BeTrgEvent::setBoardID(), CALICE::BeTrgConf::setBoardID(), CALICE::BeEvent::setBoardID(), CALICE::AhcVfeConfigurationBlock::setBoardID(), CALICE::BmlCaen767ReadoutConfigurationBlock::setBools(), CALICE::BmlEventDataSup::setBufferOverflow(), CALICE::BmlEventDataSup::setBunchID(), CALICE::BeTrgConf::setBurstCounter(), CALICE::BeTrgConf::setBurstTimeout(), CALICE::BeTrgConf::setBusyTimeout(), CALICE::BeEvent::setBxCounter(), CALICE::FeConfigurationBlock::setCalibEnable(), CALICE::FeConfigurationBlock::setCalibStart(), CALICE::FeConfigurationBlock::setCalibWidth(), CALICE::EmcStageDataBlock::setCheckSum(), CALICE::TrgReadoutConfigurationBlock::setClearBeTrg(), CALICE::ScintCaloSlowReadoutModBlock::setCmbHeight(), CALICE::ScintCaloSlowReadoutModBlock::setCmbWidth(), CALICE::BeTrgConf::setConfiguration(), CALICE::ReadOutConfigurationBlock::setConfMode(), CALICE::BeTrgEvent::setControl(), CALICE::ReadOutConfigurationBlock::setCrateID(), CALICE::FeConfigurationBlock::setCrateID(), CALICE::AhcVfeConfigurationBlock::setCrateID(), CALICE::DhcRawChipContent::setCrateNumber(), CALICE::BmlCaen767ReadoutConfigurationBlock::setCrateNumber(), CALICE::FeConfigurationBlock::setDacData(), CALICE::ScintCaloSlowReadoutModBlock::setDblArrays(), CALICE::BmlSlowRunDataBlock::setDblArrays(), CALICE::DhcRawChipContent::setDhcTimeStamp(), CALICE::AcquisitionData::setDifInfoPresent(), CALICE::AcquisitionData::setDifTriggerCounter(), CALICE::DhcRawChipContent::setElecChannel(), CALICE::FeConfigurationBlock::setEmcVfeInfo(), CALICE::TrgReadoutConfigurationBlock::setEnable(), CALICE::BeTrgPollData::setEndTime(), CALICE::BmlEventData::setEventDataCounter(), CALICE::BmlEventDataSup::setEventFifoCont(), CALICE::BmlEventDataSup::setEventIDTrailer(), CALICE::BmlEventData::setEventNumber(), CALICE::EventHeader::setEventNumberInAcquisition(), CALICE::EventHeader::setEventNumberInConfiguration(), CALICE::AcquisitionData::setEventNumberInfo(), CALICE::EventHeader::setEventNumberInRun(), CALICE::BeTrgConf::setExtBeamMode(), CALICE::ReadOutConfigurationBlock::setFeBrcSoftTrigger(), CALICE::ReadOutConfigurationBlock::setFePeriod(), CALICE::ReadOutConfigurationBlock::setFeSlotEnable(), CALICE::ReadOutConfigurationBlock::setFeSoftTrigger(), CALICE::BeTrgConf::setFifoIdleDepth(), CALICE::FeTrgData::setFifoWord(), CALICE::BeTrgEvent::setFifoWord(), CALICE::BeTrgEvent::setFinalFifoStatus(), CALICE::FeConfigurationBlock::setFrameSyncDelay(), CALICE::BeTrgConf::setGeneralEnable(), CALICE::BmlEventData::setGeoAddress(), CALICE::EmcStageDataBlock::setHeader(), CALICE::FeTrgData::setHeaderWord(), CALICE::DhcRawChipContent::setHitsHi(), CALICE::DhcRawChipContent::setHitsLo(), CALICE::FeConfigurationBlock::setHoldInvert(), CALICE::FeConfigurationBlock::setHoldStart(), CALICE::BeTrgEvent::setInitialFifoStatus(), CALICE::BeTrgEvent::setInputCatch(), CALICE::BeTrgConf::setInputEnableMask(), CALICE::BeTrgConf::setInputInvert(), CALICE::BeTrgEvent::setInputStatus(), CALICE::BeEvent::setL1aCounter(), CALICE::ScintCaloSlowReadoutModBlock::setLedSetting(), CALICE::DaqTypeDataBlock::setLengthIndexOfDblTypeNames(), CALICE::DaqTypeDataBlock::setLengthIndexOfFloatTypeNames(), CALICE::DaqTypeDataBlock::setLengthIndexOfIntTypeNames(), CALICE::DaqTypeDataBlock::setLengthIndexOfTimeStampNames(), CALICE::BeTrgPollData::setMaximumTime(), CALICE::DhcRawChipContent::setMiscInfo(), CALICE::BmlCaen767ReadoutConfigurationBlock::setMode(), CALICE::ScintCaloSlowReadoutModBlock::setModuleNumber(), CALICE::DaqRunSummaryBlock::setNumberOfAcquisitions(), CALICE::DaqRunSummaryBlock::setNumberOfConfigurations(), CALICE::DaqTypeDataBlock::setNumberOfDblTypes(), CALICE::AcquisitionData::setNumberofDifBufferWords(), CALICE::DaqRunSummaryBlock::setNumberOfEvents(), CALICE::DaqTypeDataBlock::setNumberOfFloatTypes(), CALICE::DaqTypeDataBlock::setNumberOfIntTypes(), CALICE::BeTrgPollData::setNumberOfPolls(), CALICE::BmlEventData::setNumberOfSignalChannels(), CALICE::DhcReadoutConfBlock::setNumberOfSlots(), CALICE::DaqRunSummaryBlock::setNumberOfSlowReadouts(), CALICE::DaqTypeDataBlock::setNumberOfTimeStamps(), CALICE::BmlEventData::setNumberOfWords(), CALICE::DhcReadoutConfBlock::setNumbers(), CALICE::ScintCaloSlowReadoutModBlock::setNumPos(), CALICE::BmlSlowRunDataBlock::setNumPos(), CALICE::BeTrgConf::setOscillationPeriod(), CALICE::BeTrgConf::setOscillatorEnable(), CALICE::DaqTypeDataBlock::setPointerToIndexOfDblTypeNames(), CALICE::DaqTypeDataBlock::setPointerToIndexOfFloatTypeNames(), CALICE::DaqTypeDataBlock::setPointerToIndexOfIntTypeNames(), CALICE::DaqTypeDataBlock::setPointerToIndexOfTimeStampNames(), CALICE::BeTrgEvent::setPreBusyCatch(), CALICE::BeTrgEvent::setPreBusyTriggerCounter(), CALICE::BeTrgConf::setQdrConfiguration(), CALICE::BeEvent::setQdrDataCounter(), CALICE::BeEvent::setQdrFrameCounter(), CALICE::TrgReadoutConfigurationBlock::setReadCounterPeriod(), CALICE::TrgReadoutConfigurationBlock::setReadPeriod(), CALICE::BmlCaen767ReadoutConfigurationBlock::setReadPeriod(), CALICE::FeTrgData::setRecordLabel(), CALICE::FeEvent::setRecordLabel(), CALICE::FeConfigurationBlock::setRecordLabel(), CALICE::BmlEventData::setRecordLabel(), CALICE::BeTrgPollData::setRecordLabel(), CALICE::BeTrgConf::setRecordLabel(), CALICE::BeEvent::setRecordLabel(), CALICE::AhcVfeConfigurationBlock::setRecordLabel(), CALICE::DaqRunSummaryBlock::setRunDuration(), CALICE::RunLocation::setRunLocationParameters(), CALICE::DaqRunSummaryBlock::setRunNumber(), CALICE::BeTrgConf::setSequencerControl(), CALICE::AhcVfeConfigurationBlock::setShiftRegisterData(), CALICE::BeTrgEvent::setSignalCatch(), CALICE::DaqTypeDataBlock::setSizeIndexOfDblType(), CALICE::DaqTypeDataBlock::setSizeIndexOfFloatType(), CALICE::DaqTypeDataBlock::setSizeIndexOfIntType(), CALICE::ReadOutConfigurationBlock::setSlotEnable(), CALICE::DhcReadoutConfBlock::setSlotEnable(), CALICE::DhcReadoutConfBlock::setSlotEnableMask(), CALICE::FeConfigurationBlock::setSlotID(), CALICE::AhcVfeConfigurationBlock::setSlotID(), CALICE::TrgReadoutConfigurationBlock::setSpillInvert(), CALICE::FeEvent::setSpyRegister(), CALICE::BeTrgPollData::setStartTime(), CALICE::BmlEventData::setStatus(), CALICE::BmlEventData::setStatusRegister(), CALICE::BeEvent::setStatusWord(), CALICE::BmlSlowRunDataBlock::setT4Position(), CALICE::BmlSlowRunDataBlock::setTargetPosition(), CALICE::BmlEventDataSup::setTDCErrors(), CALICE::BmlEventDataSup::setTDCType(), CALICE::BmlEventDataSup::setTDCWordCountTrailer(), CALICE::HodoscopeEventDataBlock::setTimeCounter(), CALICE::AcquisitionData::setTimeInformationMuSec(), CALICE::AcquisitionData::setTimeInformationSec(), CALICE::BeTrgPollData::setTimeout(), CALICE::ScintCaloSlowReadoutModBlock::setTimeStamp(), CALICE::BmlSlowRunDataBlock::setTimeStamp(), CALICE::BeEvent::setTotalFrameCounter(), CALICE::FeTrgData::setTrailerWord(), CALICE::FeTrgData::setTriggerCounter(), CALICE::FeEvent::setTriggerCounter(), CALICE::DifTrigger::setTriggerCounter(), CALICE::BeTrgEvent::setTriggerCounter(), CALICE::BmlEventDataSup::setTriggerLost(), CALICE::DaqTypeDataBlock::setTypeIndex(), CALICE::BmlEventDataSup::setTypeIndex(), CALICE::AhcVfeConfigurationBlock::setVerificationData(), CALICE::FeConfigurationBlock::setVfeInfo(), CALICE::FeConfigurationBlock::setVfeResetEnd(), CALICE::FeConfigurationBlock::setVfeResetStart(), CALICE::FeConfigurationBlock::setVfeSrinStart(), CALICE::ReadOutConfigurationBlock::setVmePeriod(), CALICE::EmcStageDataBlock::setXYStatus(), and CALICE::EmcStageDataBlock::setXYValues().
The documentation for this class was generated from the following file:
LCGenericObjectImplExt.hh