Functions for (Mokka) cell ID
Data Structures
class CALICE::CellIterator
iterator to run over all valid (Mokka) cell IDs
Functions
int CALICE::Ahc2Mapper::getCellIDFromModChipChan (const unsigned int module, const unsigned int chip, const unsigned int channel) const
generate (Mokka) cellID from module, chip, channel
unsigned int CALICE::Ahc2Mapper::getModuleFromCellID (const int cellID) const
module number from (Mokka) CellID
unsigned int CALICE::Ahc2Mapper::getModuleFromCellID (const int cellID, bool &valid) const
get module (number) in which this cell is included from (Mokka) cellID
unsigned int CALICE::Ahc2Mapper::getChipFromCellID (const int cellID) const
chip number from (Mokka) CellID
unsigned int CALICE::Ahc2Mapper::getChanFromCellID (const int cellID) const
channel number from (Mokka) CellID
unsigned int CALICE::Ahc2Mapper::getCrateFromCellID (const int cellID) const
crate number from (Mokka) CellID
unsigned int CALICE::Ahc2Mapper::getSlotFromCellID (const int cellID) const
slot number from (Mokka) CellID
unsigned int CALICE::Ahc2Mapper::getFeFromCellID (const int cellID) const
front end number from (Mokka) CellID
unsigned int CALICE::Ahc2Mapper::getISizeFromCellID (const int cellID) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int CALICE::Ahc2Mapper::getJSizeFromCellID (const int cellID) const
get cell size in J direction of (Mokka) CellID coordinate
int CALICE::AhcMapper::getCellIDFromModChipChan (const unsigned int module, const unsigned int chip, const unsigned int channel) const
generate (Mokka) cellID from module, chip, channel
unsigned int CALICE::AhcMapper::getModuleFromCellID (const int cellID) const
module number from (Mokka) CellID
unsigned int CALICE::AhcMapper::getModuleFromCellID (const int cellID, bool &valid) const
get module (number) in which this cell is included from (Mokka) cellID
unsigned int CALICE::AhcMapper::getChipFromCellID (const int cellID) const
chip number from (Mokka) CellID
unsigned int CALICE::AhcMapper::getChanFromCellID (const int cellID) const
channel number from (Mokka) CellID
unsigned int CALICE::AhcMapper::getCrateFromCellID (const int cellID) const
crate number from (Mokka) CellID
unsigned int CALICE::AhcMapper::getSlotFromCellID (const int cellID) const
slot number from (Mokka) CellID
unsigned int CALICE::AhcMapper::getFeFromCellID (const int cellID) const
front end number from (Mokka) CellID
unsigned int CALICE::AhcMapper::getISizeFromCellID (const int cellID) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int CALICE::AhcMapper::getJSizeFromCellID (const int cellID) const
get cell size in J direction of (Mokka) CellID coordinate
void CALICE::DecoderSet::setCellIDEncoding (const std::string &encoding)
set a new cell ID encoding string if an empty string is given the function will use the default encoding string
const std::string & CALICE::DecoderSet::getCellIDEncoding () const
get the current cell ID encoding string
unsigned int CALICE::DecoderSet::getIFromCellID (const int cellID) const
get I from (Mokka) CellID The right encoding string has to be set before.
unsigned int CALICE::DecoderSet::getJFromCellID (const int cellID) const
get J from (Mokka) CellID The right encoding string has to be set before.
unsigned int CALICE::DecoderSet::getKFromCellID (const int cellID) const
get K from (Mokka) CellID The right encoding string has to be set before.
int CALICE::DecoderSet::getCellID (const unsigned int I, const unsigned int J, const unsigned int K) const
get CellID from triple I,J,K
virtual unsigned int CALICE::Mapper::getModuleFromCellID (const int cellID) const =0
get module (number) in which this cell is included from (Mokka) cellID
virtual unsigned int CALICE::Mapper::getModuleFromCellID (const int cellID, bool &valid) const =0
get module (number) in which this cell is included from (Mokka) cellID
virtual unsigned int CALICE::Mapper::getISizeFromCellID (const int cellID) const =0
get cell size in I direction of (Mokka) CellID coordinate
virtual unsigned int CALICE::Mapper::getJSizeFromCellID (const int cellID) const =0
get cell size in J direction of (Mokka) CellID coordinate
CellIterator CALICE::Mapper::begin () const
get an iterator to the first (Mokka) cell ID
CellIterator CALICE::Mapper::end () const
get an iterator one after the last (Mokka) cell ID
virtual unsigned int CALICE::Mapper::getIndexByCellID (const int cellID) const =0
get a compact index for storing data in vectors
virtual int CALICE::Mapper::getCellIDOfIndex (unsigned int index) const =0
get the cell ID of a certain compact index
Function Documentation
CellIterator CALICE::Mapper::begin () const [inherited]
get an iterator to the first (Mokka) cell ID
Returns
iterator
Definition at line 16 of file Mapper.cc.
Referenced by CALICE::CellNeighbourCalculator::getNeighbours().
CellIterator CALICE::Mapper::end () const [inherited]
get an iterator one after the last (Mokka) cell ID
Returns
iterator
Definition at line 20 of file Mapper.cc.
References CALICE::Mapper::getMaxIndex().
Referenced by CALICE::CellNeighbourCalculator::getNeighbours().
int CALICE::DecoderSet::getCellID (const unsigned int I, const unsigned int J, const unsigned int K) const [inline, inherited]
get CellID from triple I,J,K The right encoding string has to be set before.
Warning
This cell ID will only contain information about I, J and K. If the encoding string contains additional fields this will have value 0.
See also
setCellIDencoding
Parameters
$\leftarrow$ I I of cell
$\leftarrow$ J J of cell
$\leftarrow$ K K of cell
Returns
(Mokka) cell ID
Definition at line 226 of file DecoderSet.hh.
References CALICE::FastDecoder::encodeU().
Referenced by CALICE::AhcMapper::getCellIDFromModChipChan(), CALICE::Ahc2Mapper::getCellIDFromModChipChan(), CALICE::AhcMapper::getCellIDOfIndex(), CALICE::Ahc2Mapper::getCellIDOfIndex(), CALICE::AhcMapper::getTrueCellID(), and CALICE::Ahc2Mapper::getTrueCellID().
const std::string& CALICE::DecoderSet::getCellIDEncoding () const [inline, inherited]
get the current cell ID encoding string
Returns
cell ID encoding string
Definition at line 84 of file DecoderSet.hh.
Referenced by CALICE::AhcMapper::getModule(), and CALICE::Ahc2Mapper::getModule().
int CALICE::AhcMapper::getCellIDFromModChipChan (const unsigned int module, const unsigned int chip, const unsigned int channel) const [inline, inherited]
generate (Mokka) cellID from module, chip, channel Translates module, chip, channel to (Mokka) CellID using the current encoding string.
Warning
only I,J,K will be set, possible additional variables will be 0
Parameters
$\leftarrow$ module module number
$\leftarrow$ chip chip number
$\leftarrow$ channel channel number
Returns
(Mokka) cell ID
Exceptions
BadDataException if lookup fails
Definition at line 73 of file AhcMapper.hh.
References CALICE::DecoderSet::getCellID(), CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getI(), CALICE::AhcMapper::getJ(), and CALICE::AhcMapper::getK().
int CALICE::Ahc2Mapper::getCellIDFromModChipChan (const unsigned int module, const unsigned int chip, const unsigned int channel) const [inline, inherited]
generate (Mokka) cellID from module, chip, channel Translates module, chip, channel to (Mokka) CellID using the current encoding string.
Warning
only I,J,K will be set, possible additional variables will be 0
Parameters
$\leftarrow$ module module number
$\leftarrow$ chip chip number
$\leftarrow$ channel channel number
Returns
(Mokka) cell ID
Exceptions
BadDataException if lookup fails
Definition at line 79 of file Ahc2Mapper.hh.
References CALICE::DecoderSet::getCellID(), CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getI(), CALICE::Ahc2Mapper::getJ(), and CALICE::Ahc2Mapper::getK().
virtual int CALICE::Mapper::getCellIDOfIndex (unsigned int index) const [protected, pure virtual, inherited]
get the cell ID of a certain compact index
Warning
This cell ID will only contain information about I, J and K. If the encoding string contains additional fields this will have value 0.
See also
setCellIDencoding
Returns
(Mokka) cell ID
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
Referenced by CALICE::CellIterator::operator++().
unsigned int CALICE::AhcMapper::getChanFromCellID (const int cellID) const [inline, inherited]
channel number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
channel number
Exceptions
BadDataException if lookup fails
Definition at line 241 of file AhcMapper.hh.
References CALICE::AhcMapper::getChan(), and CALICE::Mapper::getDecoder().
unsigned int CALICE::Ahc2Mapper::getChanFromCellID (const int cellID) const [inline, inherited]
channel number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
channel number
Exceptions
BadDataException if lookup fails
Definition at line 250 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getChan(), and CALICE::Mapper::getDecoder().
unsigned int CALICE::AhcMapper::getChipFromCellID (const int cellID) const [inline, inherited]
chip number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
chip number
Exceptions
BadDataException if lookup fails
Definition at line 205 of file AhcMapper.hh.
References CALICE::AhcMapper::getChip(), and CALICE::Mapper::getDecoder().
unsigned int CALICE::Ahc2Mapper::getChipFromCellID (const int cellID) const [inline, inherited]
chip number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
chip number
Exceptions
BadDataException if lookup fails
Definition at line 211 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getChip(), and CALICE::Mapper::getDecoder().
unsigned int CALICE::AhcMapper::getCrateFromCellID (const int cellID) const [inline, inherited]
crate number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
crate number
Exceptions
BadDataException if lookup fails
Definition at line 277 of file AhcMapper.hh.
References CALICE::AhcMapper::getCrate(), and CALICE::AhcMapper::getModuleFromCellID().
unsigned int CALICE::Ahc2Mapper::getCrateFromCellID (const int cellID) const [inline, inherited]
crate number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
crate number
Exceptions
BadDataException if lookup fails
Definition at line 286 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getCrate(), and CALICE::Ahc2Mapper::getModuleFromCellID().
unsigned int CALICE::AhcMapper::getFeFromCellID (const int cellID) const [inline, inherited]
front end number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
front end number
Exceptions
BadDataException if lookup fails
Definition at line 364 of file AhcMapper.hh.
References CALICE::AhcMapper::getFe(), and CALICE::AhcMapper::getModuleFromCellID().
unsigned int CALICE::Ahc2Mapper::getFeFromCellID (const int cellID) const [inline, inherited]
front end number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
front end number
Exceptions
BadDataException if lookup fails
Definition at line 373 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getFe(), and CALICE::Ahc2Mapper::getModuleFromCellID().
unsigned int CALICE::DecoderSet::getIFromCellID (const int cellID) const [inline, inherited]
get I from (Mokka) CellID The right encoding string has to be set before.
See also
setCellIDencoding
Parameters
$\leftarrow$ cellID cell ID to decode
Returns
I
Definition at line 109 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::CellDescriptionGenerator::generate(), CALICE::AhcMapper::getIndexByCellID(), and CALICE::Ahc2Mapper::getIndexByCellID().
virtual unsigned int CALICE::Mapper::getIndexByCellID (const int cellID) const [protected, pure virtual, inherited]
get a compact index for storing data in vectors
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
compact index
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
Referenced by CALICE::MappedContainer< T >::deleteByCellID(), CALICE::MappedContainer< T >::fillByCellID(), CALICE::MappedContainer< T >::getByCellID(), and CALICE::MappedContainer< T >::removeByCellID().
virtual unsigned int CALICE::Mapper::getISizeFromCellID (const int cellID) const [pure virtual, inherited]
get cell size in I direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
size in I
Exceptions
BadDataException if cell does not exist
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
unsigned int CALICE::AhcMapper::getISizeFromCellID (const int cellID) const [inline, virtual, inherited]
get cell size in I direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
size in I
Exceptions
BadDataException if lookup fails
Implements CALICE::Mapper .
Definition at line 549 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::AhcMapper::getISizeFromIJK().
unsigned int CALICE::Ahc2Mapper::getISizeFromCellID (const int cellID) const [inline, virtual, inherited]
get cell size in I direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
size in I
Exceptions
BadDataException if lookup fails
Implements CALICE::Mapper .
Definition at line 558 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::Ahc2Mapper::getISizeFromIJK().
unsigned int CALICE::DecoderSet::getJFromCellID (const int cellID) const [inline, inherited]
get J from (Mokka) CellID The right encoding string has to be set before.
See also
setCellIDencoding
Parameters
$\leftarrow$ cellID cell ID to decode
Returns
J
Definition at line 119 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::CellDescriptionGenerator::generate(), CALICE::AhcMapper::getIndexByCellID(), and CALICE::Ahc2Mapper::getIndexByCellID().
virtual unsigned int CALICE::Mapper::getJSizeFromCellID (const int cellID) const [pure virtual, inherited]
get cell size in J direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
size in J
Exceptions
BadDataException if cell does not exist
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
unsigned int CALICE::AhcMapper::getJSizeFromCellID (const int cellID) const [inline, virtual, inherited]
get cell size in J direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
size in J
Exceptions
BadDataException if lookup fails
Implements CALICE::Mapper .
Definition at line 627 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::AhcMapper::getJSizeFromIJK().
unsigned int CALICE::Ahc2Mapper::getJSizeFromCellID (const int cellID) const [inline, virtual, inherited]
get cell size in J direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
size in J
Exceptions
BadDataException if lookup fails
Implements CALICE::Mapper .
Definition at line 636 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::Ahc2Mapper::getJSizeFromIJK().
unsigned int CALICE::DecoderSet::getKFromCellID (const int cellID) const [inline, inherited]
get K from (Mokka) CellID The right encoding string has to be set before.
See also
setCellIDencoding
Parameters
$\leftarrow$ cellID cell ID to decode
Returns
K
Definition at line 129 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::CellDescriptionGenerator::generate(), CALICE::AhcMapper::getIndexByCellID(), and CALICE::Ahc2Mapper::getIndexByCellID().
virtual unsigned int CALICE::Mapper::getModuleFromCellID (const int cellID, bool & valid) const [pure virtual, inherited]
get module (number) in which this cell is included from (Mokka) cellID Checks if the cell ID exists. No exception is thrown.
Parameters
$\leftarrow$ cellID (Mokka) cell ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
virtual unsigned int CALICE::Mapper::getModuleFromCellID (const int cellID) const [pure virtual, inherited]
get module (number) in which this cell is included from (Mokka) cellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
module
Exceptions
BadDataException if some error is detected, but no full verification is performed
See also
getModuleFromCellID(const int cellID, bool &valid)
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
unsigned int CALICE::AhcMapper::getModuleFromCellID (const int cellID, bool & valid) const [inline, virtual, inherited]
get module (number) in which this cell is included from (Mokka) cellID Checks if the cell ID exists. No exception is thrown.
Parameters
$\leftarrow$ cellID (Mokka) cell ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implements CALICE::Mapper .
Definition at line 157 of file AhcMapper.hh.
References CALICE::AhcMapper::getIndexByCellID().
unsigned int CALICE::AhcMapper::getModuleFromCellID (const int cellID) const [inline, virtual, inherited]
module number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
module number
Exceptions
BadDataException if lookup fails
Implements CALICE::Mapper .
Definition at line 90 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::AhcMapper::getModule().
Referenced by CALICE::AhcMapper::getCrateFromCellID(), CALICE::AhcMapper::getFeFromCellID(), and CALICE::AhcMapper::getSlotFromCellID().
unsigned int CALICE::Ahc2Mapper::getModuleFromCellID (const int cellID, bool & valid) const [inline, virtual, inherited]
get module (number) in which this cell is included from (Mokka) cellID Checks if the cell ID exists. No exception is thrown.
Parameters
$\leftarrow$ cellID (Mokka) cell ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implements CALICE::Mapper .
Definition at line 163 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getIndexByCellID().
unsigned int CALICE::Ahc2Mapper::getModuleFromCellID (const int cellID) const [inline, virtual, inherited]
module number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
module number
Exceptions
BadDataException if lookup fails
Implements CALICE::Mapper .
Definition at line 96 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::Ahc2Mapper::getModule().
Referenced by CALICE::Ahc2Mapper::getCrateFromCellID(), CALICE::Ahc2Mapper::getFeFromCellID(), and CALICE::Ahc2Mapper::getSlotFromCellID().
unsigned int CALICE::AhcMapper::getSlotFromCellID (const int cellID) const [inline, inherited]
slot number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
slot number
Exceptions
BadDataException if lookup fails
Definition at line 320 of file AhcMapper.hh.
References CALICE::AhcMapper::getModuleFromCellID(), and CALICE::AhcMapper::getSlot().
unsigned int CALICE::Ahc2Mapper::getSlotFromCellID (const int cellID) const [inline, inherited]
slot number from (Mokka) CellID
Parameters
$\leftarrow$ cellID (Mokka) cell ID
Returns
slot number
Exceptions
BadDataException if lookup fails
Definition at line 329 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getModuleFromCellID(), and CALICE::Ahc2Mapper::getSlot().
void CALICE::DecoderSet::setCellIDEncoding (const std::string & encoding) [inherited]
set a new cell ID encoding string if an empty string is given the function will use the default encoding string
Parameters
$\leftarrow$ encoding encoding string
Definition at line 39 of file DecoderSet.cc.
References CALICE::FastDecoder::generateDecoder().
Referenced by CALICE::DecoderSet::DecoderSet().