Functions for Module channel ID
Functions
unsigned int CALICE::Ahc2Mapper::getModuleFromModuleID (const int moduleID, bool &valid) const
get module (number) from this (module) channel ID
unsigned int CALICE::Ahc2Mapper::getCrateFromModuleID (const int moduleID) const
crate number from Module cell ID
unsigned int CALICE::Ahc2Mapper::getSlotFromModuleID (const int moduleID) const
slot number from Module cell ID
unsigned int CALICE::Ahc2Mapper::getFeFromModuleID (const int moduleID) const
front end number from Module cell ID
unsigned int CALICE::Ahc2Mapper::getIFromModuleID (const int moduleID) const
I of (Mokka) cellID.
unsigned int CALICE::Ahc2Mapper::getJFromModuleID (const int moduleID) const
J of (Mokka) cellID.
unsigned int CALICE::Ahc2Mapper::getKFromModuleID (const int moduleID) const
K of (Mokka) cellID.
unsigned int CALICE::Ahc2Mapper::getISizeFromModuleID (const int moduleID) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int CALICE::Ahc2Mapper::getJSizeFromModuleID (const int moduleID) const
get cell size in J direction of (Mokka) CellID coordinate
unsigned int CALICE::AhcMapper::getModuleFromModuleID (const int moduleID, bool &valid) const
get module (number) from this (module) channel ID
unsigned int CALICE::AhcMapper::getCrateFromModuleID (const int moduleID) const
crate number from Module cell ID
unsigned int CALICE::AhcMapper::getSlotFromModuleID (const int moduleID) const
slot number from Module cell ID
unsigned int CALICE::AhcMapper::getFeFromModuleID (const int moduleID) const
front end number from Module cell ID
unsigned int CALICE::AhcMapper::getIFromModuleID (const int moduleID) const
I of (Mokka) cellID.
unsigned int CALICE::AhcMapper::getJFromModuleID (const int moduleID) const
J of (Mokka) cellID.
unsigned int CALICE::AhcMapper::getKFromModuleID (const int moduleID) const
K of (Mokka) cellID.
unsigned int CALICE::AhcMapper::getISizeFromModuleID (const int moduleID) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int CALICE::AhcMapper::getJSizeFromModuleID (const int moduleID) const
get cell size in J direction of (Mokka) CellID coordinate
void CALICE::DecoderSet::setModuleEncoding (const std::string &encoding)
set a new Module tile encoding string if an empty string is given the function will use the default encoding string
const std::string & CALICE::DecoderSet::getModuleEncoding () const
get the current Module tile encoding string
unsigned int CALICE::DecoderSet::getModuleFromModuleID (const int moduleID) const
get module from (Module) channel ID The right encoding string has to be set before.
unsigned int CALICE::DecoderSet::getChipFromModuleID (const int moduleID) const
get chip from (Module) channel ID The right encoding string has to be set before.
unsigned int CALICE::DecoderSet::getChannelFromModuleID (const int moduleID) const
get channel from (Module) channel ID The right encoding string has to be set before.
int CALICE::DecoderSet::getModuleID (const unsigned int module, const unsigned int chip, const unsigned int channel) const
get (Module) channel ID from triple module, chip, channel
virtual unsigned int CALICE::Mapper::getModuleFromModuleID (const int moduleID, bool &valid) const =0
get module (number) from this (module) channel ID
virtual unsigned int CALICE::Mapper::getIndexByModuleID (const int ID) const =0
get a compact index for storing data in vectors
Function Documentation
unsigned int CALICE::DecoderSet::getChannelFromModuleID (const int moduleID) const [inline, inherited]
get channel from (Module) channel ID The right encoding string has to be set before.
See also
setModuleEncoding
Parameters
$\leftarrow$ moduleID cell ID to decode
Returns
channel
Definition at line 159 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::AhcMapper::getIndexByModuleID(), and CALICE::Ahc2Mapper::getIndexByModuleID().
unsigned int CALICE::DecoderSet::getChipFromModuleID (const int moduleID) const [inline, inherited]
get chip from (Module) channel ID The right encoding string has to be set before.
See also
setModuleEncoding
Parameters
$\leftarrow$ moduleID cell ID to decode
Returns
module
Definition at line 149 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::AhcMapper::getIndexByModuleID(), and CALICE::Ahc2Mapper::getIndexByModuleID().
unsigned int CALICE::AhcMapper::getCrateFromModuleID (const int moduleID) const [inline, inherited]
crate number from Module cell ID
Parameters
$\leftarrow$ moduleID module cell ID
Returns
crate number
Exceptions
BadDataException if lookup fails
Definition at line 291 of file AhcMapper.hh.
References CALICE::AhcMapper::getCrate(), CALICE::Mapper::getDecoder(), and CALICE::AhcMapper::getModuleFromModuleID().
unsigned int CALICE::Ahc2Mapper::getCrateFromModuleID (const int moduleID) const [inline, inherited]
crate number from Module cell ID
Parameters
$\leftarrow$ moduleID module cell ID
Returns
crate number
Exceptions
BadDataException if lookup fails
Definition at line 300 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getCrate(), CALICE::Mapper::getDecoder(), and CALICE::Ahc2Mapper::getModuleFromModuleID().
unsigned int CALICE::AhcMapper::getFeFromModuleID (const int moduleID) const [inline, inherited]
front end number from Module cell ID
Parameters
$\leftarrow$ moduleID module cell ID
Returns
front end number
Exceptions
BadDataException if lookup fails
Definition at line 378 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getFe(), and CALICE::AhcMapper::getModuleFromModuleID().
unsigned int CALICE::Ahc2Mapper::getFeFromModuleID (const int moduleID) const [inline, inherited]
front end number from Module cell ID
Parameters
$\leftarrow$ moduleID module cell ID
Returns
front end number
Exceptions
BadDataException if lookup fails
Definition at line 387 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getFe(), and CALICE::Ahc2Mapper::getModuleFromModuleID().
unsigned int CALICE::AhcMapper::getIFromModuleID (const int moduleID) const [inline, inherited]
I of (Mokka) cellID.
Parameters
$\leftarrow$ moduleID module cell ID
Returns
I
Exceptions
BadDataException if lookup fails
Definition at line 407 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getI(), and CALICE::AhcMapper::getModuleFromModuleID().
unsigned int CALICE::Ahc2Mapper::getIFromModuleID (const int moduleID) const [inline, inherited]
I of (Mokka) cellID.
Parameters
$\leftarrow$ moduleID module cell ID
Returns
I
Exceptions
BadDataException if lookup fails
Definition at line 416 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getI(), and CALICE::Ahc2Mapper::getModuleFromModuleID().
virtual unsigned int CALICE::Mapper::getIndexByModuleID (const int ID) const [protected, pure virtual, inherited]
get a compact index for storing data in vectors
Parameters
$\leftarrow$ ID Module channel ID
Returns
compact index
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
Referenced by CALICE::MappedContainer< T >::deleteByModuleID(), CALICE::MappedContainer< T >::fillByModuleID(), CALICE::MappedContainer< T >::getByModuleID(), and CALICE::MappedContainer< T >::removeByModuleID().
unsigned int CALICE::AhcMapper::getISizeFromModuleID (const int moduleID) const [inline, inherited]
get cell size in I direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ moduleID module cell ID
Returns
size in I
Exceptions
BadDataException if lookup fails
Definition at line 563 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getISize(), and CALICE::AhcMapper::getModuleFromModuleID().
unsigned int CALICE::Ahc2Mapper::getISizeFromModuleID (const int moduleID) const [inline, inherited]
get cell size in I direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ moduleID module cell ID
Returns
size in I
Exceptions
BadDataException if lookup fails
Definition at line 572 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getISize(), and CALICE::Ahc2Mapper::getModuleFromModuleID().
unsigned int CALICE::AhcMapper::getJFromModuleID (const int moduleID) const [inline, inherited]
J of (Mokka) cellID.
Parameters
$\leftarrow$ moduleID module cell ID
Returns
J
Exceptions
BadDataException if lookup fails
Definition at line 456 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getJ(), and CALICE::AhcMapper::getModuleFromModuleID().
unsigned int CALICE::Ahc2Mapper::getJFromModuleID (const int moduleID) const [inline, inherited]
J of (Mokka) cellID.
Parameters
$\leftarrow$ moduleID module cell ID
Returns
J
Exceptions
BadDataException if lookup fails
Definition at line 465 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getJ(), and CALICE::Ahc2Mapper::getModuleFromModuleID().
unsigned int CALICE::AhcMapper::getJSizeFromModuleID (const int moduleID) const [inline, inherited]
get cell size in J direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ moduleID module cell ID
Returns
size in J
Exceptions
BadDataException if lookup fails
Definition at line 641 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getJSize(), and CALICE::AhcMapper::getModuleFromModuleID().
unsigned int CALICE::Ahc2Mapper::getJSizeFromModuleID (const int moduleID) const [inline, inherited]
get cell size in J direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ moduleID module cell ID
Returns
size in J
Exceptions
BadDataException if lookup fails
Definition at line 650 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getJSize(), and CALICE::Ahc2Mapper::getModuleFromModuleID().
unsigned int CALICE::AhcMapper::getKFromModuleID (const int moduleID) const [inline, inherited]
K of (Mokka) cellID.
Parameters
$\leftarrow$ moduleID module cell ID
Returns
K
Exceptions
BadDataException if lookup fails
Definition at line 505 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getK(), and CALICE::AhcMapper::getModuleFromModuleID().
unsigned int CALICE::Ahc2Mapper::getKFromModuleID (const int moduleID) const [inline, inherited]
K of (Mokka) cellID.
Parameters
$\leftarrow$ moduleID module cell ID
Returns
K
Exceptions
BadDataException if lookup fails
Definition at line 514 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getK(), and CALICE::Ahc2Mapper::getModuleFromModuleID().
const std::string& CALICE::DecoderSet::getModuleEncoding () const [inline, inherited]
get the current Module tile encoding string
Returns
module channel ID encoding string
Definition at line 91 of file DecoderSet.hh.
virtual unsigned int CALICE::Mapper::getModuleFromModuleID (const int moduleID, bool & valid) const [pure virtual, inherited]
get module (number) from this (module) channel ID Checks if the channel exists. No exception is thrown.
Parameters
$\leftarrow$ moduleID module channel ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
unsigned int CALICE::DecoderSet::getModuleFromModuleID (const int moduleID) const [inline, inherited]
get module from (Module) channel ID The right encoding string has to be set before.
See also
setModuleEncoding
Parameters
$\leftarrow$ moduleID cell ID to decode
Returns
module
Definition at line 139 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::AhcMapper::getIndexByModuleID(), and CALICE::Ahc2Mapper::getIndexByModuleID().
unsigned int CALICE::AhcMapper::getModuleFromModuleID (const int moduleID, bool & valid) const [inline, virtual, inherited]
get module (number) from this (module) channel ID Checks if the channel exists. No exception is thrown.
Parameters
$\leftarrow$ moduleID module channel ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implements CALICE::Mapper .
Definition at line 189 of file AhcMapper.hh.
References CALICE::AhcMapper::getIndexByModuleID().
Referenced by CALICE::AhcMapper::getCrateFromModuleID(), CALICE::AhcMapper::getFeFromModuleID(), CALICE::AhcMapper::getIFromModuleID(), CALICE::AhcMapper::getISizeFromModuleID(), CALICE::AhcMapper::getJFromModuleID(), CALICE::AhcMapper::getJSizeFromModuleID(), CALICE::AhcMapper::getKFromModuleID(), and CALICE::AhcMapper::getSlotFromModuleID().
unsigned int CALICE::Ahc2Mapper::getModuleFromModuleID (const int moduleID, bool & valid) const [inline, virtual, inherited]
get module (number) from this (module) channel ID Checks if the channel exists. No exception is thrown.
Parameters
$\leftarrow$ moduleID module channel ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implements CALICE::Mapper .
Definition at line 195 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getIndexByModuleID().
Referenced by CALICE::Ahc2Mapper::getCrateFromModuleID(), CALICE::Ahc2Mapper::getFeFromModuleID(), CALICE::Ahc2Mapper::getIFromModuleID(), CALICE::Ahc2Mapper::getISizeFromModuleID(), CALICE::Ahc2Mapper::getJFromModuleID(), CALICE::Ahc2Mapper::getJSizeFromModuleID(), CALICE::Ahc2Mapper::getKFromModuleID(), and CALICE::Ahc2Mapper::getSlotFromModuleID().
int CALICE::DecoderSet::getModuleID (const unsigned int module, const unsigned int chip, const unsigned int channel) const [inline, inherited]
get (Module) channel ID from triple module, chip, channel The right encoding string has to be set before.
Warning
This (Module) channel ID will only contain information about module, chip and channel. If the encoding string contains additional fields this will have value 0.
See also
setModuleEncoding
Parameters
$\leftarrow$ module module of this channel
$\leftarrow$ chip chip of this channel
$\leftarrow$ channel hardware channel of this channel
Returns
(Module) channel ID
Definition at line 245 of file DecoderSet.hh.
References CALICE::FastDecoder::encodeU().
unsigned int CALICE::AhcMapper::getSlotFromModuleID (const int moduleID) const [inline, inherited]
slot number from Module cell ID
Parameters
$\leftarrow$ moduleID module cell ID
Returns
slot number
Exceptions
BadDataException if lookup fails
Definition at line 334 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getModuleFromModuleID(), and CALICE::AhcMapper::getSlot().
unsigned int CALICE::Ahc2Mapper::getSlotFromModuleID (const int moduleID) const [inline, inherited]
slot number from Module cell ID
Parameters
$\leftarrow$ moduleID module cell ID
Returns
slot number
Exceptions
BadDataException if lookup fails
Definition at line 343 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getModuleFromModuleID(), and CALICE::Ahc2Mapper::getSlot().
void CALICE::DecoderSet::setModuleEncoding (const std::string & encoding) [inherited]
set a new Module tile encoding string if an empty string is given the function will use the default encoding string
Parameters
$\leftarrow$ encoding encoding string
Definition at line 64 of file DecoderSet.cc.
References CALICE::FastDecoder::generateDecoder().
Referenced by CALICE::DecoderSet::DecoderSet().