CALICE::LCHcalCalibrationObject Class Reference
Object to store information about arbitrary cell wise calibration of the HCAL in LC Objects.
#include <LCHcalCalibrationObject.hh>Inheritance diagram for CALICE::LCHcalCalibrationObject::
Public Member Functions
LCHcalCalibrationObject ()
Default c'tor.
LCHcalCalibrationObject (LCObject *obj)
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~LCHcalCalibrationObject ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
float getConstant ()
float getConstantError ()
void setConstant (float c)
void setConstantError (float ce)
unsigned getCellKey () const
get cell key of cell
void setCellKey (unsigned cellKey)
set cell key of cell
unsigned getChip () const
get chip number of cell
unsigned getChannel () const
get channel number of cell
virtual float applyCalibration (float inputValue) const
let the object apply the calibration stored in the object
virtual float cancelCalibration (float outputValue) const
cancel an applied calibration from energy value
virtual float applyCalibrationError (float inputValue, float inputError) const
let the object calculate the error after applying the calibration stored in the object
virtual float cancelCalibrationError (float outputValue, float outputError) const
apply error due to canceling a calibration to current error
virtual bool calibrationValid () const
is the calibration stored in the object valid?
virtual bool keepEvent (float resultValue, float resultError) const
should the cell been kept in the cell selection after the calibration has been performed?
virtual float getParam (unsigned paramIndex) const
virtual void setParam (unsigned paramIndex)
virtual void setCellTemp (float tempValue, float tempError)
virtual float getCellTemp ()
virtual float getCellTempError ()
const std::string getTypeName () const
return type of the class
const std::string getDataDescription () const
return a brief description of the data member
Protected Attributes
LCGenericObjectImpl * _obj
bool _createdObject
Detailed Description
Object to store information about arbitrary cell wise calibration of the HCAL in LC Objects.
Author
S. Schmidt DESY
Date
Jul 2006
Definition at line 20 of file LCHcalCalibrationObject.hh.
Member Function Documentation
virtual float CALICE::LCHcalCalibrationObject::applyCalibration (float inputValue) const [inline, virtual]
let the object apply the calibration stored in the object
Parameters
inputValue `energy` value of the cell before the calibration
Returns
`energy` value of the cell after the calibration
Reimplemented in CALICE::DeadNoiseConstants , CALICE::GainConstants , CALICE::InterConstants , CALICE::LCHcalCalibrationObject2D , CALICE::MIPConstants , CALICE::PedestalConstants , CALICE::TcmtSaturationConstants , and CALICE::TempGainConstants .
Definition at line 131 of file LCHcalCalibrationObject.hh.
virtual float CALICE::LCHcalCalibrationObject::applyCalibrationError (float inputValue, float inputError) const [inline, virtual]
let the object calculate the error after applying the calibration stored in the object
Parameters
inputValue `energy` value of the cell stored before the calibration
inputError error of the `energy` value of the cell before the calibration
Returns
error of the `energy` value of the cell after the calibration taking into account the error of the `energy` value of the cell before the calibration and the error of the calibration itself
Reimplemented in CALICE::DeadNoiseConstants , CALICE::GainConstants , CALICE::InterConstants , CALICE::LCHcalCalibrationObject2D , CALICE::MIPConstants , CALICE::PedestalConstants , CALICE::TcmtSaturationConstants , and CALICE::TempGainConstants .
Definition at line 148 of file LCHcalCalibrationObject.hh.
virtual bool CALICE::LCHcalCalibrationObject::calibrationValid () const [inline, virtual]
is the calibration stored in the object valid?
Returns
true if the calibration is valid, false if no valid calibration is available
Reimplemented in CALICE::DeadNoiseConstants , CALICE::GainConstants , CALICE::InterConstants , CALICE::MIPConstants , CALICE::PedestalConstants , CALICE::SaturationConstants , CALICE::TcmtSaturationConstants , and CALICE::TempGainConstants .
Definition at line 161 of file LCHcalCalibrationObject.hh.
virtual bool CALICE::LCHcalCalibrationObject::keepEvent (float resultValue, float resultError) const [inline, virtual]
should the cell been kept in the cell selection after the calibration has been performed?
Parameters
resultValue `energy` value of the cell after the calibration
resultError error on the `energy` value of the cell after the calibration
Reimplemented in CALICE::DeadNoiseConstants , CALICE::GainConstants , CALICE::InterConstants , CALICE::MIPConstants , CALICE::PedestalConstants , CALICE::SaturationConstants , and CALICE::TcmtSaturationConstants .
Definition at line 169 of file LCHcalCalibrationObject.hh.
LCGenericObjectImpl* CALICE::LCHcalCalibrationObject::obj () [inline]
The LCGenericObjectImpl . Sublcasses use this to access their data.
Definition at line 64 of file LCHcalCalibrationObject.hh.
Referenced by CALICE::DeadNoiseConstants::DeadNoiseConstants(), CALICE::GainConstants::GainConstants(), CALICE::TempGainConstants::setGainTemp(), CALICE::TempGainConstants::setTslope(), and CALICE::TempGainConstants::TempGainConstants().
The documentation for this class was generated from the following file:
LCHcalCalibrationObject.hh