CALICE::FeConfigurationBlock Class Reference
Stores the configuration data of the front-end of one CERC board.
#include <FeConfigurationBlock.hh>Inheritance diagram for CALICE::FeConfigurationBlock::
Public Types
enum EFlags { kFlagsCalibEnable = 1,
kFlagsHoldInvert = 2
 }
Public Member Functions
FeConfigurationBlock (int boardID)
Convenient c'tor.
FeConfigurationBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
FeConfigurationBlock & setCrateID (short crateID)
Set the crate ID.
short getCrateID () const
Get the crate ID.
FeConfigurationBlock & setSlotID (short slotID)
Set the slot ID.
short getSlotID () const
Get the slot ID.
FeConfigurationBlock & setBoardComponentNumber (short componentNumber)
Set the Boardcomponentnumber.
short getBoardComponentNumber () const
Get the Boardcomponentnumber.
void setRecordLabel (int label)
Set the RecordLabel, i.e.
short getRecordLabel () const
Get the record label.
FeConfigurationBlock & setBoardID (int boardID)
Set the boardID composed by crate, slot and component number.
int getBoardID () const
Get the boardID.
FeConfigurationBlock & setCalibStart (int calibStart)
Set Calibration pulse start value.
int getCalibStart ()
Get calibration pulse start value.
FeConfigurationBlock & setCalibWidth (int calibWidth)
Set duration of the calibration pulse.
int getCalibWidth ()
Get duration of the calibration pulse.
FeConfigurationBlock & setCalibEnable (bool calib_enable)
Se the calib enable value ????
FeConfigurationBlock & setCalibEnable ()
Method called by previously defined method ????
FeConfigurationBlock & clearCalibEnable ()
clear the calib enable flag
bool isCalibEnable ()
Check the calib enable flag.
FeConfigurationBlock & setHoldStart (int holdStart)
Set the start of holding the signal.
int getHoldStart ()
Get the signel hold start value.
FeConfigurationBlock & setHoldWidth (int holdWidth)
int getHoldWidth ()
Set the hold width.
FeConfigurationBlock & setHoldInvert (bool hold_invert)
Set whether the holded signal is to be inverted.
FeConfigurationBlock & setHoldInvert ()
Method called by previously defined method ????
FeConfigurationBlock & clearHoldInvert ()
Clear the hold invert signel.
bool isHoldInvert ()
FeConfigurationBlock & setVfeResetStart (int vfeResetStart)
Start of the Vfe Reset.
int getVfeResetStart ()
FeConfigurationBlock & setVfeResetEnd (int vfeResetEnd)
Set the end of the Vfe Reset.
int getVfeResetEnd ()
Get the end of the Vfe Reset.
FeConfigurationBlock & setVfeSrinStart (int vfeSrinStart)
I have no idea what the follwing functions really do as long as the data are correct the experts can work with them.
int getVfeSrinStart ()
FeConfigurationBlock & setVfeSrinEnd (int vfeSrinEnd)
int getVfeSrinEnd ()
FeConfigurationBlock & setVfeMplexClockStart (int vfeMplexClockStart)
int getVfeMplexClockStart ()
FeConfigurationBlock & setVfeMplexClockMark (int vfeMplexClockMark)
int getVfeMplexClockMark ()
FeConfigurationBlock & setVfeMplexClockSpace (int vfeMplexClockSpace)
int getVfeMplexClockSpace ()
FeConfigurationBlock & setVfeMplexClockPulses (int vfeMplexClockPulses)
int getVfeMplexClockPulses ()
FeConfigurationBlock & setAdcStart (int adcStart)
Start of the ADC Reading.
int getAdcStart ()
FeConfigurationBlock & setAdcEnd (int adcEnd)
End of the ADC Reading, kind of gate width.
int getAdcEnd ()
FeConfigurationBlock & setAdcControlBits (int adcControl)
To whom it may concern ;-).
int getAdcControlBits ()
FeConfigurationBlock & setAdcDelay (int adcDelay)
Delay of the ADC readout.
int getAdcDelay ()
FeConfigurationBlock & setDacData (int top_value, int bottom_value)
Dac Data setting.
int getDacDataTop () const
Daq data on top side of the ADC sample.
int getDacDataBottom () const
Daq data onbottom side of the ADC sample.
FeConfigurationBlock & setFrameSyncDelay (int frameSyncDelay)
Again not many ideas what this means.
int getFrameSyncDelay ()
FeConfigurationBlock & setQdrDataDelay (int qdrDataDelay)
int getQdrDataDelay ()
FeConfigurationBlock & setVfeInfo (int vfeInfo)
Set Vfe Info for Boards not identified as belonging to the SiW Ecal (only the word itself for the time being.
FeConfigurationBlock & setEmcVfeInfo (int vfeInfo, int iBot, int iTop, int iBotLowGainBit, int iTopLowGainBit)
Set Vfe Info for the Emc Information.
int getVfeInfo ()
Get complete the Vfe Info.
int emcVfeBottomEnable (int chip)
Get some detailed emc (!!) vfe info (basically taken from Pauls online software.
int emcVfeTopEnable (int chip)
bool emcVfeLowGainBottom ()
bool emcVfeLowGainTop ()
void print (std::ostream &os, int)
Convenient print method.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Static Public Member Functions
static unsigned int makeBoardID (const short crateID, const short slotID, const short boardComponentNumber)
Detailed Description
Stores the configuration data of the front-end of one CERC board. Based on AdcBlock. This is just a copy of the Calice DAQ class CrcFeConfigurationData. Since I don't have a profound understanding of the meaning of its members the documentation is mostly missing or at least very poor.
Author
Götz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Definition at line 58 of file FeConfigurationBlock.hh.
Constructor & Destructor Documentation
CALICE::FeConfigurationBlock::FeConfigurationBlock (int boardID) [inline]
Convenient c'tor.
Parameters
boardID CERC board ID (VME crate channel))
Definition at line 76 of file FeConfigurationBlock.hh.
References CALICE::LCGenericObjectImplExt::obj().
Member Function Documentation
int CALICE::FeConfigurationBlock::getCalibStart () [inline]
Get calibration pulse start value.
Returns
pulse start in units of 6.25 ns.
Definition at line 172 of file FeConfigurationBlock.hh.
int CALICE::FeConfigurationBlock::getCalibWidth () [inline]
Get duration of the calibration pulse.
Returns
pulse duration in units of 6.25 ns.
Definition at line 182 of file FeConfigurationBlock.hh.
FeConfigurationBlock& CALICE::FeConfigurationBlock::setCalibStart (int calibStart) [inline]
Set Calibration pulse start value.
Parameters
calibStart pulse start in units of 6.25 ns.
Definition at line 167 of file FeConfigurationBlock.hh.
References CALICE::LCGenericObjectImplExt::obj().
FeConfigurationBlock& CALICE::FeConfigurationBlock::setCalibWidth (int calibWidth) [inline]
Set duration of the calibration pulse.
Parameters
calibWidth pulse duration in units of 6.25 ns.
Definition at line 177 of file FeConfigurationBlock.hh.
References CALICE::LCGenericObjectImplExt::obj().
void CALICE::FeConfigurationBlock::setRecordLabel (int label) [inline]
Set the RecordLabel, i.e. whether this dataset was written to or read from a CRC board
Definition at line 147 of file FeConfigurationBlock.hh.
References CALICE::LCGenericObjectImplExt::obj().
The documentation for this class was generated from the following file:
FeConfigurationBlock.hh