CALICE::CellDescriptionGenerator Class Reference
class that generates cell descriptions objects
#include <CellDescriptionGenerator.hh>
Public Member Functions
CellDescriptionGenerator (const Mapper *mapper)
constructor
void generate (const lcio::LCCollection *modDescriptionCol, const lcio::LCCollection *modConnectionCol, const lcio::LCCollection *modLocationCol, const lcio::LCCollection *detTransformationCol, MappedContainer< CellDescription > *container) const
function that updates a MappedContainer of CellDescription objects
Private Attributes
const Mapper * _mapper
Detailed Description
class that generates cell descriptions objects
Author
Benjamin.Lutz@desy.de
Version
0.1
Date
June 2009
Definition at line 20 of file CellDescriptionGenerator.hh.
Constructor & Destructor Documentation
CALICE::CellDescriptionGenerator::CellDescriptionGenerator (const Mapper * mapper) [inline]
constructor
Parameters
$\leftarrow$ mapper mapper
Definition at line 29 of file CellDescriptionGenerator.hh.
Member Function Documentation
void CALICE::CellDescriptionGenerator::generate (const lcio::LCCollection * modDescriptionCol, const lcio::LCCollection * modConnectionCol, const lcio::LCCollection * modLocationCol, const lcio::LCCollection * detTransformationCol, MappedContainer< CellDescription > * container) const
function that updates a MappedContainer of CellDescription objects The cell positions are calculated the following way:
 r_{detector} + r_{module} \cdot M_{zshift} + r_{cell} \cdot M_{rot} \\ \quad\mathrm{where}\quad M_{rot}= \begin{array}{ccc} cos(\theta) & 0 & sin(\theta) \\ 0 & 1 & 0 \\ -sin(\theta) & 0 & cos(\theta) \end{array} \quad\mathrm{and}\quad M_{zshift}= \begin{array}{ccc} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1/cos(\theta) \end{array} 
Parameters
$\leftarrow$ modDescriptionCol
$\leftarrow$ modConnectionCol
$\leftarrow$ modLocationCol
$\leftarrow$ detTransformationCol
$\rightarrow$ container
Definition at line 19 of file CellDescriptionGenerator.cc.
References CALICE::MappedContainer< T >::clear(), CALICE::MappedContainer< T >::fillByCellID(), CALICE::ModuleLocation::getCellIndexOffset(), CALICE::Mapper::getDecoder(), CALICE::DetectorTransformation::getDetectorAngleZX(), CALICE::DetectorTransformation::getDetectorX0(), CALICE::DetectorTransformation::getDetectorY0(), CALICE::DetectorTransformation::getDetectorZ0(), CALICE::DecoderSet::getIFromCellID(), CALICE::ModuleConnection::getIndexOfLowerLeftCell(), CALICE::DecoderSet::getJFromCellID(), CALICE::DecoderSet::getKFromCellID(), CALICE::ModuleConnection::getModuleID(), CALICE::ModuleConnection::getModuleType(), CALICE::ModuleLocation::getModuleType(), CALICE::CellDescription::setAngle(), CALICE::CellDescription::setPosition(), and CALICE::CellDescription::setSize().
The documentation for this class was generated from the following files:
CellDescriptionGenerator.hh
CellDescriptionGenerator.cc