CALICE::GainConstants Class Reference
Class to store the results of a Gain calibration measurement, i.e.
#include <GainConstants.hh>Inheritance diagram for CALICE::GainConstants::
Public Member Functions
GainConstants ()
contructor
GainConstants (unsigned chip, unsigned channel, float value, float error)
constructor, initialised by parameters
GainConstants (LCObject *obj)
float getGainValue () const
get channels/pixel value
float getGainError () const
get channels/pixel error
float applyCalibration (float inputValue) const
apply gain calibration to energy value
float cancelCalibration (float outputValue) const
cancel an applied calibration from energy value
float applyCalibrationError (float inputValue, float inputError) const
apply calibration error to current error
float cancelCalibrationError (float outputValue, float outputError) const
apply error due to canceling a calibration to current error
bool calibrationValid () const
check if a valid gain calibration is available
bool keepEvent (float resultValue, float resultError) const
no cut for the moment
void print (std::ostream &os)
convenient print method
const std::string getTypeName () const
return type of the class
const std::string getDataDescription () const
return a brief description of the data member
Detailed Description
Class to store the results of a Gain calibration measurement, i.e. gain plus the error of it for a certain chip/channel for a fixed moduleID
Author
S. Schmidt DESY
Date
Aug 18 2006
Definition at line 25 of file GainConstants.hh.
Constructor & Destructor Documentation
CALICE::GainConstants::GainConstants (unsigned chip, unsigned channel, float value, float error) [inline]
constructor, initialised by parameters
Parameters
chip chip number of the cell to be calibrated
channel channel number of the cell to be calibrated
value gain value
error error on the gain value
Definition at line 39 of file GainConstants.hh.
References CALICE::LCHcalCalibrationObject::obj(), and CALICE::LCHcalCalibrationObject::setCellKey().
Member Function Documentation
float CALICE::GainConstants::applyCalibration (float inputValue) const [inline, virtual]
apply gain calibration to energy value
Parameters
inputValue `energy` value before the gain calibration
Returns
`energy` value after the gain calibration
Reimplemented from CALICE::LCHcalCalibrationObject .
Reimplemented in CALICE::TempGainConstants .
Definition at line 66 of file GainConstants.hh.
References getGainValue().
float CALICE::GainConstants::applyCalibrationError (float inputValue, float inputError) const [inline, virtual]
apply calibration error to current error
Parameters
inputValue `energy` value before the gain calibration
inputError error on the `energy` value before the gain calibration
Returns
error of the `energy` value after the calibration, gained from error propagation of the error of the `energy` value before the calibration and the error of the gain calibration
Reimplemented from CALICE::LCHcalCalibrationObject .
Reimplemented in CALICE::TempGainConstants .
Definition at line 82 of file GainConstants.hh.
References getGainError(), and getGainValue().
bool CALICE::GainConstants::calibrationValid () const [inline, virtual]
check if a valid gain calibration is available
Returns
true if the gain value is a valid number
Reimplemented from CALICE::LCHcalCalibrationObject .
Reimplemented in CALICE::TempGainConstants .
Definition at line 95 of file GainConstants.hh.
References getGainValue().
Referenced by CALICE::TempGainConstants::calibrationValid().
bool CALICE::GainConstants::keepEvent (float resultValue, float resultError) const [inline, virtual]
no cut for the moment
Returns
true, as no cut on cell level is performed after applying the gain calibration
Reimplemented from CALICE::LCHcalCalibrationObject .
Definition at line 102 of file GainConstants.hh.
The documentation for this class was generated from the following files:
GainConstants.hh
GainConstants.cc