CALICE::DhcReadoutConfBlock Class Reference
Class to interface the configuration of the Dhcal fes.
#include <DhcReadoutConfBlock.hh>Inheritance diagram for CALICE::DhcReadoutConfBlock::
Public Member Functions
DhcReadoutConfBlock ()
Simple Constructor.
DhcReadoutConfBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
virtual ~DhcReadoutConfBlock ()
The destructor.
DhcReadoutConfBlock & setNumbers (unsigned int numbers)
Set the numbers.
unsigned int getNumbers () const
Get the numbers.
unsigned int getCrateNumber ()
Return the crate number, can be obtained from numbers.
DhcReadoutConfBlock & setSlotEnableMask (unsigned int slotenablemask)
Set the slot enable mask, which tells which slots in could (in principle) have been enabled.
unsigned int getSlotEnableMask () const
Get the slot enable mask.
DhcReadoutConfBlock & setSlotEnable (unsigned int slotenable)
Set the slot enable, i.e.
unsigned int getSlotEnable () const
Get the slot enable.
DhcReadoutConfBlock & setNumberOfSlots (unsigned int numslots)
Set the number of slots, note that this number will have to be multiplied by two, leave it for the time being.
unsigned int getNumberOfSlots () const
Get the numbers of slots.
DhcReadoutConfBlock & setSlotFeEnable (unsigned int islot, unsigned int val)
Set the enabled fes for this slot.
unsigned short getSlotFeEnable (unsigned int islot)
Get the enabled fes for this slot.
DhcReadoutConfBlock & setSlotFeRevision (unsigned int islot, unsigned char val)
Set the revision number of the fes for this slot.
unsigned char getSlotFeRevision (unsigned int islot)
Set the revision number of the fes for this slot.
DhcReadoutConfBlock & setBeWaitInterval (unsigned int timeinmus)
Set the Be wait interval.
LCTime getBeWaitInterval ()
Return the Be wait interval, in mus.
std::ostream & print (std::ostream &ostrm)
Convenient print method.
const std::string getTypeName () const
const std::string getDataDescription () const
Return a brief description of the data members.
Private Member Functions
void fillSlotToWordsAssociationMask (unsigned int, bool)
Association mask.
void fillMethod (unsigned int, unsigned int, unsigned int, unsigned int)
A convenient method to fill fe eanble and fe revision values.
unsigned short getMethod (unsigned int, unsigned int, unsigned int)
A convenient method to fill fe eanble and fe revision values.
Private Attributes
std::map< unsigned int, unsigned int > _islotfillMap
map which associates the slots with the position in the LCGenericObject
bool _numSlotsInitialised
is the number of slots initialised (makes only sense during the filling sequence)
Detailed Description
Class to interface the configuration of the Dhcal fes.
Author
R. Pöschl (LAL Orsay), J. Smith (ANL)
Date
Apr 2011
Todo Attention we may introduce a platform dependency here!!!! The structure of the object assumes that LCGenericObjects are aligned on 32 bits Need maybe revision for assumptions on data alignment, could be added as collection parameters,
Definition at line 32 of file DhcReadoutConfBlock.hh.
Constructor & Destructor Documentation
CALICE::DhcReadoutConfBlock::DhcReadoutConfBlock (LCObject * obj) [inline]
'Copy constructor' needed to interpret LCCollection read from file/database.
Definition at line 48 of file DhcReadoutConfBlock.hh.
References _numSlotsInitialised, fillSlotToWordsAssociationMask(), and getSlotEnableMask().
Member Function Documentation
void DhcReadoutConfBlock::fillSlotToWordsAssociationMask (unsigned int slotenablemask, bool initvals) [private]
Association mask.
using the slot enable mask we create the map which associates the slots to the position in the LCGenericObject
Definition at line 21 of file DhcReadoutConfBlock.cc.
References _islotfillMap, _numSlotsInitialised, getNumberOfSlots(), and CALICE::LCGenericObjectImplExt::obj().
Referenced by DhcReadoutConfBlock(), and setSlotEnableMask().
DhcReadoutConfBlock& CALICE::DhcReadoutConfBlock::setSlotEnable (unsigned int slotenable) [inline]
Set the slot enable, i.e. the slots which are really enabled
Definition at line 92 of file DhcReadoutConfBlock.hh.
References CALICE::LCGenericObjectImplExt::obj().
The documentation for this class was generated from the following files:
DhcReadoutConfBlock.hh
DhcReadoutConfBlock.cc