CALICE::BmlCaen767ReadoutConfigurationBlock Class Reference
Stores the configuration of the Caen767 TDC into the database At the moment I am writing this class I don't know whether they'll serve for something but it is a small uncomplicated class, so here we go.
#include <BmlCaen767ReadoutConfigurationBlock.hh>Inheritance diagram for CALICE::BmlCaen767ReadoutConfigurationBlock::
Public Member Functions
BmlCaen767ReadoutConfigurationBlock ()
Default Constructor.
BmlCaen767ReadoutConfigurationBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
BmlCaen767ReadoutConfigurationBlock & setCrateNumber (int cratenumber)
set the packed board id.
int getCrateNumber ()
Return the crate number.
BmlCaen767ReadoutConfigurationBlock & setReadPeriod (int readperiod)
Set the Read Period.
unsigned int getReadPeriod () const
Return the Read Period.
BmlCaen767ReadoutConfigurationBlock & setBools (bool enable, bool softtrigger, bool bltro, bool arrayro)
Store the indicators of the readout mode.
bool isEnabled ()
bool isSoftTrigger ()
bool isBltReadout ()
bool isArrayReadout ()
BmlCaen767ReadoutConfigurationBlock & setMode (int mode)
Store the readout mode word note that this word contains the information which you also get with the isSoftTrigger, isEnable, getCrateNumber etc.
int getMode ()
Return the readout mode word.
void print (std::ostream &os)
Convenient print method.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Stores the configuration of the Caen767 TDC into the database At the moment I am writing this class I don't know whether they'll serve for something but it is a small uncomplicated class, so here we go.
See also
ConditionsChangeDelegator
Author
R. Poeschl LAL (based on the other interface classes)
Date
Aug 2006
Definition at line 36 of file BmlCaen767ReadoutConfigurationBlock.hh.
Member Function Documentation
BmlCaen767ReadoutConfigurationBlock& CALICE::BmlCaen767ReadoutConfigurationBlock::setCrateNumber (int cratenumber) [inline]
set the packed board id.
See also
BoardID For the Caen 767 TDC the boardID has a slightly different meaning compared with the CrcBoards slotID and board component numbers are just the MSB and LSB of the base address. Set the crate number
Definition at line 60 of file BmlCaen767ReadoutConfigurationBlock.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by BmlCaen767ReadoutConfigurationBlock().
BmlCaen767ReadoutConfigurationBlock& CALICE::BmlCaen767ReadoutConfigurationBlock::setMode (int mode) [inline]
Store the readout mode word note that this word contains the information which you also get with the isSoftTrigger, isEnable, getCrateNumber etc. methods we add the word in case meaning of the bits therein have changed or new inidcators are added and we weren't aware of it. Hence this is just a safety net
Definition at line 116 of file BmlCaen767ReadoutConfigurationBlock.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by BmlCaen767ReadoutConfigurationBlock().
The documentation for this class was generated from the following file:
BmlCaen767ReadoutConfigurationBlock.hh