CALICE::BeTrgConf Class Reference
Stores the configuration data of the trigger.
#include <BeTrgConf.hh>Inheritance diagram for CALICE::BeTrgConf::
Public Member Functions
BeTrgConf ()
Default Constructor.
BeTrgConf (int boardID)
Ctor.
BeTrgConf (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
BeTrgConf & setBoardID (int boardID)
set the packed board id.
int getBoardID () const
Information on the FE chip the data was received.
void setRecordLabel (int label)
Set the Record Label.
short getRecordLabel () const
Return the Record Label.
BeTrgConf & setInputEnableMask (int input_enable)
Set the trigger enable bit mask.
int getInputEnableMask () const
Get the trigger enable bit mask.
BeTrgConf & setOscillatorEnable (int osc_enable)
Set Oscillator Enable.
int getOscillatorEnable () const
Get Oscillator Enable.
BeTrgConf & setGeneralEnable (int gen_enable)
Set General Enable.
int getGeneralEnable () const
Get General Enable.
BeTrgConf & setOscillationPeriod (int oscillation_period)
Set the oscillation period.
int getOscillationPeriod () const
Get the oscillation period.
BeTrgConf & setBurstCounter (int burst_count)
Set the burst counter.
int getBurstCounter () const
Get the burst counter.
BeTrgConf & setConfiguration (int config)
Set the configuration word.
int getConfiguration () const
Get the configuration word.
BeTrgConf & setFifoIdleDepth (int fifo_idle_depth)
Set the fifo idle depth.
int getFifoIdleDepth () const
Get the fifo idle depth.
BeTrgConf & setBusyTimeout (int busy_timeout)
Set the busy time out.
int getBusyTimeout () const
Get the busy time out.
BeTrgConf & setBurstTimeout (int burst_timeout)
Set the burst time out.
int getBurstTimeout () const
Get the burst time out.
BeTrgConf & setAndEnable (int and_enable, int pos)
Set the andEnable.
int getAndEnable (int pos) const
Get the and Enable.
BeTrgConf & setExtBeamMode (int ext_beammode)
Set the extBeam Mode.
int getExtBeamMode () const
Get the extBeam Mode.
BeTrgConf & setInputInvert (int input_invert)
Set the input invert.
int getInputInvert () const
Get the input invert.
BeTrgConf & setQdrConfiguration (int qdr_config)
Set the qdr configuration.
int getQdrConfiguration () const
Get the qdr configuration.
BeTrgConf & setSequencerControl (int sequence_contr)
Set the sequencer control.
int getSequencerControl () const
Get the sequencer control.
void print (std::ostream &os)
Convenient print method.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Stores the configuration data of the trigger. To acces the configuration:
   void BrTrgCondChangeListener(LCCollection *col) {
        assert (col->getNumberOfElements()==1)
        BeTrgConf conf(col->getElementAt(0));
        UInt_t enable_mask=conf.getEnableMask();
   }
See also
ConditionsChangeDelegator
Author
Götz Gaycken LLR (Ecole Polytechnique)
Date
Sep 2005
Definition at line 76 of file BeTrgConf.hh.
Constructor & Destructor Documentation
CALICE::BeTrgConf::BeTrgConf (int boardID) [inline]
Ctor.
Parameters
boardID the packed board id (BoardID).
Definition at line 86 of file BeTrgConf.hh.
References CALICE::LCGenericObjectImplExt::obj().
Member Function Documentation
int CALICE::BeTrgConf::getInputEnableMask () const [inline]
Get the trigger enable bit mask. For each aenabled trigger a bit is set. The meaning of the bits is defined by conditions data.
See also
TriggerMask.
Definition at line 128 of file BeTrgConf.hh.
Referenced by print().
BeTrgConf& CALICE::BeTrgConf::setBoardID (int boardID) [inline]
set the packed board id.
See also
BoardID
Definition at line 97 of file BeTrgConf.hh.
References CALICE::LCGenericObjectImplExt::obj().
BeTrgConf& CALICE::BeTrgConf::setInputEnableMask (int input_enable) [inline]
Set the trigger enable bit mask. For each aenabled trigger a bit is set. The meaning of the bits is defined by conditions data.
See also
TriggerMask.
Definition at line 118 of file BeTrgConf.hh.
References CALICE::LCGenericObjectImplExt::obj().
The documentation for this class was generated from the following file:
BeTrgConf.hh