CALICE::BeEvent Class Reference
Stores the trigger history (i.e.
#include <BeEvent.hh>Inheritance diagram for CALICE::BeEvent::
Public Member Functions
BeEvent ()
Simple Constructor.
BeEvent (unsigned int board_id)
UsefulConstructor.
BeEvent (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
BeEvent & setBoardID (int boardID)
Set the packed board id.
int getBoardID () const
Get the board id.
BeEvent & setRecordLabel (int label)
Set the Record Label.
short getRecordLabel () const
Return the Record Label.
BeEvent & setStatusWord (int status)
Set the status word.
int getStatusWord () const
Get the status word.
BeEvent & setL1aCounter (int l1acounter)
Set the l1acounter This number is used to check integrity of trigger counters.
int getL1aCounter () const
Get the l1acounter.
BeEvent & setBxCounter (int bxcount)
Set the bxcounter (bunch crossing !?).
int getBxCounter () const
Get the bxcounter.
BeEvent & setQdrFrameCounter (int qdrframecount)
Set the QdrFrameCounter (Whatever this is .
int getQdrFrameCounter () const
Get the QdrFrameCounter.
BeEvent & setQdrDataCounter (int qdrdatacount)
Set the QdrDataCounter (Whatever this is .
int getQdrDataCounter () const
Get the QdrDataCounter.
BeEvent & setTotalFrameCounter (int totalframecount)
Set the TotalFrameCounter (Whatever this is .
int getTotalFrameCounter () const
Get the TotalFrameCounter.
void print (std::ostream &os)
Convenient print method.
const std::string getTypeName () const
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Stores the trigger history (i.e. fifo content).when it appears in the front end as realized for runs starting in May 2006 (Ask Paul for firmware version) in older versions of the DAQ these data came along wiith the BeTrgEventData which still contains information related to the data handled by the present interface class.
To acces the configuration:
   void processEvent(LCEvent *event) {
       try {
        // string _colName = "BeTrgEventData"
        LCCollection *col=event->getCollection(_colName);
        for (unsigned int element_i=0; element_i<col->getNumberOfElements(); element_i++) {
           BeEvent event(col->getElementAt(element_i));
        }
   }
Author
R. Pöschl (LAL Orsay)
Date
Jul 2006
Definition at line 58 of file BeEvent.hh.
Constructor & Destructor Documentation
CALICE::BeEvent::BeEvent (unsigned int board_id) [inline]
UsefulConstructor.
Parameters
board_id the packed board id (CALICE::BoardID).
Definition at line 80 of file BeEvent.hh.
References setBoardID(), setBxCounter(), setL1aCounter(), setQdrDataCounter(), setQdrFrameCounter(), setRecordLabel(), setStatusWord(), and setTotalFrameCounter().
Member Function Documentation
BeEvent& CALICE::BeEvent::setBoardID (int boardID) [inline]
Set the packed board id.
See also
BoardID
Definition at line 108 of file BeEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by BeEvent().
BeEvent& CALICE::BeEvent::setQdrDataCounter (int qdrdatacount) [inline]
Set the QdrDataCounter (Whatever this is . ..)
Definition at line 163 of file BeEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by BeEvent().
BeEvent& CALICE::BeEvent::setQdrFrameCounter (int qdrframecount) [inline]
Set the QdrFrameCounter (Whatever this is . ..)
Definition at line 155 of file BeEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by BeEvent().
BeEvent& CALICE::BeEvent::setTotalFrameCounter (int totalframecount) [inline]
Set the TotalFrameCounter (Whatever this is . ..)
Definition at line 171 of file BeEvent.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by BeEvent().
The documentation for this class was generated from the following file:
BeEvent.hh