CALICE::DeadNoiseConstants Class Reference
Class to store the results of a selection of dead or noisy cells for a certain chip/channel for a fixed moduleID.
#include <DeadNoiseConstants.hh>Inheritance diagram for CALICE::DeadNoiseConstants::
Public Member Functions
DeadNoiseConstants ()
default constructor
DeadNoiseConstants (unsigned chip, unsigned channel, int deadLevel, int noiseLevel)
constructor, initializing with parameters
DeadNoiseConstants (LCObject *obj)
int getDeadLevel () const
get cell dead level
float getNoiseLevel () const
get cell noise level
float applyCalibration (float inputValue) const
apply calibration to energy value
float applyCalibrationError (float inputValue, float inputError) const
apply calibration error to current error
bool calibrationValid () const
check if a valid calibration is available
bool keepEvent (float resultValue, float resultError) const
accept only non-dead and non-noisy events
void print (std::ostream &os)
convenient print method
const std::string getTypeName () const
return type of the class
const std::string getDataDescription () const
return a brief description of the data member
Detailed Description
Class to store the results of a selection of dead or noisy cells for a certain chip/channel for a fixed moduleID.
Author
S. Schmidt DESY
Date
Sep 25 2006
Definition at line 25 of file DeadNoiseConstants.hh.
Constructor & Destructor Documentation
CALICE::DeadNoiseConstants::DeadNoiseConstants (unsigned chip, unsigned channel, int deadLevel, int noiseLevel) [inline]
constructor, initializing with parameters
Parameters
chip chip number of cell to be calibrated
channel channel number of cell to be calibrated
deadLevel `level` of being dead for a cell, 0: not dead, 1: dead
noiseLevel `level` of being noisy for a cell, 0: no noise, 1: low noise, 2: high noise
Definition at line 39 of file DeadNoiseConstants.hh.
References CALICE::LCHcalCalibrationObject::obj(), and CALICE::LCHcalCalibrationObject::setCellKey().
Member Function Documentation
float CALICE::DeadNoiseConstants::applyCalibration (float inputValue) const [inline, virtual]
apply calibration to energy value
Parameters
inputValue `energy` value before the calibration
Returns
as the selection of non-dead/non-noisy cells has no impact on the `energy` the inputValue is returned
Reimplemented from CALICE::LCHcalCalibrationObject .
Definition at line 67 of file DeadNoiseConstants.hh.
float CALICE::DeadNoiseConstants::applyCalibrationError (float inputValue, float inputError) const [inline, virtual]
apply calibration error to current error
Parameters
inputValue `energy` value before the calibration
inputError error of the `energy` value before the calibration
Returns
as the selection of non-dead/non-noisy cells has no error the inputError is returned
Reimplemented from CALICE::LCHcalCalibrationObject .
Definition at line 76 of file DeadNoiseConstants.hh.
bool CALICE::DeadNoiseConstants::calibrationValid () const [inline, virtual]
check if a valid calibration is available
Returns
true as the selection of non-dead/non-noisy cells is always valid
Reimplemented from CALICE::LCHcalCalibrationObject .
Definition at line 83 of file DeadNoiseConstants.hh.
bool CALICE::DeadNoiseConstants::keepEvent (float resultValue, float resultError) const [inline, virtual]
accept only non-dead and non-noisy events
Parameters
resultValue `energy` value after the calibration
resultError error of the `energy` value after the calibration
Returns
true if a cell is non-dead and non-noisy
Reimplemented from CALICE::LCHcalCalibrationObject .
Definition at line 92 of file DeadNoiseConstants.hh.
References getDeadLevel(), and getNoiseLevel().
The documentation for this class was generated from the following files:
DeadNoiseConstants.hh
DeadNoiseConstants.cc