CALICE::MappedContainer< T > Class Template Reference
Container for fast access by index.
#include <MappedContainer.hh>
Data Structures
class DataWithAddress
Public Member Functions
MappedContainer (const Mapper *mapper, const bool deleteElements=true)
Constructor.
DecoderSet * getDecoder ()
return a pointer to the DecoderSet handling the decoding of IDs with encoding strings
void fillByCellID (const int cellID, T *object, bool unique=true)
fill content for (Mokka) cellID
void fillByModuleID (const int channelID, T *object, bool unique=true)
fill content for (Module) channel ID
void fillByDAQID (const int DAQID, T *object, bool unique=true)
fill content for DAQ channel ID
T * getByCellID (const int cellID)
get content for (Mokka) cellID
T * getByModuleID (const int channelID)
get content for (Module) channel ID
T * getByDAQID (const int DAQID)
get content for DAQ channel ID
T * removeByCellID (const int cellID)
get content for (Mokka) cellID and remove it from the container
T * removeByModuleID (const int channelID)
get content for (Module) channel ID and remove it from the container
T * removeByDAQID (const int DAQID)
get content for DAQ channel ID and remove it from the container
void deleteByCellID (const int cellID)
delete entry for (Mokka) cellID
void deleteByModuleID (const int channelID)
delete entry for (Module) channel ID
void deleteByDAQID (const int DAQID)
delete entry for DAQ channel ID
void clear ()
clear container
std::vector< T * > getAllElements () const
get a vector with all elements
unsigned int getVersion () const
get version number to check for updates
Private Member Functions
T * getByIndex (const unsigned int index) const
void fillByIndex (const unsigned int index, T *object, bool unique=true)
T * removeByIndex (const unsigned int index)
void deleteByIndex (const unsigned int index)
void initOrderedData (const unsigned int size, const bool clearAddresses=true)
void refillOrderedData (const unsigned int size)
void checkMapping ()
void contentModified ()
Private Attributes
const Mapper * _mapper
bool _deleteElements
std::vector< DataWithAddress * > _orderedData
unsigned int _mapperVersion
unsigned int _version
unsigned int _maxIndex
Detailed Description
template<class T> class CALICE::MappedContainer< T >
Container for fast access by index. This class stores arbitrary data types and offers transparent access by different coordinate systems.
Author
Benjamin.Lutz@desy.de
Version
1.3
Date
November 2009
Definition at line 24 of file MappedContainer.hh.
Constructor & Destructor Documentation
template<class T> CALICE::MappedContainer< T >::MappedContainer (const Mapper * mapper, const bool deleteElements = true) [inline]
Constructor.
Parameters
$\leftarrow$ mapper Mapper object that is used to translate coordinate systems
$\leftarrow$ deleteElements Determines if the object behind the stored reference should be deleted, when it is removed from the container.
Definition at line 35 of file MappedContainer.hh.
References CALICE::Mapper::getMaxIndex(), and CALICE::Mapper::getVersion().
Member Function Documentation
template<class T> void CALICE::MappedContainer< T >::deleteByCellID (const int cellID) [inline]
delete entry for (Mokka) cellID If deleteElements is set, the stored object will be deleted, too.
Parameters
$\leftarrow$ cellID coordinate for content as (Module) channel ID see Mapper
Definition at line 178 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByCellID().
template<class T> void CALICE::MappedContainer< T >::deleteByDAQID (const int DAQID) [inline]
delete entry for DAQ channel ID If deleteElements is set, the stored object will be deleted, too.
Parameters
$\leftarrow$ DAQID coordinate for content as (Module) channel ID see Mapper
Definition at line 202 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByDAQID().
template<class T> void CALICE::MappedContainer< T >::deleteByModuleID (const int channelID) [inline]
delete entry for (Module) channel ID If deleteElements is set, the stored object will be deleted, too.
Parameters
$\leftarrow$ channelID coordinate for content as (Module) channel ID see Mapper
Definition at line 190 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByModuleID().
template<class T > void CALICE::MappedContainer< T >::fillByCellID (const int cellID, T * object, bool unique = true) [inline]
fill content for (Mokka) cellID If unique is set, an already set value cannot be overwritten and an exception is thrown. Otherwise, the old value gets overwritten.
Parameters
$\leftarrow$ cellID coordinate for content as (Mokka) cellID see Mapper
$\leftarrow$ object data to be stored
$\leftarrow$ unique enables protection from overwriting
Exceptions
BadDataException
Definition at line 326 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByCellID().
Referenced by CALICE::CellDescriptionGenerator::generate(), and CALICE::CellNeighbourCalculator::getNeighbours().
template<class T > void CALICE::MappedContainer< T >::fillByDAQID (const int DAQID, T * object, bool unique = true) [inline]
fill content for DAQ channel ID If unique is set, an already set value cannot be overwritten and an exception is thrown. Otherwise, the old value gets overwritten.
Parameters
$\leftarrow$ DAQID coordinate for content as DAQ channel ID see Mapper
$\leftarrow$ object data to be stored
$\leftarrow$ unique enables protection from overwriting
Exceptions
BadDataException
Definition at line 340 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByDAQID().
template<class T > void CALICE::MappedContainer< T >::fillByModuleID (const int channelID, T * object, bool unique = true) [inline]
fill content for (Module) channel ID If unique is set, an already set value cannot be overwritten and an exception is thrown. Otherwise, the old value gets overwritten.
Parameters
$\leftarrow$ channelID coordinate for content as Module channel ID see Mapper
$\leftarrow$ object data to be stored
$\leftarrow$ unique enables protection from overwriting
Exceptions
BadDataException
Definition at line 333 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByModuleID().
template<class T> T* CALICE::MappedContainer< T >::getByCellID (const int cellID) [inline]
get content for (Mokka) cellID
Parameters
$\leftarrow$ cellID coordinate for content as (Mokka) cellID see Mapper
Returns
data for cellID or 0 if no data is available (or channel does not exist)
Definition at line 109 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByCellID().
template<class T> T* CALICE::MappedContainer< T >::getByDAQID (const int DAQID) [inline]
get content for DAQ channel ID
Parameters
$\leftarrow$ DAQID coordinate for content as (Module) channel ID see Mapper
Returns
data for channel ID or 0 if no data is available (or channel does not exist)
Definition at line 132 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByDAQID().
template<class T> T* CALICE::MappedContainer< T >::getByModuleID (const int channelID) [inline]
get content for (Module) channel ID
Parameters
$\leftarrow$ channelID coordinate for content as (Module) channel ID see Mapper
Returns
data for channel ID or 0 if no data is available (or channel does not exist)
Definition at line 120 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByModuleID().
template<class T> DecoderSet* CALICE::MappedContainer< T >::getDecoder () [inline]
return a pointer to the DecoderSet handling the decoding of IDs with encoding strings This function returns a pointer to the DecoderSet used by the Mapper. This allows to change the used encoding string. Be aware that the DecoderSet might be the same for many Objects using the same Mapper. Therefore, you should always enfore your encoding before using the MappedContainer.
Definition at line 59 of file MappedContainer.hh.
References CALICE::Mapper::getDecoder().
template<class T> T* CALICE::MappedContainer< T >::removeByCellID (const int cellID) [inline]
get content for (Mokka) cellID and remove it from the container
Parameters
$\leftarrow$ cellID coordinate for content as (Module) channel ID see Mapper
Returns
data for cellID or 0 if no data is available (or channel does not exist)
Definition at line 143 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByCellID().
template<class T> T* CALICE::MappedContainer< T >::removeByDAQID (const int DAQID) [inline]
get content for DAQ channel ID and remove it from the container
Parameters
$\leftarrow$ DAQID coordinate for content as (Module) channel ID see Mapper
Returns
data for channel ID or 0 if no data is available (or channel does not exist)
Definition at line 165 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByDAQID().
template<class T> T* CALICE::MappedContainer< T >::removeByModuleID (const int channelID) [inline]
get content for (Module) channel ID and remove it from the container
Parameters
$\leftarrow$ channelID coordinate for content as (Module) channel ID see Mapper
Returns
data for channel ID or 0 if no data is available (or channel does not exist)
Definition at line 154 of file MappedContainer.hh.
References CALICE::Mapper::getIndexByModuleID().
The documentation for this class was generated from the following file:
MappedContainer.hh