CALICE::BeTrgPollData Class Reference
Class to store info on trigger polling, This is useful to detect a softtrigger among e.g.
#include <BeTrgPollData.hh>Inheritance diagram for CALICE::BeTrgPollData::
Public Member Functions
BeTrgPollData ()
Default Constructor.
BeTrgPollData (LCObject *obj)
A copy constructor.
virtual ~BeTrgPollData ()
The destructor.
BeTrgPollData & setBoardID (int boardID)
set the packed board id.
int getBoardID () const
get the board id
BeTrgPollData & setRecordLabel (int label)
Set the Record Label.
short getRecordLabel () const
Return the Record Label.
BeTrgPollData & setStartTime (struct tm *startTime, int startTimemus)
set the start time We store Year, Month, Day and Hour, Minute, Second and microsceconds seperately We store UTC!!!!
LCTime getStartTime ()
returns the start time
BeTrgPollData & setEndTime (struct tm *endTime, int endTimemus)
set the end time (see set of start time)
LCTime getEndTime ()
returns the end time (see start time)
BeTrgPollData & setMaximumTime (int maxTimesec, int maxTimemus)
set the maximum time
int getMaximumTimeSec ()
returns the maximum time sec.
int getMaximumTimeMus ()
returns the maximum time musec.
BeTrgPollData & setNumberOfPolls (int numPolls)
set the number of polls
int getNumberOfPolls ()
returns the number of polls time
BeTrgPollData & setTimeout (int timeout)
set the info on timeout
bool isTimeout ()
timeout set?
const std::string getTypeName () const
returns the the type name
const std::string getDataDescription () const
returns a brief description of the data stored
std::ostream & print (std::ostream &ostrm)
dumps data content
Detailed Description
Class to store info on trigger polling, This is useful to detect a softtrigger among e.g. beam trigger if e.g. the beam has disappeared
Author
R. Pöschl (LAL Orsay)
Date
Jul 02 2006
Definition at line 39 of file BeTrgPollData.hh.
Member Function Documentation
int CALICE::BeTrgPollData::getMaximumTimeMus () [inline]
returns the maximum time musec. part
Definition at line 226 of file BeTrgPollData.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by print().
int CALICE::BeTrgPollData::getMaximumTimeSec () [inline]
returns the maximum time sec. part
Definition at line 217 of file BeTrgPollData.hh.
References CALICE::LCGenericObjectImplExt::obj().
Referenced by print().
BeTrgPollData& CALICE::BeTrgPollData::setBoardID (int boardID) [inline]
set the packed board id.
See also
BoardID
Definition at line 79 of file BeTrgPollData.hh.
References CALICE::LCGenericObjectImplExt::obj().
The documentation for this class was generated from the following file:
BeTrgPollData.hh