CALICE::DriftChamberParameter Class Reference
Parameters for one drift chamber.
#include <DriftChamberParameter.hh>
Public Member Functions
DriftChamberParameter (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
DriftChamberParameter & setDriftVelocity (float drift_velocity)
Set the drift velocity.
float getDriftVelocity () const
Get the drift velocity.
DriftChamberParameter & setDelay (float time_shift)
Set the time to be subtracted from the measured time to get the drift time.
float getDelay () const
Get the time to be subtracted from the measured time to get the drift time.
DriftChamberParameter & setOffsetZ (float offset_z)
Set the position offset of the chamber in the z-direction.
float getOffsetZ () const
Get the position offset of the chamber in the z-direction.
DriftChamberParameter & setOffsetU (float offset_u)
Set the position offset of the chamber in the drift direction.
float getOffsetU () const
Get the position offset of the chamber in the drift direction.
DriftChamberParameter & setError (float error)
Set the error on the position measurement.
float getError () const
Get the error on the position measurement.
DriftChamberParameter & setDirectionSign (int sign)
Set the sign of the drift direction.
int getDirectionSign () const
Get the sign of the drift direction.
float calcPos (float time) const
Calculate from the measured time the postion along the drift direction.
float calcTime (float pos) const
Calculate from the measured time the postion along the drift direction.
float calcDelay (float residual) const
Calculate from the measured residual the shift of the offset to be subtracted from the measured time.
EDriftChamberWireType getWireType () const
Return the type of the wire.
void setWireType (int wire_type)
Set the wire type.
void print (std::ostream &os)
Print all members (for debugging).
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Parameters for one drift chamber.
Definition at line 41 of file DriftChamberParameter.hh.
Member Function Documentation
float CALICE::DriftChamberParameter::calcDelay (float residual) const [inline]
Calculate from the measured residual the shift of the offset to be subtracted from the measured time.
Definition at line 163 of file DriftChamberParameter.hh.
References getDelay(), getDirectionSign(), and getDriftVelocity().
float CALICE::DriftChamberParameter::calcPos (float time) const [inline]
Calculate from the measured time the postion along the drift direction.
Definition at line 153 of file DriftChamberParameter.hh.
References getDelay(), getDirectionSign(), getDriftVelocity(), and getOffsetU().
float CALICE::DriftChamberParameter::calcTime (float pos) const [inline]
Calculate from the measured time the postion along the drift direction.
Definition at line 158 of file DriftChamberParameter.hh.
References getDelay(), getDirectionSign(), getDriftVelocity(), and getOffsetU().
EDriftChamberWireType CALICE::DriftChamberParameter::getWireType () const [inline]
Return the type of the wire. Wires are distinguished by their orientation (x.y) and the position with respect to the beam axis (left or right of the beam axis for x; below or above the beam axis for y wires).
Definition at line 172 of file DriftChamberParameter.hh.
References CALICE::kDriftChamberParameterIntWireType.
The documentation for this class was generated from the following files:
DriftChamberParameter.hh
DriftChamberParameter.cc