AverageSimple_t Class Reference
Calculate mean and standard deviation.
#include <AverageSimple_t.hh>
Public Member Functions
AverageSimple_t ()
Default constructor initialses all arrays to be ready to gather statastics of a variable.
void add (Float_t value)
build the sum and the sum of squares.
void calculate ()
calculate the standard deviation and the mean.
Double_t mean () const
return the mean value.
Double_t sigma () const
return the standard deviation.
UInt_t n () const
return the sample size.
Double_t sum () const
Get the total accumulated data.
void operator+= (Float_t val)
Protected Attributes
UInt_t _n
xx xx xx xx xx xx xx xx xx
union {
 Double_t _sum
 Double_t _mean
};
xx xx xx xx xx xx xx xx xx
union {
 Double_t _sum2
 Double_t _sigma
};
Friends
std::ostream & operator<< (std::ostream &os, AverageSimple_t &a)
Detailed Description
Calculate mean and standard deviation.
Definition at line 13 of file AverageSimple_t.hh.
Member Function Documentation
void AverageSimple_t::add (Float_t value) [inline]
build the sum and the sum of squares. The sums can be used later to calculate the mean and the standard deviation
Parameters
value the value to be added to the sum and the sum of squares (
See also
calculate)
Definition at line 28 of file AverageSimple_t.hh.
void AverageSimple_t::calculate () [inline]
calculate the standard deviation and the mean. The mean and the standard deviation are stored in the locations which are also used for the sums. Therefore if further values are added after calculate() was called, the result is undefined.
Definition at line 38 of file AverageSimple_t.hh.
References mean(), and sigma().
Double_t AverageSimple_t::mean () const [inline]
return the mean value. returns only a correct result after at least 1 value was added and calculate was called.
Definition at line 50 of file AverageSimple_t.hh.
Referenced by calculate().
Double_t AverageSimple_t::sigma () const [inline]
return the standard deviation. returns only a correct result after at least 1 value was added and calculate was called.
Definition at line 55 of file AverageSimple_t.hh.
Referenced by calculate().
The documentation for this class was generated from the following file:
AverageSimple_t.hh