CALICE::BitSet Class Reference
Base class for easy definition of bit sets.
#include <BitSet.hh>Inheritance diagram for CALICE::BitSet::
Public Member Functions
int getInt () const
get integer corresponding to the bits
void setBits (const int value)
set all bits with an integer
std::vector< int > getIntVec () const
get vector of ints with elements corresponding to the single bits (1 for true and 0 for false)
void clear ()
clear all bits to 0
Protected Member Functions
BitSet (const unsigned int maxBits, const int value=0x0)
constructur
bool getBit (unsigned int bitNo) const
get function for bit number
void setBit (unsigned int bitNo, bool state)
set function for bit number
Private Attributes
int _bits
unsigned int _maxBits
Detailed Description
Base class for easy definition of bit sets. Derived classes have to define the meaning of the bits. No instantiation possible.
Author
Benjamin.Lutz@desy.de
Date
November 2009
Version
1.0
Definition at line 18 of file BitSet.hh.
Constructor & Destructor Documentation
CALICE::BitSet::BitSet (const unsigned int maxBits, const int value = 0x0) [inline, protected]
constructur maximum number of bits defines the size of the returned vector
Parameters
$\leftarrow$ maxBits maximum number of bits
$\leftarrow$ value to initialise to different than 0
Definition at line 69 of file BitSet.hh.
Member Function Documentation
bool CALICE::BitSet::getBit (unsigned int bitNo) const [inline, protected]
get function for bit number
Parameters
bitNo number of the bit to return
Returns
state of bit
Definition at line 80 of file BitSet.hh.
Referenced by getIntVec(), CALICE::TcmtEventBits::hasMaxNumberHitsMuon(), CALICE::TcmtEventBits::hasMaxNumberMuonLikeTowers(), CALICE::TcmtEventBits::hasMaxSumEnergyMuon(), CALICE::TcmtEventBits::hasMinNumberHitsMuon(), CALICE::TcmtEventBits::hasMinNumberMuonLikeLayers(), CALICE::TcmtEventBits::hasMinNumberMuonLikeTowers(), CALICE::TcmtEventBits::hasMinSumEnergyMuon(), CALICE::TcmtEventBits::isLeakage(), CALICE::TcmtEventBits::isMuon(), and CALICE::TcmtEventBits::isPedestal().
int CALICE::BitSet::getInt () const [inline]
get integer corresponding to the bits
Returns
integer with the bits set
Definition at line 27 of file BitSet.hh.
Referenced by CALICE::TcmtEventIdentifier::addResults().
std::vector<int> CALICE::BitSet::getIntVec () const [inline]
get vector of ints with elements corresponding to the single bits (1 for true and 0 for false)
Returns
vector of integers of single bits
Definition at line 44 of file BitSet.hh.
References getBit().
Referenced by CALICE::TcmtEventIdentifier::addResults().
void CALICE::BitSet::setBit (unsigned int bitNo, bool state) [inline, protected]
set function for bit number
Parameters
bitNo number of the bit to set
state state to witch the bit gets set
Definition at line 87 of file BitSet.hh.
void CALICE::BitSet::setBits (const int value) [inline]
set all bits with an integer
Parameters
$\leftarrow$ value integer with the bits
Definition at line 34 of file BitSet.hh.
The documentation for this class was generated from the following file:
BitSet.hh