CALICE::AhcSlowReadoutModBlock Class Reference
Interface Class to access the AhcSlowReadout Data Here we handle ahc voltages, temperatures et al.
#include <AhcSlowReadoutModBlock.hh>Inheritance diagram for CALICE::AhcSlowReadoutModBlock::
Public Member Functions
AhcSlowReadoutModBlock ()
Constructor.
AhcSlowReadoutModBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
std::vector< double > & getCmbValues ()
Retrieve the cmb values.
std::vector< double > & getHbabTemperatures ()
Retrieve the hbab temperatures.
void print (std::ostream &)
convenient print method
virtual const std::string getTypeName () const
Return the type of the class.
virtual const std::string getDataDescription () const
Return a brief description of the data members.
Private Member Functions
void setTypes ()
This method defines the (general) types of the measured values A type not present here will not be handled!!!
Private Attributes
std::vector< double > _cmbValues
The output vectors.
std::vector< double > _hbabTemperatures
hbab temperatures
Detailed Description
Interface Class to access the AhcSlowReadout Data Here we handle ahc voltages, temperatures et al. when filling the class the string identifying the measured values has to be given first, a warning is issued if no identifier is given for a given datatype. On the other hand this concerns just the filler of the class, i.e. the conversion where it is done once for all. See the print method at the end of the class for the meaning of the fields (as of 31/7/06) Use the interface methods to retrieve the data fields
Author
Roman Pöschl LAL/Orsay
Date
Aug 2006
Definition at line 56 of file AhcSlowReadoutModBlock.hh.
Member Function Documentation
void CALICE::AhcSlowReadoutModBlock::print (std::ostream & os)
convenient print method Convenient print method.
Reimplemented from CALICE::ScintCaloSlowReadoutModBlock .
Definition at line 33 of file AhcSlowReadoutModBlock.cc.
References CALICE::ScintCaloSlowReadoutModBlock::_hbabVoltages, CALICE::ScintCaloSlowReadoutModBlock::getCmbHeight(), CALICE::ScintCaloSlowReadoutModBlock::getCmbTemperatures(), getCmbValues(), CALICE::ScintCaloSlowReadoutModBlock::getCmbVoltages(), CALICE::ScintCaloSlowReadoutModBlock::getCmbWidth(), getHbabTemperatures(), CALICE::ScintCaloSlowReadoutModBlock::getHbabVoltages(), CALICE::ScintCaloSlowReadoutModBlock::getLedSetting(), CALICE::ScintCaloSlowReadoutModBlock::getModuleNumber(), CALICE::ScintCaloSlowReadoutModBlock::getTimeStamp(), CALICE::ScintCaloSlowReadoutModBlock::prepareOutputVecs(), and CALICE::to_binary_bitops().
Field Documentation
std::vector<double> CALICE::AhcSlowReadoutModBlock::_cmbValues [private]
The output vectors. cmb values
Definition at line 120 of file AhcSlowReadoutModBlock.hh.
Referenced by AhcSlowReadoutModBlock(), getCmbValues(), and setTypes().
The documentation for this class was generated from the following files:
AhcSlowReadoutModBlock.hh
AhcSlowReadoutModBlock.cc