CALICE::TcmtEventIdentifier Class Reference
class that can identify type of event in TCMT
#include <TcmtEventIdentifier.hh>
Public Member Functions
TcmtEventIdentifier (const unsigned int maxLayer=16, const unsigned int startBackLayer=9, const std::string &forcedEncoding=``)
constructor
void process (lcio::LCCollection *col)
function to do the calculation on a collection
void addResults (lcio::LCCollection *col)
function to add the results as collection parameters
void addResults (const std::string parNameTcmtEventBits, lcio::LCEvent *evt)
function to add the int with the event type bits to the event
Private Member Functions
void setMuonThresholds (const int layerMuonHitMinCut, const int layerMuonHitMaxCut, const float layerMuonEnergyMinCut, const float layerMuonEnergyMaxCut, const int sumMuonHitMinCut, const int sumMuonHitMaxCut, const float sumMuonEnergyMinCut, const float sumMuonEnergyMaxCut, const int towerMuonHitCut, const int numberTowersMuonMinCut, const int numberTowersMuonMaxCut, const int numberLayersMuonCut)
internal function to set the thresholds
void reset ()
Private Attributes
float _energy
std::vector< float > _energyS
float _rmsE
float _energyBack
int _nHits
int _nHitsBack
std::vector< float > _layerEnergy
std::vector< int > _layerHits
BinnedVector< float, int > _xPos
BinnedVector< float, int > _yPos
BinnedVector< float, int > _xPosBack
BinnedVector< float, int > _yPosBack
int _nMuonLikeTowers
int _nMuonLikeLayers
std::string _forcedEncoding
unsigned int _maxLayer
unsigned int _startBackLayer
int _layerMuonHitMinCut
int _layerMuonHitMaxCut
float _layerMuonEnergyMinCut
float _layerMuonEnergyMaxCut
int _sumMuonHitMinCut
int _sumMuonHitMaxCut
float _sumMuonEnergyMinCut
float _sumMuonEnergyMaxCut
float _backEnergyRatio
int _towerMuonHitCut
int _numberTowersMuonMinCut
int _numberTowersMuonMaxCut
int _numberLayersMuonCut
TcmtEventBits _bits
Detailed Description
class that can identify type of event in TCMT The signal in the TCMT is analysed and compared to different thresholds. Following observables are used:
energy sum compared to min and max threshold
number hits compared to min and max threshold
number muon like layers compared to min threshold (the hits and energy in the layer have to be in range of a MIP signal)
number muon like towers compared to min and max threshold (the the sum of neighboring cells over consecutive layers have to exceed a certain limit)
See also
TcmtEventBits
Todo implement thresholds for TCMT back section
remove hardcoded thresholds
Author
Benjamin.Lutz@desy.de
Date
November 2009
Version
1.0
Definition at line 37 of file TcmtEventIdentifier.hh.
Constructor & Destructor Documentation
CALICE::TcmtEventIdentifier::TcmtEventIdentifier (const unsigned int maxLayer = 16, const unsigned int startBackLayer = 9, const std::string & forcedEncoding = ``)
constructor thresholds are set inside here, currently hardcoded
Parameters
$\leftarrow$ maxLayer maximum layer index (internally layer counting starts with 1)
$\leftarrow$ startBackLayer first layer to be considered back section of TCMT
$\leftarrow$ forcedEncoding can be used to overwrite the encoding string from the collection (to work around reconstruction bug)
Definition at line 12 of file TcmtEventIdentifier.cc.
References CALICE::BinnedVector< K, D >::setBinning(), and setMuonThresholds().
Member Function Documentation
void CALICE::TcmtEventIdentifier::addResults (const std::string parNameTcmtEventBits, lcio::LCEvent * evt)
function to add the int with the event type bits to the event
Parameters
$\leftarrow$ parNameTcmtEventBits name of the parameter that should contain the bits
$\rightarrow$ evt event for which the parameter should be added
Definition at line 176 of file TcmtEventIdentifier.cc.
References CALICE::BitSet::getInt().
void CALICE::TcmtEventIdentifier::addResults (lcio::LCCollection * col)
function to add the results as collection parameters
Parameters
$\rightarrow$ col TCMT collection
Definition at line 180 of file TcmtEventIdentifier.cc.
References CALICE::BitSet::getInt(), CALICE::BitSet::getIntVec(), and CALICE::BinnedVector< K, D >::getVector().
void CALICE::TcmtEventIdentifier::process (lcio::LCCollection * col)
function to do the calculation on a collection
Parameters
$\leftarrow$ col TCMT input collection
Definition at line 82 of file TcmtEventIdentifier.cc.
References CALICE::BitSet::clear(), CALICE::FastDecoder::decodeU(), CALICE::FastDecoder::generateDecoder(), and CALICE::BinnedVector< K, D >::getVector().
void CALICE::TcmtEventIdentifier::setMuonThresholds (const int layerMuonHitMinCut, const int layerMuonHitMaxCut, const float layerMuonEnergyMinCut, const float layerMuonEnergyMaxCut, const int sumMuonHitMinCut, const int sumMuonHitMaxCut, const float sumMuonEnergyMinCut, const float sumMuonEnergyMaxCut, const int towerMuonHitCut, const int numberTowersMuonMinCut, const int numberTowersMuonMaxCut, const int numberLayersMuonCut) [private]
internal function to set the thresholds
Parameters
$\leftarrow$ layerMuonHitMinCut min number of hits to consider layer muon like
$\leftarrow$ layerMuonHitMaxCut max number of hits to consider layer muon like
$\leftarrow$ layerMuonEnergyMinCut min energy sum to consider layer muon like
$\leftarrow$ layerMuonEnergyMaxCut max energy sum to consider layer muon like
$\leftarrow$ sumMuonHitMinCut min number of hits to consider signal originating from muon
$\leftarrow$ sumMuonHitMaxCut max number of hits to consider signal originating from muon
$\leftarrow$ sumMuonEnergyMinCut min energy sum to consider signal originating from muon
$\leftarrow$ sumMuonEnergyMaxCut max energy sum to consider signal originating from muon
$\leftarrow$ towerMuonHitCut min number of hits in tower to consider tower muon like
$\leftarrow$ numberTowersMuonMinCut min number of muon like tower to consider event originating from muon
$\leftarrow$ numberTowersMuonMaxCut max number of muon like tower to consider event originating from muon
$\leftarrow$ numberLayersMuonCut min number of muon like layers to consider event originating from muon
Definition at line 27 of file TcmtEventIdentifier.cc.
Referenced by TcmtEventIdentifier().
The documentation for this class was generated from the following files:
TcmtEventIdentifier.hh
TcmtEventIdentifier.cc