Functions to work with virtual Cell IDs
Functions
int CALICE::Ahc2Mapper::getTrueCellID (const int virtualCellIndex) const
return identifying index of cell
int CALICE::Ahc2Mapper::getTrueCellID (const unsigned int i, const unsigned int j, const unsigned int k) const
return identifying index of cell
unsigned int CALICE::Ahc2Mapper::getTrueIFromCellID (const int virtualCellID) const
return I of identifying index of cell
unsigned int CALICE::Ahc2Mapper::getTrueIFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const
return I of identifying index of cell
unsigned int CALICE::Ahc2Mapper::getTrueI (const unsigned int module, const unsigned int i, const unsigned int j) const
return I of identifying index of cell
unsigned int CALICE::Ahc2Mapper::getTrueJFromCellID (const int virtualCellID) const
return J of identifying index of cell
unsigned int CALICE::Ahc2Mapper::getTrueJFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const
return J of identifying index of cell
unsigned int CALICE::Ahc2Mapper::getTrueJ (const unsigned int module, const unsigned int i, const unsigned int j) const
return J of identifying index of cell
int CALICE::AhcMapper::getTrueCellID (const int virtualCellIndex) const
return identifying index of cell
int CALICE::AhcMapper::getTrueCellID (const unsigned int i, const unsigned int j, const unsigned int k) const
return identifying index of cell
unsigned int CALICE::AhcMapper::getTrueIFromCellID (const int virtualCellID) const
return I of identifying index of cell
unsigned int CALICE::AhcMapper::getTrueIFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const
return I of identifying index of cell
unsigned int CALICE::AhcMapper::getTrueI (const unsigned int module, const unsigned int i, const unsigned int j) const
return I of identifying index of cell
unsigned int CALICE::AhcMapper::getTrueJFromCellID (const int virtualCellID) const
return J of identifying index of cell
unsigned int CALICE::AhcMapper::getTrueJFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const
return J of identifying index of cell
unsigned int CALICE::AhcMapper::getTrueJ (const unsigned int module, const unsigned int i, const unsigned int j) const
return J of identifying index of cell
virtual int CALICE::Mapper::getTrueCellID (const int virtualCellIndex) const =0
return identifying index of cell
Function Documentation
virtual int CALICE::Mapper::getTrueCellID (const int virtualCellIndex) const [pure virtual, inherited]
return identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ virtualCellIndex (Mokka) cellID of (virtual) cell
Returns
index of full cell
Exceptions
BadDataException if cell does not exist
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
int CALICE::AhcMapper::getTrueCellID (const unsigned int i, const unsigned int j, const unsigned int k) const [inline, inherited]
return identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ i I of virtual cell
$\leftarrow$ j J of virtual cell
$\leftarrow$ k K of virtual cell
Returns
index of full cell
Definition at line 728 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::AhcMapper::getTrueCellID().
int CALICE::AhcMapper::getTrueCellID (const int virtualCellIndex) const [inline, virtual, inherited]
return identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ virtualCellIndex (Mokka) cellID of (virtual) cell
Returns
index of full cell
Implements CALICE::Mapper .
Definition at line 709 of file AhcMapper.hh.
References CALICE::DecoderSet::getCellID(), CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getTrueIFromCellID(), and CALICE::AhcMapper::getTrueJFromCellID().
Referenced by CALICE::AhcMapper::getTrueCellID().
int CALICE::Ahc2Mapper::getTrueCellID (const unsigned int i, const unsigned int j, const unsigned int k) const [inline, inherited]
return identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ i I of virtual cell
$\leftarrow$ j J of virtual cell
$\leftarrow$ k K of virtual cell
Returns
index of full cell
Definition at line 737 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::Ahc2Mapper::getTrueCellID().
int CALICE::Ahc2Mapper::getTrueCellID (const int virtualCellIndex) const [inline, virtual, inherited]
return identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ virtualCellIndex (Mokka) cellID of (virtual) cell
Returns
index of full cell
Implements CALICE::Mapper .
Definition at line 718 of file Ahc2Mapper.hh.
References CALICE::DecoderSet::getCellID(), CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getTrueIFromCellID(), and CALICE::Ahc2Mapper::getTrueJFromCellID().
Referenced by CALICE::Ahc2Mapper::getTrueCellID().
unsigned int CALICE::AhcMapper::getTrueI (const unsigned int module, const unsigned int i, const unsigned int j) const [inline, inherited]
return I of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ module module number
$\leftarrow$ i I
$\leftarrow$ j J
Returns
I of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 787 of file AhcMapper.hh.
Referenced by CALICE::AhcMapper::getTrueIFromIJK().
unsigned int CALICE::Ahc2Mapper::getTrueI (const unsigned int module, const unsigned int i, const unsigned int j) const [inline, inherited]
return I of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ module module number
$\leftarrow$ i I
$\leftarrow$ j J
Returns
I of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 796 of file Ahc2Mapper.hh.
Referenced by CALICE::Ahc2Mapper::getTrueIFromIJK().
unsigned int CALICE::AhcMapper::getTrueIFromCellID (const int virtualCellID) const [inline, inherited]
return I of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ virtualCellID (Mokka) cellID of (virtual) cell
Returns
I of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 747 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::AhcMapper::getTrueIFromIJK().
Referenced by CALICE::AhcMapper::getTrueCellID().
unsigned int CALICE::Ahc2Mapper::getTrueIFromCellID (const int virtualCellID) const [inline, inherited]
return I of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ virtualCellID (Mokka) cellID of (virtual) cell
Returns
I of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 756 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::Ahc2Mapper::getTrueIFromIJK().
Referenced by CALICE::Ahc2Mapper::getTrueCellID().
unsigned int CALICE::AhcMapper::getTrueIFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const [inline, inherited]
return I of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ i I
$\leftarrow$ j J
$\leftarrow$ k K
Returns
I of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 767 of file AhcMapper.hh.
References CALICE::AhcMapper::getModule(), and CALICE::AhcMapper::getTrueI().
Referenced by CALICE::AhcMapper::getTrueIFromCellID().
unsigned int CALICE::Ahc2Mapper::getTrueIFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const [inline, inherited]
return I of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ i I
$\leftarrow$ j J
$\leftarrow$ k K
Returns
I of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 776 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getModule(), and CALICE::Ahc2Mapper::getTrueI().
Referenced by CALICE::Ahc2Mapper::getTrueIFromCellID().
unsigned int CALICE::AhcMapper::getTrueJ (const unsigned int module, const unsigned int i, const unsigned int j) const [inline, inherited]
return J of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ module module number
$\leftarrow$ i I
$\leftarrow$ j J
Returns
J of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 852 of file AhcMapper.hh.
Referenced by CALICE::AhcMapper::getTrueJFromIJK().
unsigned int CALICE::Ahc2Mapper::getTrueJ (const unsigned int module, const unsigned int i, const unsigned int j) const [inline, inherited]
return J of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ module module number
$\leftarrow$ i I
$\leftarrow$ j J
Returns
J of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 861 of file Ahc2Mapper.hh.
Referenced by CALICE::Ahc2Mapper::getTrueJFromIJK().
unsigned int CALICE::AhcMapper::getTrueJFromCellID (const int virtualCellID) const [inline, inherited]
return J of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ virtualCellID (Mokka) cellID of (virtual) cell
Returns
J of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 812 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::AhcMapper::getTrueJFromIJK().
Referenced by CALICE::AhcMapper::getTrueCellID().
unsigned int CALICE::Ahc2Mapper::getTrueJFromCellID (const int virtualCellID) const [inline, inherited]
return J of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ virtualCellID (Mokka) cellID of (virtual) cell
Returns
J of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 821 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::Ahc2Mapper::getTrueJFromIJK().
Referenced by CALICE::Ahc2Mapper::getTrueCellID().
unsigned int CALICE::AhcMapper::getTrueJFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const [inline, inherited]
return J of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ i I
$\leftarrow$ j J
$\leftarrow$ k K
Returns
J of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 832 of file AhcMapper.hh.
References CALICE::AhcMapper::getModule(), and CALICE::AhcMapper::getTrueJ().
Referenced by CALICE::AhcMapper::getTrueJFromCellID().
unsigned int CALICE::Ahc2Mapper::getTrueJFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const [inline, inherited]
return J of identifying index of cell Cells of different size span different areas in Mokka CellID space. This functions returns for all coordinates of the cell the I of the Mokka CellID which is used to uniquely identify it.
Parameters
$\leftarrow$ i I
$\leftarrow$ j J
$\leftarrow$ k K
Returns
J of CellID of full cell
Exceptions
BadDataException if lookup fails
Definition at line 841 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getModule(), and CALICE::Ahc2Mapper::getTrueJ().
Referenced by CALICE::Ahc2Mapper::getTrueJFromCellID().