Functions for DAQ channel ID
Functions
unsigned int CALICE::Ahc2Mapper::getModuleFromDAQID (const int DAQchannel) const
module number from DAQ channel ID
unsigned int CALICE::Ahc2Mapper::getModuleFromDAQID (const int DAQchannel, bool &valid) const
get module (number) in which this (DAQ) channel is included
unsigned int CALICE::Ahc2Mapper::getIFromDAQID (const int DAQchannel) const
I of (Mokka) cellID.
unsigned int CALICE::Ahc2Mapper::getJFromDAQID (const int DAQchannel) const
J of (Mokka) cellID.
unsigned int CALICE::Ahc2Mapper::getKFromDAQID (const int DAQchannel) const
K of (Mokka) cellID.
unsigned int CALICE::Ahc2Mapper::getISizeFromDAQID (const int DAQchannel) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int CALICE::Ahc2Mapper::getJSizeFromDAQID (const int DAQchannel) const
get cell size in J direction of (Mokka) CellID coordinate
unsigned int CALICE::AhcMapper::getModuleFromDAQID (const int DAQchannel) const
module number from DAQ channel ID
unsigned int CALICE::AhcMapper::getModuleFromDAQID (const int DAQchannel, bool &valid) const
get module (number) in which this (DAQ) channel is included
unsigned int CALICE::AhcMapper::getIFromDAQID (const int DAQchannel) const
I of (Mokka) cellID.
unsigned int CALICE::AhcMapper::getJFromDAQID (const int DAQchannel) const
J of (Mokka) cellID.
unsigned int CALICE::AhcMapper::getKFromDAQID (const int DAQchannel) const
K of (Mokka) cellID.
unsigned int CALICE::AhcMapper::getISizeFromDAQID (const int DAQchannel) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int CALICE::AhcMapper::getJSizeFromDAQID (const int DAQchannel) const
get cell size in J direction of (Mokka) CellID coordinate
void CALICE::DecoderSet::setDAQEncoding (const std::string &encoding)
set a new DAQ channel ID encoding string if an empty string is given the function will use the default encoding string
const std::string & CALICE::DecoderSet::getDAQEncoding () const
get the current DAQ channel ID encoding string
unsigned int CALICE::DecoderSet::getChannelFromDAQID (const int DAQconnection) const
get channel from DAQ channel ID The right encoding string has to be set before.
unsigned int CALICE::DecoderSet::getChipFromDAQID (const int DAQconnection) const
get chip from DAQ channel ID The right encoding string has to be set before.
unsigned int CALICE::DecoderSet::getFeFromDAQID (const int DAQconnection) const
get fe from DAQ channel ID The right encoding string has to be set before.
unsigned int CALICE::DecoderSet::getSlotFromDAQID (const int DAQconnection) const
get slot from DAQ channel ID The right encoding string has to be set before.
unsigned int CALICE::DecoderSet::getCrateFromDAQID (const int DAQconnection) const
get crate from DAQ channel ID The right encoding string has to be set before.
int CALICE::DecoderSet::getDAQID (const unsigned int crate, const unsigned int slot, const unsigned int fe, const unsigned int chip, const unsigned int channel) const
get DAQ channel ID from crate, slot, fe, chip, channel
virtual unsigned int CALICE::Mapper::getModuleFromDAQID (const int DAQchannel) const =0
get module (number) in which this (DAQ) channel is included
virtual unsigned int CALICE::Mapper::getModuleFromDAQID (const int DAQchannel, bool &valid) const =0
get module (number) in which this (DAQ) channel is included
virtual unsigned int CALICE::Mapper::getIndexByDAQID (const int ID) const =0
get a compact index for storing data in vectors
Function Documentation
unsigned int CALICE::DecoderSet::getChannelFromDAQID (const int DAQconnection) const [inline, inherited]
get channel from DAQ channel ID The right encoding string has to be set before.
See also
setDAQEncoding
Parameters
$\leftarrow$ DAQconnection DAQ connection ID to decode
Returns
channel
Definition at line 169 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::AhcMapper::getIndexByDAQID(), and CALICE::Ahc2Mapper::getIndexByDAQID().
unsigned int CALICE::DecoderSet::getChipFromDAQID (const int DAQconnection) const [inline, inherited]
get chip from DAQ channel ID The right encoding string has to be set before.
See also
setDAQEncoding
Parameters
$\leftarrow$ DAQconnection DAQ connection ID to decode
Returns
chip
Definition at line 179 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::AhcMapper::getIndexByDAQID(), and CALICE::Ahc2Mapper::getIndexByDAQID().
unsigned int CALICE::DecoderSet::getCrateFromDAQID (const int DAQconnection) const [inline, inherited]
get crate from DAQ channel ID The right encoding string has to be set before.
See also
setDAQEncoding
Parameters
$\leftarrow$ DAQconnection DAQ connection ID to decode
Returns
crate
Definition at line 209 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::AhcMapper::getIndexByDAQID(), and CALICE::Ahc2Mapper::getIndexByDAQID().
const std::string& CALICE::DecoderSet::getDAQEncoding () const [inline, inherited]
get the current DAQ channel ID encoding string
Returns
DAQ channel ID encoding string
Definition at line 98 of file DecoderSet.hh.
int CALICE::DecoderSet::getDAQID (const unsigned int crate, const unsigned int slot, const unsigned int fe, const unsigned int chip, const unsigned int channel) const [inline, inherited]
get DAQ channel ID from crate, slot, fe, chip, channel The right encoding string has to be set before.
Warning
This DAQ channel ID will only contain information about crate, slot, fe, chip and channel. If the encoding string contains additional fields this will have value 0.
See also
setDAQEncoding
Parameters
$\leftarrow$ crate crate of this channel
$\leftarrow$ slot slot of this channel
$\leftarrow$ fe frontend of this channel
$\leftarrow$ chip chip of this channel
$\leftarrow$ channel hardware channel of this channel
Returns
DAQ channel ID
Definition at line 269 of file DecoderSet.hh.
References CALICE::FastDecoder::encodeU().
unsigned int CALICE::DecoderSet::getFeFromDAQID (const int DAQconnection) const [inline, inherited]
get fe from DAQ channel ID The right encoding string has to be set before.
See also
setDAQEncoding
Parameters
$\leftarrow$ DAQconnection DAQ connection ID to decode
Returns
fe
Definition at line 189 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::AhcMapper::getIndexByDAQID(), and CALICE::Ahc2Mapper::getIndexByDAQID().
unsigned int CALICE::AhcMapper::getIFromDAQID (const int DAQchannel) const [inline, inherited]
I of (Mokka) cellID.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
I
Exceptions
BadDataException if lookup fails
Definition at line 421 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getI(), and CALICE::AhcMapper::getModuleFromDAQID().
unsigned int CALICE::Ahc2Mapper::getIFromDAQID (const int DAQchannel) const [inline, inherited]
I of (Mokka) cellID.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
I
Exceptions
BadDataException if lookup fails
Definition at line 430 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getI(), and CALICE::Ahc2Mapper::getModuleFromDAQID().
virtual unsigned int CALICE::Mapper::getIndexByDAQID (const int ID) const [protected, pure virtual, inherited]
get a compact index for storing data in vectors
Parameters
$\leftarrow$ ID DAQ channel ID
Returns
compact index
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
Referenced by CALICE::MappedContainer< T >::deleteByDAQID(), CALICE::MappedContainer< T >::fillByDAQID(), CALICE::MappedContainer< T >::getByDAQID(), and CALICE::MappedContainer< T >::removeByDAQID().
unsigned int CALICE::AhcMapper::getISizeFromDAQID (const int DAQchannel) const [inline, inherited]
get cell size in I direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
size in I
Exceptions
BadDataException if lookup fails
Definition at line 577 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getISize(), and CALICE::AhcMapper::getModuleFromDAQID().
unsigned int CALICE::Ahc2Mapper::getISizeFromDAQID (const int DAQchannel) const [inline, inherited]
get cell size in I direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
size in I
Exceptions
BadDataException if lookup fails
Definition at line 586 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getISize(), and CALICE::Ahc2Mapper::getModuleFromDAQID().
unsigned int CALICE::AhcMapper::getJFromDAQID (const int DAQchannel) const [inline, inherited]
J of (Mokka) cellID.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
J
Exceptions
BadDataException if lookup fails
Definition at line 470 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getJ(), and CALICE::AhcMapper::getModuleFromDAQID().
unsigned int CALICE::Ahc2Mapper::getJFromDAQID (const int DAQchannel) const [inline, inherited]
J of (Mokka) cellID.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
J
Exceptions
BadDataException if lookup fails
Definition at line 479 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getJ(), and CALICE::Ahc2Mapper::getModuleFromDAQID().
unsigned int CALICE::AhcMapper::getJSizeFromDAQID (const int DAQchannel) const [inline, inherited]
get cell size in J direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
size in J
Exceptions
BadDataException if lookup fails
Definition at line 655 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::AhcMapper::getJSize(), and CALICE::AhcMapper::getModuleFromDAQID().
unsigned int CALICE::Ahc2Mapper::getJSizeFromDAQID (const int DAQchannel) const [inline, inherited]
get cell size in J direction of (Mokka) CellID coordinate
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
size in J
Exceptions
BadDataException if lookup fails
Definition at line 664 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::Ahc2Mapper::getJSize(), and CALICE::Ahc2Mapper::getModuleFromDAQID().
unsigned int CALICE::AhcMapper::getKFromDAQID (const int DAQchannel) const [inline, inherited]
K of (Mokka) cellID.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
K
Exceptions
BadDataException if lookup fails
Definition at line 519 of file AhcMapper.hh.
References CALICE::AhcMapper::getK(), and CALICE::AhcMapper::getModuleFromDAQID().
unsigned int CALICE::Ahc2Mapper::getKFromDAQID (const int DAQchannel) const [inline, inherited]
K of (Mokka) cellID.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
K
Exceptions
BadDataException if lookup fails
Definition at line 528 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getK(), and CALICE::Ahc2Mapper::getModuleFromDAQID().
virtual unsigned int CALICE::Mapper::getModuleFromDAQID (const int DAQchannel, bool & valid) const [pure virtual, inherited]
get module (number) in which this (DAQ) channel is included Checks if the channel exists. No exception is thrown.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
virtual unsigned int CALICE::Mapper::getModuleFromDAQID (const int DAQchannel) const [pure virtual, inherited]
get module (number) in which this (DAQ) channel is included
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
module
Exceptions
BadDataException if some error is detected, but no full verification is performed
See also
getModuleFromDAQID(const int DAQchannel, bool &valid)
Implemented in CALICE::Ahc2Mapper , and CALICE::AhcMapper .
unsigned int CALICE::AhcMapper::getModuleFromDAQID (const int DAQchannel, bool & valid) const [inline, virtual, inherited]
get module (number) in which this (DAQ) channel is included Checks if the channel exists. No exception is thrown.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implements CALICE::Mapper .
Definition at line 173 of file AhcMapper.hh.
References CALICE::AhcMapper::getIndexByDAQID().
unsigned int CALICE::AhcMapper::getModuleFromDAQID (const int DAQchannel) const [inline, virtual, inherited]
module number from DAQ channel ID
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
module number
Exceptions
BadDataException if lookup fails
Implements CALICE::Mapper .
Definition at line 104 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::AhcMapper::getModule().
Referenced by CALICE::AhcMapper::getIFromDAQID(), CALICE::AhcMapper::getISizeFromDAQID(), CALICE::AhcMapper::getJFromDAQID(), CALICE::AhcMapper::getJSizeFromDAQID(), and CALICE::AhcMapper::getKFromDAQID().
unsigned int CALICE::Ahc2Mapper::getModuleFromDAQID (const int DAQchannel, bool & valid) const [inline, virtual, inherited]
get module (number) in which this (DAQ) channel is included Checks if the channel exists. No exception is thrown.
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
$\rightarrow$ valid false if a non valid cell is queried
Returns
module
Implements CALICE::Mapper .
Definition at line 179 of file Ahc2Mapper.hh.
References CALICE::Ahc2Mapper::getIndexByDAQID().
unsigned int CALICE::Ahc2Mapper::getModuleFromDAQID (const int DAQchannel) const [inline, virtual, inherited]
module number from DAQ channel ID
Parameters
$\leftarrow$ DAQchannel DAQ channel ID
Returns
module number
Exceptions
BadDataException if lookup fails
Implements CALICE::Mapper .
Definition at line 110 of file Ahc2Mapper.hh.
References CALICE::Mapper::getDecoder(), and CALICE::Ahc2Mapper::getModule().
Referenced by CALICE::Ahc2Mapper::getIFromDAQID(), CALICE::Ahc2Mapper::getISizeFromDAQID(), CALICE::Ahc2Mapper::getJFromDAQID(), CALICE::Ahc2Mapper::getJSizeFromDAQID(), and CALICE::Ahc2Mapper::getKFromDAQID().
unsigned int CALICE::DecoderSet::getSlotFromDAQID (const int DAQconnection) const [inline, inherited]
get slot from DAQ channel ID The right encoding string has to be set before.
See also
setDAQEncoding
Parameters
$\leftarrow$ DAQconnection DAQ connection ID to decode
Returns
slot
Definition at line 199 of file DecoderSet.hh.
References CALICE::FastDecoder::decodeU().
Referenced by CALICE::AhcMapper::getIndexByDAQID(), and CALICE::Ahc2Mapper::getIndexByDAQID().
void CALICE::DecoderSet::setDAQEncoding (const std::string & encoding) [inherited]
set a new DAQ channel ID encoding string if an empty string is given the function will use the default encoding string
Parameters
$\leftarrow$ encoding encoding string
Definition at line 77 of file DecoderSet.cc.
References CALICE::FastDecoder::generateDecoder().
Referenced by CALICE::DecoderSet::DecoderSet().